### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by mudasarK** [jpmens/mosquitto-auth-plug#100]
please help me to compile, I am using ubunutu to make authentication plugin.
here is my config.mk file
# Select your backends from this list
BACKEND_CDB ?= no
BACKEND_MYSQL ?= yes
BACKEND_SQLITE ?= no
BACKEND_REDIS ?= no
BACKEND_POSTGRES ?= no
BACKEND_LDAP ?= no
BACKEND_HTTP ?= no
BACKEND_MONGO ?= no

# Specify the path to the Mosquitto sources here
MOSQUITTO_SRC = /home/mudasar/Downloads/mosquitto-1.4.4

# Specify the path the OpenSSL here
OPENSSLDIR = /usr

and when I run the make command this is the log
/home/mudasar/mosquitto-auth-plug# make
Selected backends:          MySQL
Using mosquitto source dir: /home/mudasar/Downloads/mosquitto-1.4.4
OpenSSL install dir:        /usr

If you changed the backend selection, you might need to 'make clean' first

cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o base64.o base64.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o pbkdf2-check.o pbkdf2-check.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o log.o log.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o envs.o envs.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o hash.o hash.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o be-psk.o be-psk.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o backends.o backends.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o cache.o cache.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o be-mysql.o be-mysql.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include  -L/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -lcares -fPIC -shared -o auth-plug.so auth-plug.o base64.o pbkdf2-check.o log.o envs.o hash.o be-psk.o backends.o cache.o be-mysql.o   `mysql_config --libs` -L/usr/lib -lcrypto -lmosquitto
/usr/bin/ld: cannot find -lmosquitto
collect2: error: ld returned 1 exit status
make: *** [auth-plug.so] Error 1

**Comment by mudasarK** [comment]
Thanks Finally I figured it out and its done.
Here is the log

/home/mudasar/mosquitto-auth-plug#  make
Selected backends:          MySQL
Using mosquitto source dir: /home/mudasar/Downloads/mosquitto-1.4.4
OpenSSL install dir:        /usr

If you changed the backend selection, you might need to 'make clean' first

cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o base64.o base64.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o pbkdf2-check.o pbkdf2-check.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o log.o log.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o envs.o envs.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o hash.o hash.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o be-psk.o be-psk.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o backends.o backends.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o cache.o cache.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o be-mysql.o be-mysql.c
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include  -L/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -lcares -fPIC -shared -o auth-plug.so auth-plug.o base64.o pbkdf2-check.o log.o envs.o hash.o be-psk.o backends.o cache.o be-mysql.o   `mysql_config --libs` -L/usr/lib -lcrypto -lmosquitto
cc -I/home/mudasar/Downloads/mosquitto-1.4.4/src/ -I/home/mudasar/Downloads/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include np.c base64.o -o np -L/usr/lib -lcrypto

**Comment by mudasarK** [comment]
Connection failed after mosquitto auth plugin added.
Please help

1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init

**Comment by jpmens** [comment]
Instead of pasting loads of useless output, would you please first **read** what you paste? It clearly says:

```
undefined symbol: ares_library_init
```

so you have an unresolved library. Hint: you compiled Mosquitto/plugin with SRV support but you are missing the libraries (ares) for it.

**Comment by mudasarK** [comment]
Sorry I am new to ubuntu and Mqtt that's why don't know what to do. 
Sure looking for it.

Thank you

**Comment by mudasarK** [comment]
Hello Jpmens,

sorry to disturb you again, can you please tell me how to resolve this problem ?
I have checked ares libraries are already up to date in my ubunu.

Thank you

**Comment by jpmens** [comment]
Compile Mosquitto with

        WITH_SRV:=no

in config.mk

**Comment by mudasarK** [comment]
sure.

Thank you

**Comment by mudasarK** [comment]
Sorry to disturb again.
There is a socket problem, I don't know the reason that's why asking.
please help

1445588839: New connection from 127.0.0.1 on port 1883.
1445588839: New client connected from 127.0.0.1 as mosqpub/10279-mudasar-M (c1, k60).
1445588839: Client mosqpub/10279-mudasar-M disconnected.
1445588855: Socket error on client mosqsub/10165-mudasar-M, disconnecting

Thank you
.

**Comment by mudasarK** [comment]
Sorry this issue is resolved, there was a problem with my mosquitto.conf file.
but there is one more issue, I am unable to connect to server whenever trying to subscribe or publish.
it always give the error like "Error : Connection refused"
don't know whats wrong now
