### ISSUE TITLE
Connection refused after adding mosquitto-auth-plugin

### ISSUE THREAD

**Issue by mudasarK** [jpmens/mosquitto-auth-plug#101]
please see my previous logs from this link
https://github.com/jpmens/mosquitto-auth-plug/issues/100

Connection failed after mosquitto auth plugin added.
Please help

1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init
1445580577: mosquitto version 1.4.4 (build date Thu, 17 Sep 2015 16:05:13 +0100) starting
1445580577: Config loaded from /etc/mosquitto/mosquitto.conf.
1445580577: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1445580577: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init

**Comment by jpmens** [comment]
Answered in https://github.com/jpmens/mosquitto-auth-plug/issues/100
