### ISSUE TITLE
Connection refused after adding mosquitto-auth-plugin

### ISSUE THREAD

**Issue by mudasarK** [jpmens/mosquitto-auth-plug#103]
Hi, 
Please help, whenever I add auth plug-in it stop working and shows connection refused, and If I remove auth plug-in form .conf file it starts working. Also I have noticed after adding auth plug-in to .conf file server stops, while I have checked to ping my database it is working with provided info as here in conf file.
Here is my conf file
# Authentication config

auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_host 127.0.0.1
auth_opt_port 3306
auth_opt_dbname mqtt
auth_opt_user root
auth_opt_pass [removing for a reason]
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = '%s' AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw >= %d)
auth_opt_anonusername AnonymouS

and trying to subscribe the message with provided db and the data as in your example, 
mosquitto_sub -d -t loc/test/abc -u a -P acl:a
Error: Connection refused

Please help me.

Thank you

**Comment by jpmens** [comment]
Show me the startup messages printed to stdout/stderr when you launch Mosquitto manually (mosquitto -c conf -v)

**Comment by mudasarK** [comment]
Here is the log
mosquitto -c mosquitto.conf -v
1445928666: mosquitto version 1.4.4 (build date 2015-10-23 17:13:16+0900) starting
1445928666: Config loaded from mosquitto.conf.
1445928666: |-- *** auth-plug: startup
|-- No backends configured.
|-- *** ABORT.

**Comment by mudasarK** [comment]
I figured out I forget to add back end.

Thank you for you help, last question can you tell me how to create the pass and use it while subscribing and publishing the message.

Thank you

**Comment by jpmens** [comment]
Read the documentation. Please.

**Comment by mudasarK** [comment]
Sure 
Thank you so much for the help.

**Comment by mudasarK** [comment]
I am in serious trouble and don't know what’s wrong,

When I run this, it connection refuse, and .conf file is configured as above mentioned
r@mudasar-MS-7599:~$ mosquitto_pub  -t loc/test -m hello -u a -P PBKDF2$sha256$901$XPkOwNbd05p5XsUn$1uPtR6hMKBedWE44nqdVg+2NPKvyGst8
Connection Refused: not authorised.
Error: The connection was refused.

Server side error is
1445935994: New connection from 127.0.0.1 on port 1883.
1445935994: |-- mosquitto_auth_unpwd_check(a)
1445935994: |-- ** checking backend mysql
1445935994: |-- getuser(a) AUTHENTICATED=0 by none
1445935994: Sending CONNACK to 127.0.0.1 (0, 5)
1445935994: Socket error on client <unknown>, disconnecting.

Please give some hint.

I am on tight time line and its taking too long for me.

Thank you

**Comment by mudasarK** [comment]
Hello Mr. Jp,

I got it, it is problem with the password, Well I don't have idea how to create the pass which will work with your plugin using java, can you give some hint ?

Thank you

**Comment by mudasarK** [comment]
Ho,

I got it too into contrib folder,  

Thank you so much for wonderful plugin.
