### ISSUE TITLE
Windows compile

### ISSUE THREAD

**Issue by Spekko** [jpmens/mosquitto-auth-plug#108]
Hi

Would like to complile this plugin on windows. Havent compiled too much C code in the past so before I just jump into the makefile I just want to know if it will be possible with this existing code-set.

Thanx

**Comment by Spekko** [comment]
I have just tried to compile the .so on linux and tried running it on windows but it gave an error stating some OS issues.

**Comment by ikarbiztech** [comment]
I have no experience with C but you need to have some points clear if you try to use a ".so" in your windows machine (hope this helps a little).

You will have problems with .so files. The linux "so" files are "dll" in windows, no idea if the final compilation uses these dynamic libraries, but you have to deal with this problem.

Check the makefile for windows compilation and solve the problems with the dependencies, at least you will need to give the proper paths for OpenSSL in windows, for Mosquitto and DB libraries, and be sure to have the needed C libs installed or accesible in your system.

**Comment by Spekko** [comment]
thanx, that is true, it skipped my mind that .so was the linux dll, got so use to linux the past while. so it should in the end be possible. Think Ill give it a go

**Comment by jpmens** [comment]
https://github.com/jpmens/mosquitto-auth-plug/issues/91

**Comment by Spekko** [comment]
thanx :+1:
