### ISSUE TITLE
Problem with LDAP

### ISSUE THREAD

**Issue by ikarbiztech** [jpmens/mosquitto-auth-plug#109]
No idea why, but with my configuration I only get "Connection Refused: not authorized."

Here is what I have done:

Configuration for "mosquitto.config":

>#Place your local configuration in /etc/mosquitto/conf.d/
>pid_file /var/run/mosquitto.pid
>persistence true
>persistence_location /var/lib/mosquitto/
>#log_dest file /var/log/mosquitto/mosquitto.log
>include_dir /etc/mosquitto/conf.d

My configiguration inside "conf.d/auth.conf":

>allow_anonymous false
>auth_plugin /home/sysadmin/mosquitto/auth-plug.so
>auth_opt_backends ldap
>auth_opt_binddn cn=Manager,dc=example,dc=com
>auth_opt_bindpw redhat
>auth_opt_ldap_uri ldap://127.0.0.1/o=mosquitto,ou=People,dc=example,dc=com?cn?sub?(&(objectclass=inetOrgPerson)(uid=@))

My configuration inside LDAP (taken from Apache Directory Studio):
![image](https://cloud.githubusercontent.com/assets/14893538/10841501/118e7a9a-7eea-11e5-89d7-b26f284e1eeb.png)

When I use this command I get "not authorized connection"! (I get the same from my Java code...)
> mosquitto_sub -t hello/world -u iker-P iker

Any ideas or help?? thanks!!

*More details:*
![image](https://cloud.githubusercontent.com/assets/14893538/10842849/291c32d2-7ef5-11e5-9a22-92dc3b0ce656.png)

**Comment by jpmens** [comment]
Thank goodness you showed screenshots or this could have taken a while ... ;-)

You have configured `auth_opt_ldap_uri` to include `(uid=@)` as search attribute type, but your LDAP entry doesn't have `uid` as far as I can see. Replace that by `(cn=@)` and it should work.

**Comment by ikarbiztech** [comment]
I have made the change.... it doesn't work... any idea???

**Comment by jpmens** [comment]
You are going to have to use `ldapsearch` to find a combination which does work; there's not much I can do to help. Verify that your directory server is actually serving what you think it should, verify credentials, search base, etc.

**Comment by ikarbiztech** [comment]
This is what I get with LDAPSEARCH, but still not working :-(

>sudo ldapsearch -x cn=iker -b o=mosquitto,ou=People,dc=example,dc=com
> extended LDIF
>
> LDAPv3
> base <o=mosquitto,ou=People,dc=example,dc=com> with scope subtree
> filter: cn=iker
> requesting: ALL
>

> iker, mosquitto, People, example.com
>dn: cn=iker,o=mosquitto,ou=People,dc=example,dc=com
>sn: iker
>cn: iker
>objectClass: person
>objectClass: top
>userPassword;lang-es-es: iker

> search result
>search: 2
>result: 0 Success

> numResponses: 2
> numEntries: 1

**Comment by jpmens** [comment]
Drop the sudo (useless).

And now try to authenticate:

```
ldapsearch .... -D "cn=iker,o=mosquitto,ou=People,dc=example,dc=com" -W
```

**Comment by ikarbiztech** [comment]
No idea why I have the same result o_O

>ldapsearch -h localhost -p 389 -D "cn=iker,o=mosquitto,ou=People,dc=example,dc=com" -W
>Enter LDAP Password:
>ldap_bind: Invalid credentials (49)

**Comment by jpmens** [comment]
If you cannot bind as that user on the command line, the plugin cannot either!

Your password is incorrect or your directory server isn't allowing credentials being passed in clear; you might have to switch to TLS.

**Comment by ikarbiztech** [comment]
Ok, ok, I have configured again the LDAP with a "step by step" manual, and I have the following configuration now:

>allow_anonymous false
>auth_plugin /home/sysadmin/mosquitto/auth-plug.so
>auth_opt_backends ldap
>auth_opt_binddn cn=Manager,dc=example,dc=com
>auth_opt_bindpw redhat
>auth_opt_ldap_uri ldap://127.0.0.1/ou=People,dc=example,dc=com?cn?sub?(&(objectclass=inetOrgPerson)(uid=@))

With this new configuration for LDAP:

![image](https://cloud.githubusercontent.com/assets/14893538/10880269/2e6a92e4-815a-11e5-9c3e-8676d103dd10.png)

And trying to use the following user:
![image](https://cloud.githubusercontent.com/assets/14893538/10880288/4d199f64-815a-11e5-8de8-40d1aa3ddd04.png)

and now when I try to log in by the console, I get this:

>$ ldapsearch -h localhost -p 389 -D "uid=ldapuser01,ou=People,dc=example,dc=com" -W
>Enter LDAP Password:
> extended LDIF

> LDAPv3
> base <> (default) with scope subtree
> filter: (objectclass=*)
> requesting: ALL


> search result
>search: 2
>result: 32 No such object

> numResponses: 1

But when I try with the "mosquitto_sub":

> mosquitto_sub -t hello/world -u ldapuser01 -P ldapuser01
>Connection Refused: not authorised.
>Connection Refused: not authorised.

Now I am not sure what I have to do with the mosquitto and the plugin... but the LDAP seems to work....

**Comment by jpmens** [comment]
Launch Mosquitto in the foreground and show me what it is logging to stderr while you attempt the `mosquitto_sub`, please.

**Comment by ikarbiztech** [comment]
Here it's (after launching  
mosquitto_sub -t hello/world -u ldapuser01 -P ldapuser01
)


> sudo ./mosquitto -c /etc/mosquitto/mosquitto.conf
>1446541155: mosquitto version 1.4.4 (build date 2015-09-24 08:11:44+0000) starting
>1446541155: Config loaded from /etc/mosquitto/mosquitto.conf.
>1446541155: |-- *** auth-plug: startup
>1446541155: |-- ** Configured order: ldap
>1446541155: |-- }}}} LDAP
>1446541155: Opening ipv4 listen socket on port 1883.
>1446541155: Opening ipv6 listen socket on port 1883.
>1446541202: New connection from ::1 on port 1883.
>1446541202: |-- mosquitto_auth_unpwd_check(ldapuser01)
>1446541202: |-- ** checking backend ldap
>1446541202: |-- LDAP search for ldapuser01 returns != 1 entry
>1446541202: |-- getuser(ldapuser01) AUTHENTICATED=0 by none
>1446541202: Socket error on client <unknown>, disconnecting.
>1446541203: New connection from ::1 on port 1883.
>1446541203: |-- mosquitto_auth_unpwd_check(ldapuser01)
>1446541203: |-- ** checking backend ldap
>1446541203: |-- LDAP search for ldapuser01 returns != 1 entry
>1446541203: |-- getuser(ldapuser01) AUTHENTICATED=0 by none
>1446541203: Socket error on client <unknown>, disconnecting.
>1446541204: New connection from ::1 on port 1883.
>1446541204: |-- mosquitto_auth_unpwd_check(ldapuser01)
>1446541204: |-- ** checking backend ldap
>1446541204: |-- LDAP search for ldapuser01 returns != 1 entry
>1446541204: |-- getuser(ldapuser01) AUTHENTICATED=0 by none
>1446541204: Socket error on client <unknown>, disconnecting.
>1446541205: New connection from ::1 on port 1883.
>1446541205: |-- mosquitto_auth_unpwd_check(ldapuser01)
>1446541205: |-- ** checking backend ldap
>1446541205: |-- LDAP search for ldapuser01 returns != 1 entry
>1446541205: |-- getuser(ldapuser01) AUTHENTICATED=0 by none
>1446541205: Socket error on client <unknown>, disconnecting.
>1446541206: New connection from ::1 on port 1883.
>1446541206: |-- mosquitto_auth_unpwd_check(ldapuser01)
>1446541206: |-- ** checking backend ldap
>1446541206: |-- LDAP search for ldapuser01 returns != 1 entry
>1446541206: |-- getuser(ldapuser01) AUTHENTICATED=0 by none
>1446541206: Socket error on client <unknown>, disconnecting.
>^C1446541206: mosquitto version 1.4.4 terminating
>1446541206: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.

**Comment by jpmens** [comment]
What the plugin does is basic authentication with credentials sent in the clear (i.e. no SASL currently). So please try to authenticate accordingly from the shell:

```
ldapsearch -x -h localhost -p 389 -D "uid=ldapuser01,ou=People,dc=example,dc=com" -W
```

(Note the addition of `-x`)

The plugin is not finding the user, possibly because it's not allowed to BIND in clear text.

**Comment by jpmens** [comment]
Come to think of it, please do it this way and show output:

```
ldapsearch -x -LLL -h localhost -p 389 -D "uid=ldapuser01,ou=People,dc=example,dc=com" -W -b ou=people,dc=example,dc=com uid=ldapuser01
```

**Comment by ikarbiztech** [comment]
Here:
>$ ldapsearch -x -LLL -h localhost -p 389 -D "uid=ldapuser01,ou=People,dc=example,dc=com" -W -b
 >ou=people,dc=example,dc=com uid=ldapuser01
>Enter LDAP Password:
>dn: uid=ldapuser01,ou=People,dc=example,dc=com
>uid: ldapuser01
>cn: ldapuser01
>objectClass: account
>objectClass: posixAccount
>objectClass: top
>loginShell: /bin/bash
>uidNumber: 1003
>gidNumber: 1003
>homeDirectory: /home/guests/ldapuser01
>userPassword:: bGRhcHVzZXIwMQ==

**Comment by jpmens** [comment]
You have configured

```
auth_opt_binddn cn=Manager,dc=example,dc=com
auth_opt_bindpw redhat
auth_opt_ldap_uri ldap://127.0.0.1/o=mosquitto,ou=People,dc=example,dc=com?cn?sub?(&(objectclass=inetOrgPerson)(uid=@))
```

Questions:

1. does the object `cn=Manager,dc=example,dc=com` with that password (`redhat`) actually exist?
2. may that object search your directory?
3. Your user is *not* in the `o=mosquitto,ou=People,dc=example,dc=com` base (drop the `o=mosquitto`)
4. You are searching for users who have `(objectclass=inetOrgPerson)`, but your user doesn't have that class

So what do you expect the auth plugin to actually find?

**Comment by ikarbiztech** [comment]
The configuration I have right now is as follows (check yesterday comment plz) :-( 
>allow_anonymous false
>auth_plugin /home/sysadmin/mosquitto/auth-plug.so
>auth_opt_backends ldap
>auth_opt_binddn cn=Manager,dc=example,dc=com
>auth_opt_bindpw redhat
>auth_opt_ldap_uri ldap://127.0.0.1/ou=People,dc=example,dc=com?cn?sub?(&(objectclass=inetOrgPerson)(uid=@))

1. It exists, I can access the LDAP with it from my apache Directory Studio :-(
2. I can navigate with this user through the directory shown in the Apache Directory Studio (I can access ou=People ...)
3. I don't have "o=mosquitto" (check the conf again, please)
4. You where right, this one was the problem, now it works!!!! (didn't realize about this... sorry) :-( 

Thanks a lot!!!  :-)

**Comment by jpmens** [comment]
OK, glad you got it working.
