### ISSUE TITLE
Auth Plugin Memory issue 

### ISSUE THREAD

**Issue by yunju123** [jpmens/mosquitto-auth-plug#116]
HI. 

Thanks for supporting great plugin :)

I am using Redis to check acl and I got OOM by Kernel Monitoring yesterday while load test
- 100 tps with 10,000 clients were connected for 12 hours.

Here is my Kernel log, 
# 

Dec 19 06:57:57 vexommbwst1 kernel: lowmem_reserve[]: 0 0 0 0
Dec 19 06:57:57 vexommbwst1 kernel: Node 0 DMA: 3_4kB 2_8kB 1_16kB 2_32kB 2_64kB 1_128kB 0_256kB 0_512kB 1_1024kB 1_2048kB 3_4096kB = 15724kB
Dec 19 06:57:57 vexommbwst1 kernel: Node 0 DMA32: 815_4kB 415_8kB 168_16kB 400_32kB 136_64kB 35_128kB 11_256kB 8_512kB 6_1024kB 0_2048kB 0_4096kB = 48308kB
Dec 19 06:57:57 vexommbwst1 kernel: Node 0 Normal: 778_4kB 755_8kB 406_16kB 180_32kB 87_64kB 22_128kB 2_256kB 9_512kB 1_1024kB 0_2048kB 0_4096kB = 35936kB
Dec 19 06:57:57 vexommbwst1 kernel: 4450 total pagecache pages
Dec 19 06:57:57 vexommbwst1 kernel: 963 pages in swap cache
Dec 19 06:57:57 vexommbwst1 kernel: Swap cache stats: add 12558234, delete 12557271, find 6974971/7156595
Dec 19 06:57:57 vexommbwst1 kernel: Free swap  = 0kB
Dec 19 06:57:57 vexommbwst1 kernel: Total swap = 8388604kB
Dec 19 06:57:57 vexommbwst1 kernel: Node 0 DMA32: 815_4kB 415_8kB 168_16kB 400_32kB 136_64kB 35_128kB 11_256kB 8_512kB 6_1024kB 0_2048kB 0_4096kB = 48308kB
Dec 19 06:57:57 vexommbwst1 kernel: Node 0 Normal: 778_4kB 755_8kB 406_16kB 180_32kB 87_64kB 22_128kB 2_256kB 9_512kB 1_1024kB 0_2048kB 0*4096kB = 35936kB
Dec 19 06:57:57 vexommbwst1 kernel: 4450 total pagecache pages
Dec 19 06:57:57 vexommbwst1 kernel: 963 pages in swap cache
Dec 19 06:57:57 vexommbwst1 kernel: Swap cache stats: add 12558234, delete 12557271, find 6974971/7156595
Dec 19 06:57:57 vexommbwst1 kernel: Free swap  = 0kB
Dec 19 06:57:57 vexommbwst1 kernel: Total swap = 8388604kB
Dec 19 06:57:57 vexommbwst1 kernel: 2095103 pages RAM
Dec 19 06:57:57 vexommbwst1 kernel: 86022 pages reserved
Dec 19 06:57:57 vexommbwst1 kernel: 4752 pages shared
Dec 19 06:57:57 vexommbwst1 kernel: 1973108 pages non-shared
Dec 19 06:57:57 vexommbwst1 kernel: [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
Dec 19 06:57:57 vexommbwst1 kernel: [  439]     0   439     2690       28   0     -17         -1000 udevd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1197]     0  1197    23283       86   3     -17         -1000 auditd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1227]     0  1227    62993      855   0       0             0 rsyslogd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1246]     0  1246     2727       88   0       0             0 irqbalance
Dec 19 06:57:57 vexommbwst1 kernel: [ 1273]    81  1273     5358       42   2       0             0 dbus-daemon
Dec 19 06:57:57 vexommbwst1 kernel: [ 1291]     0  1291    47233       19   0       0             0 cupsd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1319]     0  1319     1020       13   0       0             0 acpid
Dec 19 06:57:57 vexommbwst1 kernel: [ 1329]    68  1329     9474      175   0       0             0 hald
Dec 19 06:57:57 vexommbwst1 kernel: [ 1330]     0  1330     5100       20   2       0             0 hald-runner
Dec 19 06:57:57 vexommbwst1 kernel: [ 1359]     0  1359     5630       18   0       0             0 hald-addon-inpu
Dec 19 06:57:57 vexommbwst1 kernel: [ 1371]    68  1371     4502       18   0       0             0 hald-addon-acpi
Dec 19 06:57:57 vexommbwst1 kernel: [ 1391]     0  1391    16554       26   2     -17         -1000 sshd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1400]    38  1400     6627      110   0       0             0 ntpd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1412]     0  1412    13027       35   1       0             0 vsftpd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1490]     0  1490    20215       53   0       0             0 master
Dec 19 06:57:57 vexommbwst1 kernel: [ 1504]    89  1504    20278       65   1       0             0 qmgr
Dec 19 06:57:57 vexommbwst1 kernel: [ 1515]     0  1515    28661       39   1       0             0 abrtd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1523]     0  1523    28133       41   1       0             0 abrt-dump-oops
Dec 19 06:57:57 vexommbwst1 kernel: [ 1533]     0  1533    29223       67   0       0             0 crond
Dec 19 06:57:57 vexommbwst1 kernel: [ 1546]     0  1546     5276       15   3       0             0 atd
Dec 19 06:57:57 vexommbwst1 kernel: Out of memory: Kill process 58145 (mosquitto) score 832 or sacrifice child
Dec 19 06:57:57 vexommbwst1 kernel: Killed process 58145, UID 503, (mosquitto) total-vm:13690032kB, anon-rss:5300928kB, file-rss:684kB
Dec 19 06:57:57 vexommbwst1 kernel: [ 1562]     0  1562     1016       14   0       0             0 mingetty
Dec 19 06:57:57 vexommbwst1 kernel: [ 1564]     0  1564     1016       14   2       0             0 mingetty
Dec 19 06:57:57 vexommbwst1 kernel: [ 1566]     0  1566     1016       14   2       0             0 mingetty
Dec 19 06:57:57 vexommbwst1 kernel: [ 1568]     0  1568     1016       14   2       0             0 mingetty
Dec 19 06:57:57 vexommbwst1 kernel: [ 1570]     0  1570     1016       14   2       0             0 mingetty
Dec 19 06:57:57 vexommbwst1 kernel: [ 1572]     0  1572     1016       14   2       0             0 mingetty
Dec 19 06:57:57 vexommbwst1 kernel: [ 1576]     0  1576     2689       27   0     -17         -1000 udevd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1577]     0  1577     2689       27   0     -17         -1000 udevd
Dec 19 06:57:57 vexommbwst1 kernel: [ 1583]     0  1583     7473      181   3       0             0 VAGENT
Dec 19 06:57:57 vexommbwst1 kernel: [ 1719]     0  1719     3523       92   0       0             0 cmd_scd
Dec 19 06:57:57 vexommbwst1 kernel: [ 2393]     0  2393    87747     1558   1       0             0 SMSAGENT
Dec 19 06:57:57 vexommbwst1 kernel: [ 2806]     0  2806     3523      107   0       0             0 cmd_scd
Dec 19 06:57:57 vexommbwst1 kernel: [129338]     0 129338    26718      354   3       0             0 sh
Dec 19 06:57:57 vexommbwst1 kernel: [58145]   503 58145  3422508  1325403   3       0             0 mosquitto
Dec 19 06:57:57 vexommbwst1 kernel: [39797]   502 39797    26558       24   2       0             0 catalina.sh
Dec 19 06:57:57 vexommbwst1 kernel: [39798]   502 39798     1030       41   0       0             0 cronolog
Dec 19 06:57:57 vexommbwst1 kernel: [39799]   502 39799  1340723   590005   0       0             0 java
Dec 19 06:57:57 vexommbwst1 kernel: [60250]     0 60250     3806      181   0       0             0 nmon_x86_64_rhe
Dec 19 06:57:57 vexommbwst1 kernel: [66526]    89 66526    20235      294   0       0             0 pickup
Dec 19 06:57:57 vexommbwst1 kernel: [76661]     0 76661    25227      141   1       0             0 sleep
Dec 19 06:57:57 vexommbwst1 kernel: Out of memory: Kill process 58145 (mosquitto) score 832 or sacrifice child
Dec 19 06:57:57 vexommbwst1 kernel: Killed process 58145, UID 503, (mosquitto) total-vm:13690032kB, anon-rss:5300928kB, file-rss:684kB
# 

I thought my json parser code has something wrong but I found memory usage was still getting increase when I removed my code. 

Here are what I've tested (Each case under same load for 1 hour)
1. Mosquitto without auth plugin   ->  no memory increased
2. Mosquitto with auth plugin, add the first line "return 1" on "be_redis_aclcheck" method.
   -> memory increased :(
3. Mosquitto with auth plugin, set cacheseconds 0 on config file 
   -> no memory increased

So, I think there are some memory leak problem on using cache. 

Could you please check it?

Thanks

**Comment by jpmens** [comment]
Is this still the case?

**Comment by jpmens** [comment]
Closing because of no response.

**Comment by yunju123** [comment]
I'm sorry to response to late. 

When I set cacheseconds to 0 , there were no memory leak so I believed caching had something wrong. 

I think this problem is already solved #86.
