### ISSUE TITLE
np : segmentation fault if using -i

### ISSUE THREAD

**Issue by dethegeek** [jpmens/mosquitto-auth-plug#117]
Hi

For testing purpose, I used np to generate a password hash.

I noticed I cannot specify a interation number. It looks like simply using -i (without argument or any number) crashed the program.

examples : 
np -i 
np -i 1 -p test
np -i 1
np -i 901 (found in the source code)

All of these make a segmentation fault.

Anyway, thank you for this plugin :)

**Comment by jpmens** [comment]
Very sorry about this. Fixed.
