### ISSUE TITLE
 ACL checks - Write ONLY access

### ISSUE THREAD

**Issue by harisk74** [jpmens/mosquitto-auth-plug#119]
Mosquitto defines three access modes read|write|readwrite in ACLs

In docs of mosquitto-auth-plug only to are defined read=1, readwrite=2.
How can we achieve wrte only access ?

**Comment by jpmens** [comment]
This is currently not possible in the plugin.

**Comment by harisk74** [comment]
Hi,
    Thanks for clearing up this matter. I would just like to support the
idea of implementing write-only access.
I believe there are numerous use cases that we need to allow write-only
access.
Trying to make an analogy with email, is like allowing everyone who has
a right to send you an email be able to read your mailbox too.

Hope you will consider to implement write-only access.

Thanks in advance

Charis

On 3/2/2016 1:39 μμ, JP Mens wrote:
> This is currently not possible in the plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpmens/mosquitto-auth-plug/issues/119#issuecomment-179179471>.
>


-- 
----------------------------------------------------      
Koutsouris Charalampos, MSc, CISA,CISSP
Institute of Informatics and Telecommunications,
NCSR "Demokritos",
153-10 Agia Paraskevi , Athens, GREECE
Tel: +30 - 210 - 6503125
Fax: +30 - 210 - 6543615
E-mail: harisk@iit.demokritos.gr
mobile : 0030 6981013265
Skype : koutsourish
---------------------------------------------------- 



---
Αυτό το e-mail ελέγχθηκε για ιούς από το πρόγραμμα Avast antivirus.
https://www.avast.com/antivirus

**Comment by btry** [comment]
Hi

I also need this feature (I'm using mysql).

I quickly reviewed the source and I see that
- READ = 1
- WRITE = 2

Therefore ach capability has its own bit.

I change my ACL query to be similar to the example found in the source 
```SELECT topic FROM table WHERE username = '%s' AND (acc & %d)```

I created a user ```test``` with acc = 3 and tried tu subscribe in a terminal and publish with an other one. It worked.

I set acc = 1 (read only), and it subscribed successfully, but failed to publish.

I set acc = 2 (write only) and it subscribed successfully, but did not received a mesage published with the same user.

Tio ensure the publish worked, I created a user ```test2``` with acc = 1 and tried again. the user ```test2```received the message sent by ```test```.

I *believe* this is already working as long the acl is used as a bit field.

@jpmens  I'm waiting for your review 

Thanks

**Comment by jpmens** [comment]
@btry you know my code better than I do! Yes, you're right: for mysql and postgres backends this works, but not generally for the others IIRC.

**Comment by btry** [comment]
Thank you very much for your feedback. I'll keep the change in my SQL query.

**Comment by harisk74** [comment]
Thanks btry and jpmens. It's great that we have this obstacle removed.

**Comment by 7wonders** [comment]
Is it basically that we should use the bit type on the rw column in postgres and adjust the query accordingly to achieve this?

**Comment by btry** [comment]
Hi

As long as you can compare your column against a bit mask it should work. I guess it is not necessary to change the type of your rw column.

In my case, my column is a int(2) (mysql)

**Comment by cordovapolymer** [comment]
It's also required in mongodb plugin!

**Comment by rh389** [comment]
@cordovapolymer it is now!

```json
{
  "username": "user1",
  "password": "...",
  "topics": {
    "my/write/only/topic":"w"
  }
}
```
