### ISSUE TITLE
Issue in receiving messages after mosquitto is restarted

### ISSUE THREAD

**Issue by 87sanchavan** [jpmens/mosquitto-auth-plug#120]
Hi ,
Thanks for building this plugin.  I have configured mosquitto-auth-plug with Redis as backend. It is working fine without the broker restart . however there is one issue when I restart the broker.

I was testing with two clients connected to the broker and they subscribed to a topic 'c/d'. When the broker goes down or restarted . After restart , when client 1 publish some message on topic 'c/d' , both client should receive this message :Client 1 immediately since it is connected and client 2 when it is connected.  **my problem is client 2 is not getting message.** 
I did check the logs and found out that 

** Without Restart**

1454684764: |-- mosquitto_auth_acl_check(..., 100, sanjay, c/d, MOSQ_ACL_WRITE)
1454684764: |-- aclcheck(sanjay, c/d, 2) CACHEDAUTH: 0
1454684764: Received PUBLISH from 100 (d0, q1, r0, m3, 'c/d', ... (12 bytes))
1454684764: |-- mosquitto_auth_acl_check(..., 200, arun-kumar, c/d, MOSQ_ACL_READ)
1454684764: |-- aclcheck(arun-kumar, c/d, 1) CACHEDAUTH: 0
1454684764: |-- mosquitto_auth_acl_check(..., 100, sanjay, c/d, MOSQ_ACL_READ)
1454684764: |-- aclcheck(sanjay, c/d, 1) CACHEDAUTH: 0

**After Restart**

: Received PUBLISH from 100 (d0, q1, r0, m1, 'c/d', ... (12 bytes))
1454685132: |-- mosquitto_auth_acl_check(..., 200, anonymous, c/d, MOSQ_ACL_READ)
1454685132: |-- aclcheck(anonymous, c/d, 1) AUTHORIZED=0 by (null)
1454685132: |--  Cached  [908A0FA242480195EB5F21830171B9DA2A320160] for (200,anonymous,1)
1454685132: |-- mosquitto_auth_acl_check(..., 100, sanjay, c/d, MOSQ_ACL_READ)
1454685132: |-- aclcheck(sanjay, c/d, 1) trying to acl with redis
1454685132: |-- aclcheck(sanjay, c/d, 1) AUTHORIZED=1 by redis
1454685132: |--  Cached  [B0D0747F31EE9BD5699EC1199C33953B3B1F2497] for (100,sanjay,1)
1454685132: |-- mosquitto_auth_acl_check(..., sanjay, anonymous, c/d, MOSQ_ACL_READ)
1454685132: |-- aclcheck(anonymous, c/d, 1) AUTHORIZED=0 by (null)
1454685132: |--  Cached  [2EDBDC81C848D6EB0CC01530C9FB4D8F5C947985] for (sanjay,anonymous,1)
1454685132: |-- mosquitto_auth_acl_check(..., 300, anonymous, c/d, MOSQ_ACL_READ)
1454685132: |-- aclcheck(anonymous, c/d, 1) AUTHORIZED=0 by (null)
1454685132: |--  Cached  [6E0199ACEA5195725E31DEBCCE004C96BF6D94A6] for (300,anonymous,1)
1

My observation is in the line 
mosquitto_auth_acl_check( ) 
1. without restart -  it was using actual user as username
2. after restart - it is using anonymous as username .
 
Can you please help me in solving this issue.

Thanks
Sanjay

**Comment by jpmens** [comment]
The clientIDs you are using have changed (100, vs 200).

> 1454684764: |-- mosquitto_auth_acl_check(, 100, sanjay, c/d, MOSQ_ACL_WRITE)
> 1454685132: |-- mosquitto_auth_acl_check(, 200, anonymous, c/d, MOSQ_ACL_READ)

I would suggest your client reconnected with a new id but without authentication.

**Comment by 87sanchavan** [comment]
Thank you sir for quick response. actually 200 client id was not yet connected however it was subscribed to message published by 100.

I have followed below steps. I have used 888 and 999 client Ids. 
1. Server started 
2.both client connected and subscribed to c/d.
3. server is down , both clients automatically disconnected
4.server restarted 
5.client 888 is connected back and published message and below is log for that.



1454687854: |-- mosquitto_auth_acl_check(..., 888, sanjay, c/d, MOSQ_ACL_WRITE)
1454687854: |-- aclcheck(sanjay, c/d, 2) trying to acl with redis
1454687854: |-- aclcheck(sanjay, c/d, 2) AUTHORIZED=1 by redis
1454687854: |--  Cached  [7D30DD393F55FF86733C9A34C7F89F4F3D9F7141] for (888,sanjay,2)
1454687854: Received PUBLISH from 888 (d0, q1, r0, m1, 'c/d', ... (12 bytes))
1454687854: |-- mosquitto_auth_acl_check(..., 888, sanjay, c/d, MOSQ_ACL_READ)
1454687854: |-- aclcheck(sanjay, c/d, 1) trying to acl with redis
1454687854: |-- aclcheck(sanjay, c/d, 1) AUTHORIZED=1 by redis
1454687854: |--  Cached  [DA206D115B412A2B9049346DA75921B32F3E9F37] for (888,sanjay,1)
1454687854: |-- mosquitto_auth_acl_check(..., 999, anonymous, c/d, MOSQ_ACL_READ)
1454687854: |-- aclcheck(anonymous, c/d, 1) AUTHORIZED=0 by (null)
1454687854: |--  Cached  [ED6629B8919B46C0DEFA47D0C3DF2FD5C3733C0E] for (999,anonymous,1)
1454687854: Sending PUBACK to 888 (Mid: 1)
1454687854: Sending PUBLISH to 888 (d0, q1, r0, m1, 'c/d', ... (12 bytes))
1454687855: Received PUBACK from 888 (Mid: 1)
1454687860: Saving in-memory database to /usr/local/mosquitto-1.4.7/mosquitto.db.

**Comment by 87sanchavan** [comment]
client id 888 has name - sanjay  and client id 999 has name arun

**Comment by 87sanchavan** [comment]
just want to update my observation here so other may get benefit from this.
I think there is issue with Mosquitto ACL module and its not related to auth plug in.
Here is what I have done...

1. Server started 
2.both client connected and subscribed to c/d.
3. server is down , both clients automatically disconnected
4.server restarted 
5.Client 1 connected and published some messages on topic c/d (Client 2 was not yet connected)
6.Client 2 connected .. however It doesn't receive all the messages that client 1 published after server restart and before client 2 gets connected.

**Comment by jpmens** [comment]
Please show us the exact mosquitto_sub and _pub commands you used to test, with all options and with clientIds specified.

**Comment by 87sanchavan** [comment]
I have used Eclipse Paho MQTT Client(UI) for the testing...

Client 1 Options
- Server UI - tcp://54.148.186.65:1883
- client id : 100
- clean session - false
- enable login - (username1 , password1) 

Client 2 Options
- Server UI - tcp://54.148.186.65:1883
- client id : 200
- clean session - false
- enable login - (username2 , password2).

Please let me know if you need any other information.

**Comment by jpmens** [comment]
This is looking like an application issue on your side. Please try to reproduce using known-good utilities (mosquitto_pub/sub), using unique clientids for both. If you can reproduce, I'll look at it.

**Comment by 87sanchavan** [comment]
Sure. I will do and let you know.
