### ISSUE TITLE
mosquitto auth plugin database issue

### ISSUE THREAD

**Issue by mkj-git** [jpmens/mosquitto-auth-plug#121]
I am using mosquitto auth plugin here is my mosquitto.config file

> listener 1883
> 
> #listener 9001 127.0.0.1
> #protocol websockets
> 
> auth_opt_backends postgres
> auth_plugin /etc/mosquitto/auth-plug.so
> auth_opt_dbname mqtt
> auth_opt_host localhost
> auth_opt_port 5432
> auth_opt_user postgres
> auth_opt_pass postgres
> auth_opt_userquery SELECT password FROM account WHERE username = $1 limit 1
> auth_opt_superquery SELECT COALESCE(COUNT(*),0) FROM account WHERE username = $1 AND super = 1
> auth_opt_aclquery SELECT topic FROM acls WHERE (username = $1) AND (rw >= $2)

all postgres setting are default postgres settings. when I run

> sudo /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

command. I am getting this error:

> _1456228482: mosquitto version 1.4.8 (build date 2016-02-22 18:23:09+0530) starting
> 1456228482: Config loaded from /etc/mosquitto/mosquitto.conf.
> 1456228482: |-- *** auth-plug: startup
> 1456228482: |-- ** Configured order: postgres
> 
> 1456228482: |-- }}}} POSTGRES
> 1456228482: |-- HERE: SELECT COALESCE(COUNT(*),0) FROM account WHERE username = $1 AND super = 1
> 1456228482: |-- HERE: SELECT topic FROM acls WHERE (username = $1) AND (rw >= $2)
> |-- We were unable to connect to the database
> |-- *** ABORT._

If I uncomment these two line

> #listener 9001 127.0.0.1
> #protocol websockets

i get this error:

> Error: Websockets support not available.
> Error found at /etc/mosquitto/mosquitto.conf:4.
> Error: Unable to open configuration file.

I was following these tutorial

http://my-classes.com/2015/02/05/acl-mosquitto-mqtt-broker-auth-plugin/
http://www.kirang.in/2015/05/23/setting-up-acl-in-mosquitto-using-postgres/

**Comment by jpmens** [comment]
Both `We were unable to connect to the database` and `Error: Websockets support not available` seem rather self-explanatory to me.

**Comment by mkj-git** [comment]
after changing password of postgres and chaging the default port 1883

> 1456232627: mosquitto version 1.4.8 (build date 2016-02-22 18:23:09+0530) starting
> 1456232627: Config loaded from /etc/mosquitto/mosquitto.conf.
> 1456232627: |-- *** auth-plug: startup
> 1456232627: |-- ** Configured order: postgres
> 
> 1456232627: |-- }}}} POSTGRES
> 1456232627: |-- HERE: SELECT COALESCE(COUNT(*),0) FROM account WHERE username = $1 AND super = 1
> 1456232627: |-- HERE: SELECT topic FROM acls WHERE (username = $1) AND (rw >= $2)
> 1456232627: Opening ipv4 listen socket on port 1884.
> 1456232627: Opening ipv6 listen socket on port 1884.
> 1456232627: Error: Invalid user 'mosquitto'.

from where "mosquitto" user is comming

and also why `Error: Websockets support not available` is showing i am not getting why its showing that. It is supported by mosquiito previously i had tried accesing from browser and it was running.

**Comment by jpmens** [comment]
I think you should read some introductory material (e.g. the manual pages) of mosquitto and mosquitto.conf.

`mosquitto` is the default user it runs under.

Also, if Mosquitto says `Websockets support not available` it isn't. Either you changed something upon rebuilding, have a version that doesn't support it or whatever.

Also: this is not a Mosquitto support site: if you have issues with the authentication plugin, then that's fine.

**Comment by mkj-git** [comment]
ok but why is it showing 

 Invalid user 'mosquitto'.

how to solve it ?

**Comment by jpmens** [comment]
have you read the mosquitto.conf manual?

user username
           When run as root, change to this user and its primary group
           on startup. If
                      mosquitto is unable to change to this user and
                      group, it will exit with an
                                 error. The user specified must have
                                 read/write access to the persistence
                                            database if it is to be
                                            written. If run as a
                                            non-root user, this setting
                                            has no
                                                       effect. Defaults
                                                       to mosquitto.

**Comment by mkj-git** [comment]
I am using javac MosquittoPBKDF2/Example.java to generate password i am getting this output

```
Creating a new hash for "0123456789"...
  -> New hash for "0123456789": PBKDF2$sha256$901$8eUcGfP+5O3oDnMw$FeBmAUj8jSAU9oWkBWDCKQJUDDS8DSlj
Checking if "PBKDF2$sha256$901$8eUcGfP+5O3oDnMw$FeBmAUj8jSAU9oWkBWDCKQJUDDS8DSlj" is a valid hash for "0123456789"...
  -> Password match. It is valid!
Checking if "PBKDF2$sha256$901$8eUcGfP+5O3oDnMw$FeBmAUj8jSAU9oWkBWDCKQJUDDS8DSlj" is a valid hash for "AWrongPassword"...
  -> Password does not match. It is not valid
```

i inserted this in DB 

```
mqtt=# select * from account;
 id | username |                              password                               | super 
----+----------+---------------------------------------------------------------------+-------
  1 | u1       | PBKDF2$sha256$901$8eUcGfP+5O3oDnMw$FeBmAUj8jSAU9oWkBWDCKQJUDDS8DSlj |     0
(1 row)

mqtt=# select * from acls;
 id | username | topic | rw 
----+----------+-------+----
  1 | u1       | hello |  0
```


  no i am doing 

`   mosquitto_sub -t "hello" -u u1 -P 0123456789`

   it shows 

 mosquitto_sub -d -t "hello" -u u1 -P 0123456789
Client mosqsub/26533-manish-Le sending CONNECT
Client mosqsub/26533-manish-Le received CONNACK
Connection Refused: bad user name or password.

**Comment by mkj-git** [comment]
Here i am publishing message
```
mosquitto_pub -d -t 'hello/world' -p 1884 -m 'aaaa' -u u1 -P 0123456789
Client mosqpub/27644-manish-Le sending CONNECT
Client mosqpub/27644-manish-Le received CONNACK
Client mosqpub/27644-manish-Le sending PUBLISH (d0, q0, r0, m1, 'hello/world', ... (4 bytes))
Client mosqpub/27644-manish-Le sending DISCONNECT
```


Here i am subscribing

```
 mosquitto_sub -d -t "hello/world" -p 1884 -u u1 -P 0123456789

Client mosqsub/27624-manish-Le sending CONNECT
Client mosqsub/27624-manish-Le received CONNACK
Client mosqsub/27624-manish-Le sending SUBSCRIBE (Mid: 1, Topic: hello/world, QoS: 0)
Client mosqsub/27624-manish-Le received SUBACK
Subscribed (mid: 1): 0
Client mosqsub/27624-manish-Le sending PINGREQ
Client mosqsub/27624-manish-Le received PINGRESP
```

as you can see no message has received
