### ISSUE TITLE
create password with php

### ISSUE THREAD

**Issue by cyrix333** [jpmens/mosquitto-auth-plug#122]
Hi jpmens,
first thank you very much for your plugin, it works like a charm.

I have a question, is it possible to create a password with a php script ?
The np program you have written works very well but it seems, currently, not possible to
create users without it.
I tried the following php funciton
`
hash_pbkdf2
`
but the created password will not match
(  I added PBKDF2$sha256$901$ before the created key )

**Comment by jpmens** [comment]
Try `contrib/genhash.php`

**Comment by cyrix333** [comment]
Hi jpmens,
thank you very much!
sorry for the question .. sitting hole day in front of the screen .. after a while one cannot see the wood for the trees

.. very fast answer .. thank you so much !
