### ISSUE TITLE
Segmentation fault with mongodb backend

### ISSUE THREAD

**Issue by sreeisalso** [jpmens/mosquitto-auth-plug#123]
Hi, @jpmens 
my config file is 
`autosave_interval 1800`
`persistence true`
`persistence_file mosquitto.db`
`persistence_location /tmp/`
`connection_messages true`
`log_dest stderr`
`log_type all`
`listener 1883`
`listener 1884`
`protocol websockets`
`allow_anonymous false`
`auth_plugin /home/hacking/Git/mosquitto-auth-plug/auth-plug.so`
`auth_opt_backends mongo`
`auth_opt_mongo_host localhost`
`auth_opt_mongo_port 27017`

if the username is wrong it will crash

>1456310095: mosquitto version 1.4.8 (build date 2016-02-23 08:04:17-0500) starting
1456310095: Config loaded from mosquitto-mongo-conf.
1456310095: |-- *** auth-plug: startup
1456310095: |-- ** Configured order: mongo
mongo: [mongodb://localhost:27017]
1456310095: Opening ipv4 listen socket on port 1883.
1456310095: Opening ipv6 listen socket on port 1883.
1456310095: Opening websockets listen socket on port 1884.
1456310100: |-- mosquitto_auth_unpwd_check(7575758665)
1456310100: |-- ** checking backend mongo
1456310100: |-- getuser(7575758665) AUTHENTICATED=0 by none
1456310100: Sending CONNACK to  (0, 5)
Segmentation fault (core dumped)

if username is correct it will not crash

> 1456310273: mosquitto version 1.4.8 (build date 2016-02-23 08:04:17-0500) starting
1456310273: Config loaded from mosquitto-mongo-conf.
1456310273: |-- *** auth-plug: startup
1456310273: |-- ** Configured order: mongo
mongo: [mongodb://localhost:27017]
1456310273: Opening ipv4 listen socket on port 1883.
1456310273: Opening ipv6 listen socket on port 1883.
1456310273: Opening websockets listen socket on port 1884.
1456310289: |-- mosquitto_auth_unpwd_check(9632696010)
1456310289: |-- ** checking backend mongo
1456310289: |-- getuser(9632696010) AUTHENTICATED=1 by mongo
1456310289: New client connected from 45.124.158.82 as user-da4dd9b1ba6566f7 (c1, k60, u'9632696010').
1456310289: Sending CONNACK to user-da4dd9b1ba6566f7 (0, 0)

**Comment by dadivx** [comment]
Hi,

I've just had a look at the code as this issue is easily reproducible and I think I've found where the problem is:
[Line 78 at be-mongo.c](https://github.com/jpmens/mosquitto-auth-plug/blob/master/be-mongo.c#L78)
The segmentation fault happens when it tries to free a pointer that was never allocated, so I just assigned "result" to NULL (as the caller would check if NULL before releasing memory)
`char *result = NULL;` and it seems to work for me.

**Comment by sreeisalso** [comment]
Thanks David,

I think the issue will be not seen with your suggestion.

cheers
Sreekanth.
