### ISSUE TITLE
mosquitto-auth-plugin No backends configured for postgresql

### ISSUE THREAD

**Issue by mahesh21** [jpmens/mosquitto-auth-plug#126]
Earlier I use to get the 
Error: Unable to load auth plugin "/home/ubuntu/mosquitto-auth-plug/auth-plug.so".

Then based on the issue https://github.com/jpmens/mosquitto-auth-plug/issues/33 I made a change in mosquitto config.mk file with WITH_SRV:=no and recompiled both mosquitto and mosquitto-auth-plugin.

The I got this error:
./mosquitto -c ../local.conf 
1457697662: mosquitto version 1.4.8 (build date 2016-03-11 03:59:19-0800) starting
1457697662: Config loaded from ../local.conf.
1457697662: |-- **\* auth-plug: startup
|-- No backends configured.
|-- **\* ABORT.

**config.mk (mosquitto-auth-plugin)**

BACKEND_CDB ?= no
BACKEND_MYSQL ?= no
BACKEND_SQLITE ?= no
BACKEND_REDIS ?= no
BACKEND_POSTGRES ?= yes
BACKEND_LDAP ?= no
BACKEND_HTTP ?= no
BACKEND_MONGO ?= no

MOSQUITTO_SRC = /home/ubuntu/mosquitto-1.4.8

OPENSSLDIR = /usr

**Comment by jpmens** [comment]
It says `No backends configured`. You haven't configured any backends in your `local.conf`.
