### ISSUE TITLE
MongoDB setting via  param.h file in stead of configuration file.

### ISSUE THREAD

**Issue by weizengquan** [jpmens/mosquitto-auth-plug#127]
It seems that the plugin for mongodb needs to hard code the db configuration parameters into the mongoParam.h file instead by add them into the mosquitto.conf file.  this implementation needs to rebuild the source if I change the database backend setting. 

will the mongodb plugin be updated just like the mysql and postgre in the future?
thanks.

**Comment by jpmens** [comment]
Contributed code is welcome.
