### ISSUE TITLE
How get clientId in auth_opt_userquery MySQL

### ISSUE THREAD

**Issue by yurik3zzz** [jpmens/mosquitto-auth-plug#128]
In the query:
auth_opt_userquery SELECT pw FROM devices WHERE deviceId = '%s'

where '%s' - is a username from connection
How get the clientId from connection?

And how combine auth plugin with native auth mehtods, as
mosquitto_passwd -b /etc/mosquitto/passwd superuser 123456

**Comment by jpmens** [comment]
1. You cannot.
2. configure ACL file and auth plugin. If the user isn't found in the former, the latter is tried.
