### ISSUE TITLE
Existing mosquitto broker now dead: mosquitto dead but pid file exists

### ISSUE THREAD

**Issue by AdamMiltonBarker** [jpmens/mosquitto-auth-plug#131]
After adding the plugin to an existing broker it is now dead, please can anyone offer suggestions, it reloads/restarts/starts and then dies. Error message is: mosquitto dead but pid file exists

**Comment by jpmens** [comment]
Start the broker manually (mosquitto -v -c /path/to/config), possibly adding log_stderr to your configuration, and show us what it says when you launch the broker.

**Comment by AdamMiltonBarker** [comment]
Thank you for quick reply

|-- *** auth-plug: startup
|-- No backends configured.
|-- *** ABORT.

However they are:

allow_anonymous false
autosave_interval 1800
connection_messages true
log_dest stderr
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
log_type all
log_type debug
log_timestamp true
#password_file /etc/mosquitto/conf.d/auth.pw
#acl_file /etc/mosquitto/conf.d/perms.acl
#persistence true
#persistence_location /tmp/
persistence_file mosquitto.db
persistent_client_expiration 1m
retained_persistence true
#listener 1883 127.0.0.1
listener 8883
tls_version tlsv1
cafile /etc/mosquitto/certs/ca.pem
certfile /etc/mosquitto/certs/crt.crt
keyfile /etc/mosquitto/certs/key.key
require_certificate false
user mosquitto
protocol mqtt
#use_username_as_clientid true
auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname DBNAME
auth_opt_user DBUNAME
auth_opt_pass DBPASS
auth_opt_userquery SELECT pw FROM DBTABLE WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM DBTABLE  WHERE username = '%s' AND super = 1
auth_opt_aclquery SELECT topic FROM DBTABLE  WHERE (username = '%s') AND (rw >= %d)

**Comment by jpmens** [comment]
I don't see an `auth_opt_backends` in there.

**Comment by AdamMiltonBarker** [comment]
ahh ok let me check the docs again. Thanks again for quick reply

**Comment by AdamMiltonBarker** [comment]
OK thanks it is now loading but the clients are returning 5, to populate the database I copied the existing users / passwords into the database but doesn't seem to be working, any suggestions?

**Comment by jpmens** [comment]
Yes: study the documentation and take it step by step. Don't just copy paste.

**Comment by AdamMiltonBarker** [comment]
Yer not seeing anything that mentions the issue I am having

**Comment by jpmens** [comment]
You said you _copied the existing users / passwords into the database_. How did you do that?

**Comment by AdamMiltonBarker** [comment]
I opened up the auth.pw file and copied the usernames into my database and the passwords that were already generated and then I added the relevant topics for the users in the acl table

**Comment by jpmens** [comment]
Which is why I said "don't just copy/paste"!
Read the plugin documentation. Hint: PBKDF2.

**Comment by AdamMiltonBarker** [comment]
Ah I was of the understanding that the passwords in the auth file were already PBKDF2, my bad if not. So I need to generate the passwords again as PBKDF2 right ?

**Comment by AdamMiltonBarker** [comment]
Cannot find a package np or command

**Comment by AdamMiltonBarker** [comment]
Well that was a bit rude

**Comment by jpmens** [comment]
I don't believe it was. I have asked you several times to look at the documentation, and I got tired of handholding:

```
$ cd directory/to/which/you/pulled/mosquitto-auth-plug/
$ ls -l np.c
$ make np
$ ./np
```

**Comment by AdamMiltonBarker** [comment]
Yer that isn't actually on your documentation, I followed the instructions on the docs and it did not work, I found the answer on another blog.

**Comment by AdamMiltonBarker** [comment]
After following that and adding the passwords in database it is still not functioning rc 5

**Comment by jpmens** [comment]
The documentation says: A trivial utility to generate hashes is included as `np`. `np` is built by the default Makefile.

Also "still not functioning" is something  I cannot help you with unless you show me *exactly* what you did, and how you did it.

**Comment by AdamMiltonBarker** [comment]
The docs say to issue the command np but it is ./np.

I get this error now:

 New connection from IP on port 8883.
1458741708: Socket error on client TechBubble, disconnecting.
1458741708: Client TechBubble disconnected.
1458741708: New client connected from 80.37.43.114 as TechBubble (c0, k10, u'USER').
1458741708: Sending CONNACK to TechBubble (0, 0)
1458741708: Received SUBSCRIBE from TechBubble
1458741708:     TechBubble/Device/JumpWay/1/Sensors (QoS 0)
1458741708: TechBubble 0 TechBubble/Device/JumpWay/1/Sensors
1458741708: Sending SUBACK to TechBubble
1458741709: Socket error on client TechBubble, disconnecting.

**Comment by jpmens** [comment]
I'm finding it difficult to continue with this.... 

It's `./np` if you don't have a path to the directory `np` resides in.

You have not shown me exactly what you did and how you did it, even though I asked you to. You have not shown me how you generated the password, and whether it was the clear text you entered. You have not shown me the content of the database table for this particular user. You have not shown me the ACL entry in the database table for this user. You have not shown me any subscribe or publish command with the exact options and arguments you are using to obtain the above. You have also not shown me what mosquitto logs (with -v) while all this is happening. You've not said anything about the device which is doing this (judging by the topic it's a sensor). You have not explained, if it is a sensor, what that is, what firmware it uses, how you've been testing so far, etc.

Apart from that, I don't see a problem. A client TechBuggle has connected as USER and has successfully subscribed, after which TechBubble has gone away.

**Comment by AdamMiltonBarker** [comment]
Hi sorry have solved the error with np. the issues is  Socket error on client TechBubble, disconnecting. When subscribed I do not see the the messages anymore, with the same script used before I used to see the messages that I was subscribed to these do not show anymore.

I generated the passwords using np and added them to database although connecting something is still not working of which I am unsure.

**Comment by AdamMiltonBarker** [comment]
This should be working as it is an existing system, the only difference is the plugin, passwords generated exactly as per docs, topics added exactly as per docs and exactly how they were before, difference is socket error and not being able to actually see the messages subscribed to anyomre

**Comment by AdamMiltonBarker** [comment]
Additional info I see the subscribe and publish on the pi but I should also see the message:


Subscribed: 3458
Published: 3459
Proximity Detected

No message shown any more

I changed the topics to allow to see all to see if this was the issue but still no:


id	username	topics	rw	
1	USER1	#	1
2	USER2	#	1

id	username	pw	su	
1	USER3	PBKDF2$6$knl45CUbThAMMQAt$N5XsxZvqEl2esvpFQzbAY/dPjLPHjy7XYIc8zfKQEioOsVoWrO0bCTfrZJ9SZEw9sJFhYziqoTUjSdFanwXPJQ==	0
2	USER2	PBKDF2$sha256$901$+0c95eDSpmIW20dU$GjD2wQoxYjTbJ33SEkLWNlC+kXp+/4ba	0
3	USER4	PBKDF2$6$SQCKIiHpyDIJ+HNM$2pBpkcwrErjiyo0kN501wm4GbDStkN2dIaTsVRtYzVigpdklVZYhetPBVa+kMKBPdrTlhKmbyi1wSGGQ+93Fyg==	0
4	USER1	PBKDF2$sha256$901$zsoHwyFKq5ZQydqJ$mdHl2fHqj1up17CmfQnPN7a3+R5LvKDK	0

**Comment by AdamMiltonBarker** [comment]
The user 3 and user 4 are not being tested they are incorrect passwords it is user1 and user2 that are being tested with the new passwords generated

**Comment by AdamMiltonBarker** [comment]
Sorry missed you asked for log,

USER1 is not actual username

 mosquitto -v -c /etc/mosquitto/conf.d/mosquitto.conf
1458745716: mosquitto version 1.4.8 (build date 2016-02-14 16:30:28+0000) starting
1458745716: Config loaded from /etc/mosquitto/conf.d/mosquitto.conf.
1458745716: |-- *** auth-plug: startup
1458745716: |-- ** Configured order: mysql

1458745716: |-- }}}} MYSQL
1458745716: Opening ipv4 listen socket on port 8883.
1458745716: Opening ipv6 listen socket on port 8883.
1458745716: New connection from IP on port 8883.
1458745717: New connection from IP on port 8883.
1458745717: |-- mosquitto_auth_unpwd_check(USER1)
1458745717: |-- ** checking backend mysql
1458745717: |-- getuser(USER1) AUTHENTICATED=1 by mysql
1458745717: Client TechBubble disconnected.
1458745717: New client connected from IP as TechBubble (c0, k10, u'USER1').
1458745717: Sending CONNACK to TechBubble (0, 0)
1458745717: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458745717: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) AUTHORIZED=0 by (null)
1458745717: |--  Cached  [90BAD6CBB737480D6AD7E9AD55C2BE0CD6A26A23] for (TechBubble,USER1,2)
1458745717: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (79 bytes))
1458745717: |-- mosquitto_auth_unpwd_check(USER1)
1458745717: |-- ** checking backend mysql
1458745717: |-- getuser(USER1) AUTHENTICATED=1 by mysql
1458745717: Client TechBubble already connected, closing old connection.
1458745717: Client TechBubble disconnected.
1458745717: New client connected from IP as TechBubble (c0, k10, u'USER1').
1458745717: Sending CONNACK to TechBubble (0, 0)
1458745717: Received SUBSCRIBE from TechBubble
1458745717:     TechBubble/Device/JumpWay/1/Sensors (QoS 0)
1458745717: TechBubble 0 TechBubble/Device/JumpWay/1/Sensors
1458745717: Sending SUBACK to TechBubble
1458745718: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458745718: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12

**Comment by AdamMiltonBarker** [comment]
Is this information to see what is happening with all of the above ?

**Comment by AdamMiltonBarker** [comment]
id	username	topic	rw	
1	USER2	#	1
2	USER1 TechBubble/#	1

 mosquitto -v -c /etc/mosquitto/conf.d/mosquitto.conf
1458746666: mosquitto version 1.4.8 (build date 2016-02-14 16:30:28+0000) starting
1458746666: Config loaded from /etc/mosquitto/conf.d/mosquitto.conf.
1458746666: |-- *** auth-plug: startup
1458746666: |-- ** Configured order: mysql

1458746666: |-- }}}} MYSQL
1458746666: Opening ipv4 listen socket on port 8883.
1458746666: Opening ipv6 listen socket on port 8883.
1458746667: New connection from IP on port 8883.
1458746667: |-- mosquitto_auth_unpwd_check(USER1)
1458746667: |-- ** checking backend mysql
1458746667: |-- getuser(USER1) AUTHENTICATED=1 by mysql
1458746667: Client TechBubble disconnected.
1458746667: New client connected from IP as TechBubble (c0, k10, u'USER1').
1458746667: Sending CONNACK to TechBubble (0, 0)
1458746667: Received SUBSCRIBE from TechBubble
1458746667:     TechBubble/Device/JumpWay/1/Sensors (QoS 0)
1458746667: TechBubble 0 TechBubble/Device/JumpWay/1/Sensors
1458746667: Sending SUBACK to TechBubble
1458746668: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746668: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) AUTHORIZED=0 by (null)
1458746668: |--  Cached  [90BAD6CBB737480D6AD7E9AD55C2BE0CD6A26A23] for (TechBubble,USER1,2)
1458746668: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (79 bytes))
1458746668: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746668: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746668: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (77 bytes))
1458746668: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746668: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746668: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (72 bytes))
1458746668: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746668: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746668: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (87 bytes))
1458746669: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746669: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746669: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (82 bytes))
1458746670: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746670: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746670: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (79 bytes))
1458746670: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746670: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746670: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (77 bytes))
1458746670: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746670: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746670: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (72 bytes))
1458746670: |-- mosquitto_auth_acl_check(..., TechBubble, USER1, TechBubble/Device/JumpWay/1/Sensors, MOSQ_ACL_WRITE)
1458746670: |-- aclcheck(USER1, TechBubble/Device/JumpWay/1/Sensors, 2) CACHEDAUTH: 12
1458746670: Denied PUBLISH from TechBubble (d0, q0, r0, m0, 'TechBubble/Device/JumpWay/1/Sensors', ... (87 bytes))
^C1458746671: mosquitto version 1.4.8 terminating
1458746671: Saving in-memory database to mosquitto.db.

**Comment by AdamMiltonBarker** [comment]
GOT IT :D Needed 2 instead of 1 in database

**Comment by jpmens** [comment]
As per what you've configured, that is right. That's why logging is so important: `Denied PUBLISH` ought to have been a hint. :)

**Comment by AdamMiltonBarker** [comment]
Thanks for helping through mate. This plugin solved a massive headache I was having with my platform I am building, I appreciate your work.
