### ISSUE TITLE
Socket error and client disconnecting.

### ISSUE THREAD

**Issue by AdamMiltonBarker** [jpmens/mosquitto-auth-plug#132]
I guess I should make a new issue as it is not same as the last one, thanks for help getting that solved.

New connection from IP on port 8883.
1458741708: Socket error on client TechBubble, disconnecting.
1458741708: Client TechBubble disconnected.
1458741708: New client connected from IP as TechBubble (c0, k10, u'USER').
1458741708: Sending CONNACK to TechBubble (0, 0)
1458741708: Received SUBSCRIBE from TechBubble
1458741708: TechBubble/Device/JumpWay/1/Sensors (QoS 0)
1458741708: TechBubble 0 TechBubble/Device/JumpWay/1/Sensors
1458741708: Sending SUBACK to TechBubble
1458741709: Socket error on client TechBubble, disconnecting.

**Comment by jpmens** [comment]
Done in #131

**Comment by AdamMiltonBarker** [comment]
Yep sorry was going to close this thanks for help.
