### ISSUE TITLE
Deny Anonymous users?

### ISSUE THREAD

**Issue by svrooij** [jpmens/mosquitto-auth-plug#133]
I was wondering if it was possible with this plugin to deny all anonymous users.

This is because we want all users to create an account through an other website that just creates accounts in the mysql database. Which is our only backend configured.

We tried the following but this didn't work:

```
allow_anonymous = false
```

**Comment by Sufi-Al-Hussaini** [comment]
You should add `allow_anonymous false` (**without the `=`**) to your `mosquitto.conf`. 
IIRC, I was able to get this to work with the auth-plug enabled.
