### ISSUE TITLE
Thread safety with pbkdf2-check.c

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [jpmens/mosquitto-auth-plug#134]
I'm sorry if this is not the right place for this question.

I wanted to use your `pbkdf2-check.c` in another project. 
I found that `valgrind` complained about memory errors relating to these lines:

```
int pbkdf2_check(char *password, char *hash)
{
        static char *sha, *salt, *h_pw;    // <-- Problem is here
```

I have setup OpenSSL locking via callbacks and the code otherwise seems to be thread safe.
Is there any specific reason for making these vars `static`?

**Comment by jpmens** [comment]
Thank you for reporting that. There is, indeed, no reason for the `static` declaration.
