### ISSUE TITLE
Cannot Load auth-plug.so

### ISSUE THREAD

**Issue by TNChalise** [jpmens/mosquitto-auth-plug#135]
Cannot load auth-plugin.so.

```php
mosquitto -c /etc/mosquitto/mosquitto.conf -v
mosquitto version 1.4.8 (build date Sun, 14 Feb 2016 15:48:26 +0000) starting
Config loaded from /etc/mosquitto/mosquitto.conf.
Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so ".
 Load error: /etc/mosquitto/auth-plug.so : cannot open shared object file: No such file or directory
```
```linux
# ls /etc/mosquitto/
auth-plug.so  ca_certificates  certs  conf.d  mosquitto.conf  mosquitto.conf~
```
Gone through: #33

**Comment by jpmens** [comment]
Did you actually _read_ the diagnostic message?

**Comment by TNChalise** [comment]
Yes. 
I have auth-plug.so in /etc/mosquitto/ directory, which is loaded in the conf file. Do I need to do other stuffs ? I believe the issue is with 

> cannot open shared object file:

**Comment by jpmens** [comment]
Now look at this, very carefully:

```
Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so ".
```

**Comment by TNChalise** [comment]
Found the extra space there.
Follow-inly stuck into

> Load error: /etc/mosquitto/auth-plug.so: undefined symbol: ares_library_init

**Comment by TNChalise** [comment]
Just to confirm: I have installed mosquitto by adding willy source lists. And, for auth I have manually downloaded mosquitto library and given the path. 

> Is that the reason behind this: after I changed  `WITH_SRV=no` still yeilds the same error message ?

**Comment by jpmens** [comment]
I don't know what willy source lists are.

If you change config.mk you have to rebuild the library and the plugin

**Comment by TNChalise** [comment]
I have installed all libraries fresh, and still stuck with `: undefined symbol: ares_library_init`

**Comment by jpmens** [comment]
Something, probably auth-plug, has been built with SRV enabled, hence that message.

**Comment by TNChalise** [comment]
I tried by installing this dependency, from one of your issues.
`yum install c-ares-devel -y`
But, still no hope.

**Comment by jpmens** [comment]
Show me the output of 

```
ldd /path/to/auth-plug.so
```

**Comment by TNChalise** [comment]
```linux
	linux-vdso.so.1 =>  (0x00007ffcf86a1000)
	libmysqlclient.so.18 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007f5d8b796000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f5d8b352000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5d8af87000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5d8ad6d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5d8ab69000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5d8a94a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5d8a5c8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5d8a2c0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5d8a0a8000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d7a8606000)
```

**Comment by jpmens** [comment]
I don't see any mention of libares in there; are you testing with the correct `.so`? 
Will Mosquitto start if you remove the configuration for the auth plugin?

**Comment by TNChalise** [comment]
```
$ mosquitto
mosquitto version 1.4.8 (build date Sun, 14 Feb 2016 15:48:26 +0000) starting
Using default config.
Opening ipv4 listen socket on port 1883.
 Opening ipv6 listen socket on port 1883.

```

**Comment by jpmens** [comment]
and you have rebuilt the authentication plugin from source since? This is beginning to sound inpossible ...

**Comment by TNChalise** [comment]
Are you suggesting me to reinstall all the dependencies and retry the cycle ?

**Comment by jpmens** [comment]
Please recompile (make clean; make) the auth plugin

**Comment by TNChalise** [comment]
I downloaded and reinstalled, and now WITH_SRV:=no, new configuration are loaded.

**Comment by jpmens** [comment]
So it works. Please close this issue then.

**Comment by TNChalise** [comment]
Reference:
#33 , #103, #100

**Comment by jpmens** [comment]
And not even a word of thanks for the hand-holding that took place here. Sometimes, it's a real pleasure to do Open Source not.

**Comment by X-Cli** [comment]
Thank you :) (even though I don't know what this thread is about :o)))

**Comment by fkahhaleh** [comment]
Thank you for the great plugin/library and the support you put behind it 
:)

**Comment by TNChalise** [comment]
Thank you.

**Comment by chipengliu** [comment]
```
1519388743: mosquitto version 1.4.14 (build date 2018-02-23 20:22:02+0800) starting
1519388743: Config loaded from mosquitto.conf.
1519388743: Error: Unable to load auth plugin "./auth-plug.so".
1519388743: Load error: ./auth-plug.so: undefined symbol: ares_library_init
```

execute ` export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{path}/mosquitto/lib`, may solve this problem, even though I don't know the reason.
