### ISSUE TITLE
compile issue 

### ISSUE THREAD

**Issue by yh22** [jpmens/mosquitto-auth-plug#140]
Selected backends:          MySQL
Using mosquitto source dir: /mosquitto
OpenSSL install dir:        /usr/lib/ssl

If you changed the backend selection, you might need to 'make clean' first

CFLAGS:  -I/mosquitto/src/ -I/mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing    -g -DNDEBUG -I/src -DDEBUG=1 -I/usr/lib/ssl/
LDFLAGS:  -L/mosquitto/lib/
LDADD:    -L/usr/lib/arm-linux-gnueabihf -lmysqlclient -lpthread -lz -lm -ldl -L/usr/lib/ssl/lib -lcrypto -lmosquitto

cc -I/mosquitto/src/ -I/mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/ssl/   -c -o auth-plug.o auth-plug.c
auth-plug.c:33:25: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
                         ^
compilation terminated.
<builtin>: recipe for target 'auth-plug.o' failed
make: *** [auth-plug.o] Error 1

**Comment by yh22** [comment]
Hello, i really need help please..

**Comment by sreeisalso** [comment]
Install openssl libraries 

Regards
Sreekanth

**Comment by yh22** [comment]
thanks bro ! problem solved.
