### ISSUE TITLE
How does ACL work on MySQL

### ISSUE THREAD

**Issue by hcarsten** [jpmens/mosquitto-auth-plug#141]
I am working on a project using the mqtt_acl plugin. Anyway when it comes to ACL I am lost.

So I have basically 2 users, one is an admin-account which is used to publish. The second is a normal account which should have restricted access and should be able to only subscribe to a single topic.

So my setup is currently :

user "admin" and user "box1". The admin user is publishing to "ds/0001/cmd". The problem is that the user "box1" does not got any messages, the same box running with user "admin" works.

so this, does NOT work :
`mosquitto_sub -h mqtt-server.com -u box1 -P pwd -v -t "ds/00001/cmd"`

this one works as expected :
`mosquitto_sub -h mqtt-server.com -u admin -P pwd -v -t "ds/00001/cmd"`

this is my mqtt_acls table

```
id  username    topic       rw
1   box1        ds/00001/#  2
```

So no idea what is going wrong here, or how the topic has to be constructed in the acls-table ?

best

Carsten

**Comment by jpmens** [comment]
I believe this is documented. If you feel it is inadequatly documented, I will accept improvements to said docs.
