### ISSUE TITLE
be-mongo.c aclcheck() failed

### ISSUE THREAD

**Issue by kevin830222** [jpmens/mosquitto-auth-plug#146]
i used mongo as my backend and found that only superusers can be authorized.

i thought the problem is here

```
// line268
if (mongoc_cursor_error (cursor, &error)) {
	fprintf (stderr, "Cursor Failure: %s\n", error.message);
	return 0;
}
```

i changed it into the following and can work well
```
if (mongoc_cursor_error (cursor, &error)) {
	fprintf (stderr, "Cursor Failure: %s\n", error.message);
	return match;
}
```

is it a correct bug fix?

**Comment by kevin830222** [comment]
btw, it will get memory leak if acl check failed for many times.
i thought it's because line:274 will not be triggered when auth failed
```
// line: 274
	bson_destroy(&query);
	mongoc_cursor_destroy (cursor);
	mongoc_collection_destroy(collection);
```

**Comment by jpmens** [comment]
Closed via https://github.com/jpmens/mosquitto-auth-plug/pull/163
