### ISSUE TITLE
Can't buiding the plugin(auth-plug.so)

### ISSUE THREAD

**Issue by fluke3015** [jpmens/mosquitto-auth-plug#149]
# What i found before command "make"

Selected backends:          MySQL
Using mosquitto source dir: /usr/sbin/
OpenSSL install dir:        /usr/bin/

If you changed the backend selection, you might need to 'make clean' first

CFLAGS:  -I/usr/sbin//src/ -I/usr/sbin//lib/ -fPIC -Wall -Werror  -DBE_MYSQL  -I/usr/include/mysql -g  -m64 -fPIC  -g -fabi-version=2 -fno-omit-frame-pointer -fno-strict-aliasing -I/src -DDEBUG=1 -I/usr/bin//include
LDFLAGS:  -L/usr/sbin//lib/
LDADD:    -L/usr/lib64/mysql -lmysqlclient -lpthread -lm -ldl -L/usr/bin//lib -lcrypto -lmosquitto

cc -I/usr/sbin//src/ -I/usr/sbin//lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/bin//include   -c -o auth-plug.o auth-plug.c
auth-plug.c:34:23: fatal error: mosquitto.h: No such file or directory
 #include <mosquitto.h>
                       ^
compilation terminated.
make: **\* [auth-plug.o] Error 1
# in config.mk

BACKEND_CDB ?= no
BACKEND_MYSQL ?= yes
BACKEND_SQLITE ?= no
BACKEND_REDIS ?= no
BACKEND_POSTGRES ?= no
BACKEND_LDAP ?= no
BACKEND_HTTP ?= no
BACKEND_JWT ?= no
BACKEND_MONGO ?= no
# Specify the path to the Mosquitto sources here

MOSQUITTO_SRC = /usr/sbin/
# Specify the path the OpenSSL here

OPENSSLDIR = /usr/bin/
............................................................................
Help me please.......

**Comment by imZack** [comment]
`MOSQUITTO_SRC = /usr/sbin/`

I think your mosquitto source code location is wrong.

**Comment by btry** [comment]
+1

If you installed mosquitto from your distro, you may leave  MOSQUITTO_SRC empty and it should compile.

**Comment by fluke3015** [comment]
Thank you so much for response. I'll try reinstall another source code.
