### ISSUE TITLE
mongodb backend functionality: ACL checks

### ISSUE THREAD

**Issue by cordovapolymer** [jpmens/mosquitto-auth-plug#157]
Hi,

> currently no readwrite checks on ACL, all topics will be readwrite, do not add a flag to the array of topics in db.

Please add read, write and readwrite checks to the mongodb backend.

> The mysql back-end supports expansion of %c and %u as clientid and username respectively. 

Please add expansion of %c and %u to the mongodb backend.

**Comment by rogueturnip** [comment]
This would be a very beneficial addition.

**Comment by jpmens** [comment]
Closing: feel free to submit PR
