### ISSUE TITLE
mosqutto pub/sub based auth

### ISSUE THREAD

**Issue by cordovapolymer** [jpmens/mosquitto-auth-plug#158]
It would be great to have a mosquitto based authentication. So certain authorized client would be able to send a message with users, password hashes and acl, and mosquitto would use these acls on session based manner.
A configuration file for this would look like:

```
auth_opt_hosts localhost, otherhost
auth_opt_authtopic mosqutto_acl 
auth_opt_user superuser
auth_opt_pass passwordhash
```

**Comment by jpmens** [comment]
You are going to have to explain this more in detail/ depth, as I don't see
what this should be.

**Comment by cordovapolymer** [comment]
An idea is to have a mosquitto based acl configuration, so a configured superuser could publish messages with ACLs which would be received by the auth plug and immediatelly applied. 
I have provided a configuration file in my first post, here's a a proposal for messages:

topic: `mosqutto_acl `

message, in json ```[{"user":"username", "topic": "sensor/%u/data", "access": "read"}, {"user":"username2", "topic": "device/%c/#", "access": "write"}, {"user":"username3", "topic": "device/#", "access": "readwrite"}, {"user":"groupname_*", "topic": "device/+/+", "access": "read"}]```

The json message has to be an array of objects with three key/value pairs, user, topic and access rights. User could be specified with  fnmatch(3) (a.k.a glob(3))  pattern. A topic could be specified with  %c and %u to be expanded as as clientid and username respectively.

This would allow to manage a pure mqtt base dynamic acl configuration. Of course It wouldn't be able to handle a heavy setup of hundreds of millions of acls, but will easily go up to a mid class setups.

**Comment by jpmens** [comment]
We will not do this.

**Comment by cordovapolymer** [comment]
>We will not do this.

Can you give a reason?
