### ISSUE TITLE
Validating Client ID on authentication

### ISSUE THREAD

**Issue by je-al** [jpmens/mosquitto-auth-plug#159]
Hi, you mentioned in #128 that there's no way to obtain the client_id on the auth_opt_userquery.

I was wondering if this is because the current plugin's / MySQL backend's implementation does not support it or because whatever "extension hook" for authentication mosquitto provides does not supply it at this stage.

As you know, unless we can check for this, there's the possibility for any valid (malicious?) user to close another's session.

**Comment by jpmens** [comment]
Mosquitto's mosquitto_auth_unpwd_check() doesn't provide the clientID at the 
time the plugin authenticates a user; the clientID is, however, provided once 
the authentication succeeds and it's time to check the ACL.

An MQTT broker will "kick" out the oldest clientID when it detects a duplicate.  
I have though never tested wether catching a duplicate authentication request 
(in unpwd_check()) and forbidding the second client at that point would 
eliminate kicking out the first client. Would be worth testing, probably...

**Comment by je-al** [comment]
Thing is, we don't have any way of knowing when client has disconnected, do we?

**Comment by cordovapolymer** [comment]
>Thing is, we don't have any way of knowing when client has disconnected, do we?

check out mqtt last-will.

**Comment by je-al** [comment]
> check out mqtt last-will.
right, however, there's a threshold for malicious users to get in without setting a last will and blocking user auth for whatever TTL we setup for the block thought. We could parse the logs for the client disconnects thought, it just feels "dirty". Furthermore, there's nothing stopping a malicious user from "getting in" before the valid user and blocking them.
