### ISSUE TITLE
Mosquitto dies on wrong password.

### ISSUE THREAD

**Issue by satanasov** [jpmens/mosquitto-auth-plug#16]
When usin the MySQL backend, on wrong password - mosquitto dies

Mosquitto version 1.2.2

It sigfaults. 

mosquitto[4984]: segfault at 7ff8705257d8 ip 00007ff8705257d8 sp 00007fff90610d48 error 15 in libc-2.17.so[7ff870525000+2000

**Comment by nikhilve99** [comment]
hi i am getting same error 
1484724748: New connection from 10.40.145.5 on port 443.
1484724748: |-- mosquitto_auth_unpwd_check(nikhilv)
1484724748: |-- ** checking backend mysql
1484724748: |-- getuser(nikhilv) AUTHENTICATED=0 by none
1484724748: Sending CONNACK to 10.40.145.5 (0, 5)
1484724748: Socket error on client <unknown>, disconnecting.

kindly help
regards
nikhil
