### ISSUE TITLE
mqtt-auth-plug can't work on sqlite

### ISSUE THREAD

**Issue by Royalor** [jpmens/mosquitto-auth-plug#161]
This is my mqtt-auth-plug's config.mk :
###### 
#Select your backends from this list

BACKEND_CDB ?= no
BACKEND_MYSQL ?= no
BACKEND_SQLITE ?= yes
BACKEND_REDIS ?= no
BACKEND_POSTGRES ?= no
BACKEND_LDAP ?= no
BACKEND_HTTP ?= no
BACKEND_JWT ?= no
BACKEND_MONGO ?= no
#Specify the path to the Mosquitto sources here

MOSQUITTO_SRC = /home/mti/mqtt_source/mosquitto-1.4.10/
#Specify the path the OpenSSL here

OPENSSLDIR = /usr
###### 

It's can be make successfully.

This is my mosquitto-1.4.10's config.mk:
###### 

WITH_TLS:=yes
WITH_TLS_PSK:=yes
WITH_THREADING:=yes
WITH_BRIDGE:=yes
WITH_PERSISTENCE:=yes
WITH_MEMORY_TRACKING:=yes
#WITH_DB_UPGRADE:=yes

WITH_SYS_TREE:=yes
WITH_SRV:=no
WITH_UUID:=yes
WITH_WEBSOCKETS:=no
WITH_EC:=yes
WITH_DOCS:=yes
WITH_SOCKS:=yes
....
###### 

It's can be make install successfully.

My mosquitto.conf : 
###### 

auth_opt_backends sqlite
auth_plugin /etc/mosquitto/auth-plug.so
#for sqlite3

auth_opt_dbpath /home/mti/mqtt_source/db.sqlite
auth_opt_sqliteuserquery SELECT password FROM users WHERE name = '%s'
###### 

For sqlite3 command line, i can get 'name' and 'password' that use command : 
SELECT password FROM users WHERE name = 'Roy', 
and return
PBKDF2$sha256$901$ejd6O3xmresjUsnf$sevFjEk8rESzybDNZl1yT6FHDBrB6ivn
which is created by np.
ng
There is problem, when i run mosquitto -c /etc/mosquitto.conf, seems very normal,
#log:

1473846702: mosquitto version 1.4.10 (build date 2016-09-13 11:45:06+0800) starting
1473846702: Config loaded from mosquitto.conf.
1473846702: |-- **\* auth-plug: startup
1473846702: |-- *\* Configured order: sqlite

1473846702: Opening ipv4 listen socket on port 1883.
1473846702: Opening ipv6 listen socket on port 1883.
1473846707: New connection from 127.0.0.1 on port 1883.
1473846707: |-- mosquitto_auth_unpwd_check(Roy)
1473846707: |-- *\* checking backend sqlite
Can't bind
1473846707: |-- getuser(Roy) AUTHENTICATED=0 by none
1473846707: Socket error on client <unknown>, disconnecting.
1473846708: New connection from 127.0.0.1 on port 1883.
1473846708: |-- mosquitto_auth_unpwd_check(Roy)
1473846708: |-- *\* checking backend sqlite
Can't bind

---

What i missing?

BTW. my password is '1111', and mosquitto command is  
mosquitto_sub -d -t 111  -u Roy -P 1111.

**Comment by vivek1729** [comment]
I am getting the same error. Could you solve it @Royalor?

**Comment by vivek1729** [comment]
@Royalor , I was able to solve this issue by using the specific parameter expected by SQLite. It doesn't work exactly like a MySQL query. So in that SELECT statement since we want to replace a literal with a parameter, we do it like: `SELECT password FROM users WHERE name = ?1`
[Relevant documentation](https://www.sqlite.org/lang_expr.html) : Check the parameters section.

Hope it helps.

**Comment by Royalor** [comment]
@vivek1729 , It's work!!!
Thank you for your help!!
