### ISSUE TITLE
Wildcard topic # subscribe acl not working.

### ISSUE THREAD

**Issue by akashtalole** [jpmens/mosquitto-auth-plug#166]
When i subscribe topic # then it allows to subscribe bot in ACL there is # subscribe not allowed. Im using mosquitto 1.4.10.

**Comment by simonmorley** [comment]
Are you saying you can subscribe to the '#' topic, even when you do not have this in the DB for a user?

**Comment by akashtalole** [comment]
@simonmorley yes

**Comment by simonmorley** [comment]
I can replicate.

**Comment by bitfreak25** [comment]
I could not reproduce it with the back-end mongoDB. What back-end are you using?

**Comment by akashtalole** [comment]
I am using MySQL.

**Comment by simonmorley** [comment]
The problem isn't seemingly related to the backend you're using. It would seem there is no check during a subscribe to see if the user has permissions for a topic.

**Comment by simonmorley** [comment]
@bitfreak25 What version of mosquito are you using?

**Comment by bitfreak25** [comment]
I'm also using mosquitto 1.4.10.

@akashtalole 
Do you login **without** username and password and then subscribe to # ? This seems to be working with my implementation, but with it I can't get the topics of other users.

**Comment by akashtalole** [comment]
@bitfreak25 Connection refused Error occurs when subscribe to # without username and password and I think when i subscribe to # topic to particular user then it only shows his topics messages only not others.

**Comment by simonmorley** [comment]
Actually I can still replicate and subscribe to all topics using the #.

**Comment by bartremans** [comment]
I'm having the same issue, can also subscribe to wildcards (using acl and username/pw authentication).
Don't know how to interpret the statement 'Wildcards are not supported'?
Is the plugin not invoked for wildcards? Or is it and should it revoke all wildcards?
