### ISSUE TITLE
ACL issue

### ISSUE THREAD

**Issue by akashtalole** [jpmens/mosquitto-auth-plug#169]
In MySQL backend ACL database Entries
user        topic   rw
akash   x    1
ps1             x    2

Then

> mosquitto_pub -t "x" -m test -u ps1 -P password1
> 
> mosquitto_sub -t "x" -u akash -P password
> test

I am able to see user ps1's topic "x" messages  in user akash.

**Comment by jpmens** [comment]
I'll need to see your configuration and table rows of all plugin-related tables please, so that I can try to reproduce.
