### ISSUE TITLE
How to have a static password file authentication for admin and HTTP authentication for others

### ISSUE THREAD

**Issue by vivek1729** [jpmens/mosquitto-auth-plug#178]
I am using this plugin to authenticate clients using a browser through web sockets. The authentication API is defined in my app server which also needs to have a client that will have admin privileges. But I obviously can not authenticate the admin with HTTP API's since the API's live on the same server and I bind the client during server boot. Can I have a static authentication mechanism for admin and fallback to HTTP for other users. Referencing issue https://github.com/eclipse/mosquitto/issues/322 reported on Mosquitto Github Repo.

**Comment by hardillb** [comment]
The auth plugin supports multiple using mechanisms, the only thing it won't do is specifically what you are asking about, namely allow you to mix using the plugin with using the built in flat file. You could achieve something very similar by using the http and say the sqlitedb support which would be a local file.

**Comment by vivek1729** [comment]
Got it! I guess using a simple sqlite database won't complicate things. However, I see that the documentation for sqlite integration is not that detailed. Should I submit a pull request to update the documentation with a working example?

**Comment by hardillb** [comment]
Sounds like a good idea

**Comment by jpmens** [comment]
Pull requests are *always* welcome! :-)
