### ISSUE TITLE
ACL Check with JWT backend

### ISSUE THREAD

**Issue by Tryforce** [jpmens/mosquitto-auth-plug#180]
I have a RESTful API running express.js that is catching the different routes for my user/superuser/acl checks.
Mosquitto doesn't seem to be running the aclcheck to the uri that I have configured here:

```
auth_plugin /home/kyle/Documents/mqtt2/mosquitto-auth-plug-master/auth-plug.so
auth_opt_backends jwt
auth_opt_http_ip localhost
auth_opt_http_port 8085
auth_opt_http_getuser_uri /auth
auth_opt_http_superuser_uri /superuser
auth_opt_http_aclcheck_uri /acl
```

The auth check works fine.  I am passing a token as my username when I connect and decoding it, checking for a username, and responding with a 200 status code, obviously just for testing purposes, it's extremely simple:
(in my /auth path)

```
auth: function(req, res) {
        var token = req.headers.authorization.substr(req.headers.authorization.indexOf(' ') + 1);
        var decoded = jwtDecode(token);
        if (decoded.username != null) {
            res.json(200);
        }
    }
```

This seems to work fine:

```
1481214677: Config loaded from /home/kyle/Documents/mqtt2/mosquitto-1.4.10/mosquitto.conf.
1481214677: |-- *** auth-plug: startup
1481214677: |-- ** Configured order: jwt

1481214677: |-- with_tls=false
1481214677: |-- getuser_uri=/auth
1481214677: |-- superuser_uri=/superuser
1481214677: |-- aclcheck_uri=/acl
1481214677: |-- getuser_params=(null)
1481214677: |-- superuser_params=(null)
1481214677: |-- aclcheck_paramsi=(null)
1481214677: Opening websockets listen socket on port 1883.
1481214679: |-- mosquitto_auth_unpwd_check(eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0ODE4MTY5NjE5NzIsInVzZXJuYW1lIjoia3lsZWJha2VyMTdAZ21haWwuY29tIiwidXNlcl9pZCI6NjYsImN1c3RvbWVyX2lkIjozNn0.hp8ie3atkHLB84XBzqN6HblHEqmvzQR0w-ER3dkl5Wo)
1481214679: |-- ** checking backend jwt
1481214679: |-- url=http://localhost:8085/auth
1481214679: |-- data=topic=&acc=-1&clientid=
1481214679: |-- getuser(eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0ODE4MTY5NjE5NzIsInVzZXJuYW1lIjoia3lsZWJha2VyMTdAZ21haWwuY29tIiwidXNlcl9pZCI6NjYsImN1c3RvbWVyX2lkIjozNn0.hp8ie3atkHLB84XBzqN6HblHEqmvzQR0w-ER3dkl5Wo) AUTHENTICATED=1 by jwt
1481214679: New client connected from 10.10.10.18 as mqttjs_e3767eae (c1, k60, u'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0ODE4MTY5NjE5NzIsInVzZXJuYW1lIjoia3lsZWJha2VyMTdAZ21haWwuY29tIiwidXNlcl9pZCI6NjYsImN1c3RvbWVyX2lkIjozNn0.hp8ie3atkHLB84XBzqN6HblHEqmvzQR0w-ER3dkl5Wo').

```

However, when we try to subscribe, no where does the aclcheck (/acl) get called:

```
1481214679: Sending CONNACK to mqttjs_e3767eae (0, 0)
1481214680: Received SUBSCRIBE from mqttjs_e3767eae
1481214680: 	/mrs/cgw/+/gps (QoS 0)
1481214680: mqttjs_e3767eae 0 /mrs/cgw/+/gps
1481214680: Sending SUBACK to mqttjs_e3767eae
1481214680: Socket error on client mqttjs_e3767eae, disconnecting.

```

It gets the subscription request and (tries to) send back immediately, without running through my API to do the acl check. Am I missing something?

**Comment by PierreF** [comment]
From a quick look to Mosquitto code, Mosquitto do ACL check when sending/receiving message, not on subscribe.
You could always subscribe to any topic, but if ACL deny it, you won't receive anything.

ACL will be checked when you sent a message, and 2 times:

* One ACL check that the sender is allowed to sent on the topic
* One ACL check that the subscriber is allowed to read from the topic

Note that mosquitto-auth-plug does some caching, so this won't happen for each message.

**Comment by Tryforce** [comment]
Thank you for clearing that up, I thought the ACL check was running on the subscribe.

I am able to get into my acl path on the API now, but I can't seem to find the topic anywhere in the request. I should be able to see the topic they are requesting to publish/read messages from in my API, no?

**Comment by PierreF** [comment]
You look for the topic in request POST data right ?
I don't thing they are present in GET data, but they are in POST data.

Documentation is rather unclear on this point and [example](https://github.com/jpmens/mosquitto-auth-plug/blob/master/examples/http-auth-be.py) is either misleading (using request.forms.get) or wrong :)

**Comment by Tryforce** [comment]
Yes, it's a post. In my index.js that catches the route: 

`router.post('/acl', auth.acl);`

And then in auth.js:

```
acl: function(req, res) {
      console.log(req.body);
      res.status(200).json();
    }
```

This method gets called correctly, but in my console log:

```
app listening on port 8085
{}
```

And in my mosquitto server, here is where the acl is getting called (the topic I need is in the data):

```
1481223235: |-- url=http://localhost:8085/acl
1481223235: |-- data=topic=%2Fmrs%2Fcgw%2FDevice%20ID%20One%2Fgps&acc=1&clientid=mqttjs_02908e96
```

**Comment by PierreF** [comment]
Are you sure you framework/library don't assume that req.body is a JSON ? Post is not a JSON but a multipart/form-data.

**Comment by Tryforce** [comment]
@PierreF yep, that was it lol. Had to allow my body parser to include URL encoded data. Everything seems to be working now. Thank you for the help!

**Comment by andriwarda** [comment]
@Tryforce can you share me step by step to make example for jwt authentication ?

**Comment by andriwarda** [comment]
@Tryforce can you share me step by step to make example for jwt authentication ?

**Comment by andriwarda** [comment]
@Tryforce can you share me step by step to make example for jwt authentication ?
