### ISSUE TITLE
Error with # in topic names.

### ISSUE THREAD

**Issue by AdamMiltonBarker** [jpmens/mosquitto-auth-plug#186]
Hi mate, as far as I am aware a + in a topic would be used in between topic parts ie:

test/+/test2

and a # is to be used at the end to match anything trailing after that, when I have a topic permission like so:

test/test/#

it should be able to send and receive from:

test/test/1/2
test/test/1/2/3 

But it cannot, although the following would work:

test/test/1

I literally have to put multiple permission in like:

test/test/1/# 
test/test/2/# 

Is there anything I have missed in the docs that say how to accomplish this ?

**Comment by zanninialex** [comment]
I've the same issue ... :-(
Someone can confirm that's a bug ??

**Comment by rh389** [comment]
Which backend are you using?

**Comment by zanninialex** [comment]
I use redis as backend...

**Comment by rh389** [comment]
I don't think wildcards are supported at all in redis - https://github.com/jpmens/mosquitto-auth-plug/issues/198

**Comment by AdamMiltonBarker** [comment]
@rh389 I am using MySQL, sorry forgot to mention that.

**Comment by jpmens** [comment]
Wildcards work fine with the MySQL backend.

**Comment by AdamMiltonBarker** [comment]
They arent in my case as explained above.

**Comment by rh389** [comment]
They should work (the plugin just defers to mosquitto for topic matching) - and @AdamMiltonBarker your understanding looks right. Maybe there's something amiss with your config or data, a sample and/or logs would help.

**Comment by jpmens** [comment]
Closing because of no response.
