### ISSUE TITLE
Denied after chang topic permissions

### ISSUE THREAD

**Issue by AdamMiltonBarker** [jpmens/mosquitto-auth-plug#187]
The topic structure I use is similar to below:

LOCATIONID/ZONEID/DEVICEID

Through our interface you can change the location and zone of a device which updates the mysql database with the new topic, IE:

1/2/3/# could be changed to 1/3/3/#

Once this happens the new topic path is sent to the device, the relevant authentication database tables are updated and the device will disconnect from the broker and reconnect to the new topic successfully. 

In logs you can see that the device is now connected/publishing and receiving correctly on the new topic. After a while the device stops receiving messages, although logs still show that it is publishing messages on that topic fine and the data can be viewed in our GUI, the device will not receive further commands, for example if I send a message as above to change the location again it does not show in logs that the message has been sent to the device and the device does not receive it, although you can see it being sent to another global client application, after a while as the database has been updated but the device did not receive the message, all publishes from the device become denied. 

Once I update the topic back to the original one, it takes about ten minutes before the DENIED messages start to become RECEIVED again.

**Comment by jpmens** [comment]
That is correct: the plugin caches data. You can disable the cache by configuring `cacheseconds`

**Comment by AdamMiltonBarker** [comment]
OK thanks for the reply, and that will not affect any other features ?

**Comment by jpmens** [comment]
Caching will be disabled.

**Comment by AdamMiltonBarker** [comment]
I guessed that :) Was just checking it would negatively affect any other part of the plugin. Thanks for the reply.
