### ISSUE TITLE
how to specify ACL for anonymous?

### ISSUE THREAD

**Issue by joysfera** [jpmens/mosquitto-auth-plug#189]
I can't get the anonymous user working properly. With 'mysql' as the only backend it's also the fallback backend for anonymous users, right?

Now the "auth_opt_anonusername" basically gives the anonymous user a name. Fine.

There's no password so the auth_opt_userquery is not used for anonymous, is it?

And why doesn't the auth_opt_aclquery work? If I specify something like
```
auth_opt_anonusername anonymouse
auth_opt_aclquery SELECT '%c/#' FROM DUAL WHERE '%s' = 'anonymouse'
```
then the plugin just crashes with segmentation fault. How am I supposed to specify the ACL for an anonymous user (using the %c), please?

**Comment by brandond** [comment]
I think you need to escape `%c` as `%%c`, as the string formatter is probably tripping up on it as unsupported. Note that the client ID expansion into the topic occurs AFTER the topic is returned from the database - the query string itself only supports `%s` and `%d` for username and access level.

**Comment by joysfera** [comment]
Which string formatter? In the plugin, or in MySQL? How did you come up with the idea of escaping the %c?
I'm OK with client ID expansion occuring after the topic is returned from the database. As you can read in my query I just want to assign the topic by the client ID.

**Comment by brandond** [comment]
@joysfera The plugin replaces `%s` and `%d` in the query before it is executed on the server. If `%c` occurs in the response from the server, it is replaced with the client ID before the ACL is evaluated. I was anticipating that these were standard sprintf style strings which would need to be escaped, but it appears that's not the case, it's just character scanning in [backends.c](https://github.com/jpmens/mosquitto-auth-plug/blob/master/backends.c) with no escaping possible. My apologies.

That said, you might see if you can get a stack trace from the segfault to see where it's failing?

**Comment by jpmens** [comment]
Closing because of no response.
