### ISSUE TITLE
Include Client ID in getuser call

### ISSUE THREAD

**Issue by brandond** [jpmens/mosquitto-auth-plug#192]
I would like to be able to control the ClientIds used by a client. Currently, the ClientID (if any) is known at the time that the getuser (username + password) check is done since it is also part of the CONNECT packet, but it is not passed to the back-end.

Disallowing by ClientId is allowed by the spec:
> If the Server rejects the ClientId it MUST respond to the CONNECT Packet with a CONNACK return code 0x02 (Identifier rejected) and then close the Network Connection [MQTT-3.1.3-9].

**Comment by jpmens** [comment]
Thanks for the suggestion. I have now implemented this via #266 for the `mysql` backend; others may follow.
