### ISSUE TITLE
How to compile auth plugin on Alpine?

### ISSUE THREAD

**Issue by vivek1729** [jpmens/mosquitto-auth-plug#194]
I love this plugin and have been able to get it to work by building mosquitto from source and referencing the shared object file as clearly specified in the README. However, I want to install the broker on a lightweight distro like Alpine. They already have a package for mosquitto and I was wondering if it is still possible to build the auth plugin if mosquitto broker is installed as a package from the repository instead of being built from source. I get an error during make that 

`auth-plug.c:34:23: fatal error: mosquitto.h: No such file or directory
 #include <mosquitto.h>`

This makes sense since the above header files don't exist. Is there a way to still compile this plugin without building mosquitto from source?

**Comment by jpmens** [comment]
You need the header files to build, but you can build on one machine and
then copy the shared object (.so) over to your production machine.

**Comment by vivek1729** [comment]
Thanks @jpmens for your prompt reply. It points me in the right direction. Copying the shared object built once, significantly lowers the memory usage. :)
