### ISSUE TITLE
issue with undefined symbol: EVP_MD_CTX_reset 

### ISSUE THREAD

**Issue by shahabmusic** [jpmens/mosquitto-auth-plug#195]
Hi I am having this issue for last 10days and could not solve it. I am hoping that you could help me please.

mosquitto ver:1.4.10 (tried previous version and got the same error)
ubuntu 14.04.5 (also tried on 16.04.1 lts)

I could successfully build everything few months ago but not now.
I did build mosquitto, install and ldconfig.
when building auth pluging, I get explicit deceleration of evp_md_ctx_reset and some other functions. removed -Werror flag and I could build it. but mosquitto cannot load the plugin. When I modified mosquitto security.c to print the plugin error, it printed "undefined symbol: EVP_MD_CTX_reset ".

I tried different openssl versions (1.0.2g, 1.1.0)

I could build and run this successfully on my virtualbox machine which I setup a year ago but I went through these issues when trying to build and run on Amazon servers. 

Any help would be appreciated.

**Comment by Vishal1419** [comment]
I have also tried it on virtual machine but still I get the same error. 
Load error:  /etc/mosquitto/auth-plug.so : undefined symbol: EVP_MD_CTX_reset

If anybody finds a solution then please post it.

**Comment by FernandoGarcia** [comment]
Try: https://github.com/jpmens/mosquitto-auth-plug/pull/184/files

**Comment by Vishal1419** [comment]
@FernandoGarcia  I have already tried that without any success.

**Comment by FernandoGarcia** [comment]
I know, my answer was to @shahabmusic.

**Comment by jpmens** [comment]
Fixed via #184
