### ISSUE TITLE
wildcard chars don't work in ACL topics definition with redis

### ISSUE THREAD

**Issue by francescoPadovani81** [jpmens/mosquitto-auth-plug#198]
Hello,
it seems that wildcard chars don't work with redis backend ...? Someone has tried?
I set the following redis key/value for a user (user1), but it doesn't work:
**set user1-/cro/test/# 2**
...but when I try to publish or subscribe on topic "/cro/test/something" or "/cro/test/something/else" it is not authorized (I see this in logs).
Instead if I set the redis/key with a specific topic, like
**set user1-/cro/test/something 2**
...it works like a charm.

Is this a bug? Or I'm wrong somewhere inside the configuration?

Thanks

**Comment by thpham** [comment]
@francescoPadovani81 I got the same problem with "+" wildcard.
it seems to be a bug !

**Comment by rh389** [comment]
Looking at the code, this definitely isn't supported. The backend does a simple GET query, so requires an exact match of the full `username-topic` string being requested. 

I've put in a PR to clarify the docs, but the implementation would pretty much need a rewrite to support wildcards properly. Sorry!

**Comment by karran6190** [comment]
I am working on Mosquitto and plan to use Redis as the back end to  handle both username/password pair authentication and ACL. I am using  JPmens' authentication plugin to do this.
 mosquitto conf:
 auth_opt_backends redis
 auth_plugin /etc/mosquitto/auth-plug.so
 auth_opt_redis_host 127.0.0.1 
 auth_opt_redis_port 6379 
 auth_opt_redis_userquery GET %s 
 auth_opt_redis_aclquery GET %s-%s 
 Following name/password pairs are working fine for the authentication  
SET user1 PBKDF2$sha256$901$Qh18ysY4wstXoHhk$g8d2aDzbz3rYztvJiO3dsV698jzECxSg 
 Following settings won't work for the ACL:  SET user1-test 2  
Following are the logs of mosquitto :  
1507037072: Denied PUBLISH from mosqpub/3838-ip-172-31- (d0, q0, r0, m0, 'user1-test', ... (4 bytes)) 1507037072: Received DISCONNECT from mosqpub/3838-ip-172-31-  So, whenever I try to pub/sub mosquitto authenticate the user but didn't allow for publishing and disconnect the user.  
Testing with:  
mosquitto_pub -p 1884 -t "test" -m "demo" -u user1 -P xyz   
for sub: 
 mosquitto_sub -p 1884 -t "test" -u user1 -P xyz
