### ISSUE TITLE
make error on arch

### ISSUE THREAD

**Issue by matteb99** [jpmens/mosquitto-auth-plug#201]
I'm trying to compile this excellent plug-in but I get this error while compiling with make.. here the output:
Selected backends:          MySQL
Using mosquitto source dir: /home/matteo01/test/mosquitto-1.4.4
OpenSSL install dir:        /usr
 
If you changed the backend selection, you might need to 'make clean' first
 
CFLAGS:  -I/home/matteo01/test/mosquitto-1.4.4/src/ -I/home/matteo01/test/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  -I/usr/include/mysql  -I/src -DDEBUG=1 -I/usr/include
LDFLAGS:   -L/home/matteo01/test/mosquitto-1.4.4/lib/
LDADD:    -L/usr/lib  -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -L/usr/lib -lcrypto -lmosquitto
 
cc -I/home/matteo01/test/mosquitto-1.4.4/src/ -I/home/matteo01/test/mosquitto-1.4.4/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o cache.o cache.c
cache.c: In function 'sha_hash':
cache.c:48:23: error: implicit declaration of function 'EVP_MD_CTX_new' [-Werror=implicit-function-declaration]
   EVP_MD_CTX *mdctx = EVP_MD_CTX_new();
                       ^~~~~~~~~~~~~~
cache.c:48:23: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
cache.c:53:3: error: implicit declaration of function 'EVP_MD_CTX_free' [-Werror=implicit-function-declaration]
   EVP_MD_CTX_free(mdctx);
   ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: cache.o] Error 1
 
 
and this is a my uname -a
Linux samsungnc1002.server.matteob99 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:41:20 CET 2017 i686 GNU/Linux

**Comment by lanker** [comment]
From https://www.openssl.org/docs/manmaster/man3/EVP_MD_CTX_new.html:

"EVP_MD_CTX_create() and EVP_MD_CTX_destroy() were renamed to EVP_MD_CTX_new() and EVP_MD_CTX_free() in OpenSSL 1.1."

Arch Linux is currently using OpenSSL 1.0.

**Comment by jpmens** [comment]
Fixed via #184

**Comment by btry** [comment]
Hi

Note : the release 0.0.9 does not compile on an up to date Debian Jessie for the same reason.

**Comment by jpmens** [comment]
Try 0.1.1 build just now
