### ISSUE TITLE
seg fault during authentication via http

### ISSUE THREAD

**Issue by gmatt76** [jpmens/mosquitto-auth-plug#202]
Hi,
we are trying to use the authentication over http, configuring auth-plug with:

auth_plugin /usr/local/sbin/auth-plug.so

auth_opt_backends http
auth_opt_http_ip 127.0.0.1
auth_opt_http_port 80
auth_opt_http_getuser_uri /cms_auth.php
auth_opt_http_superuser_uri /cms_superuser.php
auth_opt_http_aclcheck_uri /cms_acl.php

The user authentication phase is going good, but when we try to publish a topic we experience a seg. fault:

root@testbed-234:/home/httpd/cms# mosquitto -c /etc/mosquitto/mosquitto.conf -v
1488296899: mosquitto version 1.4.11 (build date 2017-02-24 09:41:40+0000) starting
1488296899: Config loaded from /etc/mosquitto/mosquitto.conf.
1488296899: |-- *** auth-plug: startup
1488296899: |-- ** Configured order: http

1488296899: |-- with_tls=false
1488296899: |-- getuser_uri=/cms_auth.php
1488296899: |-- superuser_uri=/cms_superuser.php
1488296899: |-- aclcheck_uri=/cms_acl.php
1488296899: |-- getuser_params=(null)
1488296899: |-- superuser_params=(null)
1488296899: |-- aclcheck_paramsi=(null)
1488296899: |-- retry_count=3
1488296899: Opening websockets listen socket on port 8883.
1488296899: Opening ipv4 listen socket on port 8884.
1488296899: Opening ipv6 listen socket on port 1883.
1488296899: Opening ipv4 listen socket on port 1883.
1488296912: New connection from 192.168.24.171 on port 8884.
1488296912: |-- mosquitto_auth_unpwd_check(administrator)
1488296912: |-- ** checking backend http
1488296912: |-- url=http://127.0.0.1:80/cms_auth.php
1488296912: |-- data=username=administrator&password=admin&topic=&acc=-1&clientid=
<?xml version="1.0" encoding="UTF-8"?>
1488296912: |-- getuser(administrator) AUTHENTICATED=1 by http
1488296912: New client connected from 192.168.24.171 as peami-backend (c1, k60, u'administrator').
1488296912: Sending CONNACK to peami-backend (0, 0)
1488296912: |-- mosquitto_auth_acl_check(..., peami-backend, administrator, CMS/test, MOSQ_ACL_WRITE)
Segmentation fault

Puhlishing with:

mosquitto_pub -h 192.168.1.234 -p 8884 -t 'CMS/test' -i 'peami-backend' -u 'administrator' -P 'admin' -m ""

Tests done on a Debian 7.

Thanks in advance,
Gianluca

**Comment by jpmens** [comment]
Please provide a concise, but complete example of scripts which demonstrate the issue.

**Comment by gmatt76** [comment]
Hi,

the php scripts I'm using are very minimal (simple_auth.php, simple_superuser.php, simple_acl.php):

<?php
        http_response_code(400);
?>

Again, the issue happens only when publishing, not when subscribing.

Running the same example within gdb, I got the following:

gdb mosquitto 
[...]
(gdb) r -c /etc/mosquitto/mosquitto.conf -v
Starting program: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
1488980714: mosquitto version 1.4.11 (build date 2017-02-24 09:41:40+0000) starting
1488980714: Config loaded from /etc/mosquitto/mosquitto.conf.
1488980714: |-- *** auth-plug: startup
1488980714: |-- ** Configured order: http

1488980714: |-- with_tls=false
1488980714: |-- getuser_uri=/simple_auth.php
1488980714: |-- superuser_uri=/simple_superuser.php
1488980714: |-- aclcheck_uri=/simple_acl.php
1488980714: |-- getuser_params=(null)
1488980714: |-- superuser_params=(null)
1488980714: |-- aclcheck_paramsi=(null)
1488980714: |-- retry_count=3
1488980714: Opening websockets listen socket on port 8883.
1488980714: Opening ipv4 listen socket on port 8884.
1488980714: Opening ipv6 listen socket on port 1883.
1488980714: Opening ipv4 listen socket on port 1883.
1488980722: New connection from 192.168.24.171 on port 8884.
1488980722: |-- mosquitto_auth_unpwd_check(user)
1488980722: |-- ** checking backend http
1488980722: |-- url=http://127.0.0.1:80/simple_auth.php
1488980722: |-- data=username=user&password=password&topic=&acc=-1&clientid=
1488980722: |-- getuser(user) AUTHENTICATED=1 by http
1488980722: New client connected from 192.168.24.171 as peami-backend (c1, k60, u'user').
1488980722: Sending CONNACK to peami-backend (0, 0)
1488980722: |-- mosquitto_auth_acl_check(..., peami-backend, user, CMS/test, MOSQ_ACL_WRITE)

Program received signal SIGSEGV, Segmentation fault.
0xb7eac512 in OPENSSL_cleanse () from /usr/local/lib/libcrypto.so.1.1
(gdb) 

Thanks in advance,
Gianluca

**Comment by jpmens** [comment]
I cannot help if you don't provide simple versions of simple_auth.php, simple_superuser.php, simple_acl.php which prove your point.

**Comment by gmatt76** [comment]
Sorry, the code was not inserted properly in my previous post, I have just edited it.
