### ISSUE TITLE
Message bad request

### ISSUE THREAD

**Issue by andriwarda** [jpmens/mosquitto-auth-plug#206]
I'm sorry for annoying this forum.
I want to know about `code 400, message Bad HTTP/0.9 request type`
I want try to run http back-ends plugin, i follow step-by-step configuration from `https://github.com/jpmens/mosquitto-auth-plug` and from this website `http://my-classes.com/2015/02/05/acl-mosquitto-mqtt-broker-auth-plugin/`. When i running server from `https://github.com/jpmens/mosquitto-auth-plug/blob/master/examples/http-auth-be.py`, and in another terminal i try to publish and subscribe with this command,
`mosquitto_pub -h 127.0.0.1 -t "test" -m "hello_world" -u "jane@mens.de" -P "jolie" -p 8100
` and `mosquitto_sub -t "test" -u "jane@mens.de" -P "jolie" -p 8100`
But i have output `127.0.0.1 - - [08/Mar/2017 09:10:42] code 400, message Bad HTTP/0.9 request type ('\x10:\x00\x06MQIsdp\x03\xc2\x00<\x00\x17mosqpub/5022-andri-K43S\x00')
127.0.0.1 - - [08/Mar/2017 09:10:42] ":MQIsdp�<mosqpub/5022-andri-K43S
                                                                          jane@mens.dejolie" 400 -
`
Here my configuration file,
`# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_backends http
auth_opt_http_ip 127.0.0.1
auth_opt_http_port 8100
#auth_opt_http_hostname example.org
auth_opt_http_getuser_uri /auth
auth_opt_http_superuser_uri /superuser
auth_opt_http_aclcheck_uri /acl`

Can someone give me a suggestion about where to look to find the error?
Thanks in advance

**Comment by rh389** [comment]
The http server is only for mosquitto (via this plugin) to talk to, to authenticate/authorise requests. You're trying to publish messages to the http server. Publish/subscribe to mosquitto instead.

Client <---> Mosquitto (port 8884 by default) <---> http auth server (port 8100 in your example)
