### ISSUE TITLE
Error acl checking and superuser

### ISSUE THREAD

**Issue by andriwarda** [jpmens/mosquitto-auth-plug#208]
Hello,
Firstly i want to say thank you about this plugin. 
I want to run mosquitto auth plugin with http back-ends, in mosquitto configuration i don't have problem. When i run the plugin its running correctly, but when i try to publish and subscribe a topics i have error in acl checking and superuser.
Publish command `mosquitto_pub  -t ‘topic’ -m world -u jane@mens.de -P jolie`
In configuration terminal 
```
1489372724: New connection from 127.0.0.1 on port 1883.
1489372724: |-- mosquitto_auth_unpwd_check(jane@mens.de)
1489372724: |-- ** checking backend http
1489372724: |-- url=http://127.0.0.1:80/auth
1489372724: |-- data=username=jane%40mens.de&password=jolie&topic=&acc=-1&clientid=
1489372724: |-- getuser(jane@mens.de) AUTHENTICATED=1 by http
1489372724: New client connected from 127.0.0.1 as mosqpub/2582-andri-K43S (c1, k60, u'jane@mens.de').
1489372724: |-- mosquitto_auth_acl_check(..., mosqpub/2582-andri-K43S, jane@mens.de, ‘topic’, MOSQ_ACL_WRITE)
1489372724: |-- url=http://127.0.0.1:80/superuser
1489372724: |-- data=username=jane%40mens.de&password=&topic=&acc=-1&clientid=
1489372724: |-- url=http://127.0.0.1:80/acl
1489372724: |-- data=username=jane%40mens.de&password=&topic=%E2%80%98topic%E2%80%99&acc=2&clientid=mosqpub/2582-andri-K43S
1489372724: |-- aclcheck(jane@mens.de, ‘topic’, 2) AUTHORIZED=0 by (null)
1489372724: |--  Cached  [D6C7CA4F0DA50EE2B0B7E9E87BD0B65D259C63E3] for (mosqpub/2582-andri-K43S,jane@mens.de,2)
1489372724: |--  Cleanup [544DD810798AFBB3AC96C7F4480793259348D57A]
1489372724: |--  Cleanup [17E2593BA03279EB274B10288D15E88A72942CFA]
1489372724: Client mosqpub/2582-andri-K43S disconnected.
```

In server terminal
```
127.0.0.1 - - [13/Mar/2017 09:38:44] "POST /auth HTTP/1.1" 200 0
127.0.0.1 - - [13/Mar/2017 09:38:44] "POST /superuser HTTP/1.1" 403 0
127.0.0.1 - - [13/Mar/2017 09:38:44] "POST /acl HTTP/1.1" 403 0
```
Can anyone help me about acl checking and superuser ?
Thank you for advance.

**Comment by jpmens** [comment]
Your `superuser` and `acl` HTTP endpoints return 403

**Comment by andriwarda** [comment]
Thank's for fast reply sir, what can i do to solve my problem about acl and superuser ?

**Comment by jpmens** [comment]
Fix the scripts on your HTTP endpoints to accept, check parameters and 
return proper result codes.

**Comment by andriwarda** [comment]
I'm sorry sir, do you mean the code that i run in server ?

**Comment by rh389** [comment]
Yes - your http server (the code behind `/superuser` and `/acl`) is telling the plugin to deny access (code `403`). You need to make those endpoints return `200` in the appropriate circumstances.
