### ISSUE TITLE
Http auth plugin detect username as anonymous

### ISSUE THREAD

**Issue by andriwarda** [jpmens/mosquitto-auth-plug#212]
Firstly i say thank's for this plugin.
Can you help me ? :) I configure http auth plugin as back-end and use arduino as client to publish.
But i have some error, the mosquitto can't detect my username. It's detect username as anonymous.
Here shown in the terminal,
`New connection from 192.168.1.108 on port 1883.
1489580188: New client connected from 192.168.1.108 as jane@mens.de, jolie (c1, k15).
1489580188: |-- mosquitto_auth_acl_check(..., jane@mens.de, jolie, anonymous, outTopic, MOSQ_ACL_WRITE)
1489580188: |-- url=http://127.0.0.1:80/superuser
1489580188: |-- data=username=anonymous&password=&topic=&acc=-1&clientid=
1489580188: |-- url=http://127.0.0.1:80/acl
1489580188: |-- data=username=anonymous&password=&topic=outTopic&acc=2&clientid=jane@mens.de, jolie
1489580188: |-- aclcheck(anonymous, outTopic, 2) AUTHORIZED=0 by (null)
1489580188: |--  Cached  [7AC092533CEA51E0FE24A4D9C07334FD4E44C03E] for (jane@mens.de, jolie,anonymous,2)
1489580188: |-- mosquitto_auth_acl_check(..., jane@mens.de, jolie, anonymous, outTopic, MOSQ_ACL_WRITE)
1489580188: |-- aclcheck(anonymous, outTopic, 2) CACHEDAUTH: 12
`
Can anyone help me ? Thank's for advance.

**Comment by eppak** [comment]
I have sometime the same behaviour, i explicited the anonymous deny on the config but seems to be ignored by the plugin in some way.

**Comment by jpmens** [comment]
There's typically no such thing as sometimes yes, sometimes no. Cannot reproduce.
