### ISSUE TITLE
Make with mongo backend fails with mongoc.h: No such file or directory

### ISSUE THREAD

**Issue by walschap** [jpmens/mosquitto-auth-plug#213]
Hey

I'm trying to make with only the mongo backend, but it fails:
It looks like in be-mongo.c,  mongoc.h is referenced but in my opinion only be-mongo.h exists.

--> partial output
cc -I..//src/ -I..//lib/ -fPIC -Wall -Werror  -DBE_MONGO  -I/usr/local/include/ -I/usr/local/include/libmongoc-1.0/ -I/usr/local/include/libbson-1.0/ -Wno-deprecated-declarations -I/src -DDEBUG=1 -I/usr/include   -c -o be-mongo.o be-mongo.c
be-mongo.c:14:20: fatal error: mongoc.h: No such file or directory
compilation terminated.
make: *** [be-mongo.o] Error 1
<builtin>: recipe for target 'be-mongo.o' failed

Thx in advance

**Comment by jpmens** [comment]
Have you installed mongo development libraries and headers?

**Comment by walschap** [comment]
No I didn't, I see now what I forgot and will install them, 
thanx for the quick reply
