### ISSUE TITLE
Error on runing the updeted  "mosquitto-auth-plug" version

### ISSUE THREAD

**Issue by kSuccess** [jpmens/mosquitto-auth-plug#217]
when i try to run the last update of mosquitto-auth-plug with this command "sudo make " but i had these errors : 
be-mongo.c: In function ‘be_mongo_new_uri_from_options’:
be-mongo.c:100:4: error: implicit declaration of function ‘mongoc_uri_set_username’ [-Werror=implicit-function-declaration]
    mongoc_uri_set_username(uri, user);

be-mongo.c:102:5: error: implicit declaration of function ‘mongoc_uri_set_password’ [-Werror=implicit-function-declaration]
     mongoc_uri_set_password(uri, password);
     ^
be-mongo.c:106:4: error: implicit declaration of function ‘mongoc_uri_set_auth_source’ [-Werror=implicit-function-declaration]
    mongoc_uri_set_auth_source(uri, authSource);

**Comment by rh389** [comment]
The latest version requires 1.4.0 or later of the mongo c driver. Those setters were only introduced then.

**Comment by kSuccess** [comment]
ok thanks i will try with 1.6.1 version

**Comment by rh389** [comment]
In case you run into the same issue - I couldn't manage to build 1.6.1 myself - their `configure` wouldn't parse for whatever reason. 1.6.0 was ok.

**Comment by kSuccess** [comment]
in the older version i my auth_opt_mongo_uri  "mongodb://user:password"
how can i include host,port,user and password in the last version

**Comment by rh389** [comment]
See https://docs.mongodb.com/manual/reference/connection-string/

For standalone servers they're basically the same as http uris, i.e. mongodb://user:pass@host:port

The old options are still implemented too, just deprecated. If an old config has stopped working it might be a bug.

**Comment by kSuccess** [comment]
thanks a lot @rh389
