### ISSUE TITLE
Authentication & Key Problem 

### ISSUE THREAD

**Issue by kSuccess** [jpmens/mosquitto-auth-plug#223]
hi my goal is to add authentication and ACL  into mosquitto broker
in my configuration file /etc/mosquitto/mosquitto.conf :  

```
    listener 1883
    auth_opt_backends mongo
    auth_plugin /home/test/Desktop/mqtt/mosquitto-auth-plug-master/auth-plug.so
    auth_opt_mongo_uri mongodb://user:password@localhost:27017
    auth_opt_mongo_database dbmongo
    auth_opt_mongo_user_coll users
    auth_opt_mongo_topiclist_coll topics

```

and my users ans topics collections on the data base : 
```
      { 
              "_id" : ObjectId("58d5131676be970df7369901"), 
              "user_username_prop" : "user", 
             "user_password_prop" :  "PBKDF2$sha256$901$PZEEmxrVhqL4bxfK$EssexnmkFM8u7jFLqkJRnW1AsxT0NqBJ", 
           "user_topiclist_fk_prop" : NumberInt(12), 
           "user_topics_prop" : {
                   "[/sensor/ph]" : "r",  "[/sensor/temperature]" : "w", "[/sensor/production]" : "rw"  }, 
          "user_superuser_prop" : NumberInt(0)
}
 topics collection :
   { 
    "_id" : NumberInt(12), 
    "topiclist_topics_prop" : [ "/test/ph", "/test/temperature", "/test/production"
    ]
} 

```
when i run mosquitto by this comande : sudo mosquitto -c /etc/mosquitto/mosquitto.conf : 

```
         1490552332: |-- *** auth-plug: startup
       1490552332: |-- ** Configured order: mongo
```
then i launch mosquitto_sub : 
  mosquitto_sub -v -u user -P password -t   /sensor/production
      it show me     :   Connection Refused: not authorised  on the mosquitto_sub's terminal 
```
                 and :  getuser(user) AUTHENTICATED=0 by none
               1490553737: |-- mosquitto_auth_unpwd_check(user)
              1490553737: |-- ** checking backend mongo
               1490553737: |-- getuser(user) AUTHENTICATED=0 by none
```
in the mosquitto broker's terminal 
but when i replace the key user_usermane_prop and user_password_prop by username and password respectively on the users's collection 
the result on the mosquitto broker's terminal : 
```

       1490554113: |-- mosquitto_auth_unpwd_check(user)
        1490554113: |-- ** checking backend mongo
        1490554113: |-- getuser(user) AUTHENTICATED=1 by mongo
```
 until know authentication works fine 
   but when i type mosquittp_pub commande  
   mosquitto mosquitto_pub -d -u user -P password -t /sensor/production -m "test "
it show me this error in the mosquitto broker's terminal : 
```
       1490554413: |-- ** checking backend mongo
       1490554413: |-- getuser(user) AUTHENTICATED=1 by mongo
       1490554413: |-- mosquitto_auth_acl_check(..., mosqpub/7716-test-Virtu, user, /sonsor/production,   MOSQ_ACL_WRITE)
        src/bson/bson.c:1549 bson_append_utf8(): precondition failed: key
       Aborted (core dumped).
```
i don't know if i must change all keys in the users collections ??

**Comment by rh389** [comment]
I think you're misunderstanding the docs (maybe my notation is unclear). `"username"` is the default place for your user's ID, so by default your documents should have a property on them called `"username"`.

`users_username_prop` is a _configuration option_ you can optionally use to make the plugin look at a different field, for example by setting `auth_opt_mongo_users_username_prop email_address` in `mosquitto.conf`. It's a variable containing the name of the property, not the literal name of the property. Same with all of the other property names (the square brackets around the field names are meant to denote that - that's how you use variable values as object keys in javascript).

In the end it looks like the plugin has crashed, which is a bug. I'll look into that. 

([Try using triple backticks](https://guides.github.com/features/mastering-markdown/) around code or logs by the way - it's hard to read your issue)

**Comment by kSuccess** [comment]
i think there is a bug in the plugin because when i replace ""bson_append_utf8(&query, handle->user_username_prop, -1, username, -1)"" function on be-mongo.c with
""bson_append_utf8(&query, "username", -1, username, -1)"" it works fine

**Comment by rh389** [comment]
Yikes, yes you're right there's a horrible bug in there. https://github.com/jpmens/mosquitto-auth-plug/pull/226 is the fix. Thanks for tracking that down.

**Comment by SunilSheth** [comment]
Thanks kSuccess for finding and solving the bug, We where working on it yesterday and facing same problem.
And thank you Rob Hogan for adding mongoDb support

**Comment by SunilSheth** [comment]
the problem still exist.....please guide the modification required in be-mongo.c to solve the problem

**Comment by kSuccess** [comment]
@SunilSheth in be-mongo.c try to replace every function ""bson_append_utf8 (&query, "username", -1, username, -1);""  with this function "bson_append_utf8 (&query, conf->user_username_prop, -1, username, -1);"" in my case i replace it in 3 places save the changes and run "make clean" to the plugin after that run make command to build the plugin again

**Comment by kSuccess** [comment]
@SunilSheth or just Download mosquitto-auth-plug master version it contain the last modifications

**Comment by rh389** [comment]
Yes, the fix is now in master (the biggest issue was that user_username_prop wasn't being initialised), although I haven't had chance to test it personally - if you still have problems please post your logs and config.

**Comment by SunilSheth** [comment]
thanks @kSuccess 
it works now!
