### ISSUE TITLE
Authentication over PSK and ACL with plugin

### ISSUE THREAD

**Issue by dominik4545** [jpmens/mosquitto-auth-plug#224]
Hi everyone,
as I do not know how to ask a question otherwise, I'm using this - sorry for that...

Is it possible to use authentication via pre shared ssh-keys/certificates and do the access control list using this plugin in combination with a MySQL-DB? If yes, how should my configuration file look like? Would there be any further steps?

Thanks a lot in advance!
Best regards
Dominik

**Comment by jpmens** [comment]
This software does not use (and never will use) SSH keys.
