### ISSUE TITLE
Merge JWT into HTTP?

### ISSUE THREAD

**Issue by rh389** [jpmens/mosquitto-auth-plug#228]
Currently, the JWT backend does exactly what the HTTP backend does, except passing a different `Authorization` header. This results in a lot of unnecessary duplication of code.

If I got a chance to work on a PR would you be open to adding `auth_scheme` as an `http` configuration option, and removing the separate `jwt` backend?

(Long-term, I think real JWT support would mean the plugin decoding the JWT, verifying the signature against a provided certificate and using the JWT's claims for permissions. The whole point of a JWT is that it speaks for itself, so it shouldn't be necessary to call off to another server.)

**Comment by jpmens** [comment]
I think that would be very good, yes, and I'd appreciate if you made that happen; I'll gladly take a PR for that.

**Comment by rh389** [comment]
I just had a look at this but there's more to it than I thought because of the way the http backend currently sets both the `Authorization` header _and_ sends the username and password in form data (and has a separate `basic_auth_key` config which also sets an auth header, which may be overwritten).

I'd need a bit more time than I have at the moment to pick the bones out of it and come up with a sane set of config options, I suspect, so closing for now but might return later.
