### ISSUE TITLE
ud->be_list is not cleaned up at mosquitto_auth_plugin_cleanup

### ISSUE THREAD

**Issue by auselen** [jpmens/mosquitto-auth-plug#231]
Seems like `ud->be_list` is not cleaned up at `mosquitto_auth_plugin_cleanup`. Kill functions are never called as well. It might not sound necessary, but It makes valgrind unhappy and can shadow other issues.

May be something like this is needed?
```
	if (ud->be_list) {
		struct backend_p **bep;
		for (bep = ud->be_list; bep && *bep; bep++) {
			(*bep)->kill((*bep)->conf);
			free((*bep)->name);
			free((*bep)->conf);
			free(*bep);
		}
		free(ud->be_list);
	}
```

**Comment by auselen** [comment]
and call `(*bep)->kill((*bep)->conf);` before the first `free`.

**Comment by jpmens** [comment]
You're right. I'm adding this now even if possibly not complete.
