### ISSUE TITLE
JWT Token verifying

### ISSUE THREAD

**Issue by andriwarda** [jpmens/mosquitto-auth-plug#233]
Hello, 
I try to implement jwt back-ends, i successfully get the token using username and password. But when i want to verify the token using this command `mosquitto_pub -t "test" -m "hola_mundo" -u "<token>"` without password it can't. Here in the mosquitto.conf terminal `1491980321: New connection from 10.34.249.21 on port 1883.
1491980321: Socket error on client <unknown>, disconnecting.`. I want to ask, whether in mosquitto, the mechanism is like that for token verification ?
Because as far as i know to verify the token we just send the token as username without password.
Please correct me if i wrong. Thanks

**Comment by auselen** [comment]
Can you try to pass an empty password? that works for me.

-P " "

**Comment by andriwarda** [comment]
Thank's for fast response, when i try empty password it works too. I want to know, to verify the token should i send the password too ? Though that is the empty password ?

**Comment by auselen** [comment]
I think it expects a password regardless, so just send an empty one.

**Comment by iceberg1369** [comment]
@andriwarda would you please post your config file please, I like to implement as well

**Comment by andriwarda** [comment]
@iceberg1369 
`auth_plugin /home/andri/Documents/mosquitto-auth-plug-master/auth-plug.so
auth_opt_backends jwt
auth_opt_http_ip localhost
auth_opt_http_port 3000
#auth_opt_http_hostname example.org
auth_opt_http_getuser_uri /auth
auth_opt_http_superuser_uri /superuser
auth_opt_http_aclcheck_uri /acl`
