### ISSUE TITLE
Http Cache

### ISSUE THREAD

**Issue by eppak** [jpmens/mosquitto-auth-plug#234]
Hello,
i'm using the plugin with http module, sometime i see a lot of calls to admin api call: my application is doing nothig. There is some cache mechanism? I can see this option only on mysql.

Thanks

**Comment by jpmens** [comment]
If your application isn't doing anything you shouldn't be seeing any logs from the authentication plugin, irrespective of the back-end used.

**Comment by eppak** [comment]
Yes, something is not in the righe place, but no cache mechanics present for this backend?

**Comment by jpmens** [comment]
I think the cache is enabled for all backends unless you disable it of course.
