### ISSUE TITLE
origin IP authentication

### ISSUE THREAD

**Issue by joser** [jpmens/mosquitto-auth-plug#236]
Hello,

I would like to implement client origin IP authentication with mosquitto-auth-plug.

I've been reading the code and I think Mosquitto broker does not provide authentication plugins the client origin IP, is this correct?

Thanks

**Comment by jpmens** [comment]
Passing in the client IP is something we'd have to request as an API change in the Mosquitto project; you're right: the broker currently does not make that available.

**Comment by jpmens** [comment]
Closing now. Feel free to re-open when Mosquitto's API provides this.
