### ISSUE TITLE
Allow plain passwords in mongo (or login without password)

### ISSUE THREAD

**Issue by jenguidanos** [jpmens/mosquitto-auth-plug#237]
Thanks for all your work, @jpmens and contributors

We are working in a "close" environment, developing our own hardware, software and IoT platform. Is there any way to use plain passwords with mongo? or directly don't use a password at all, only a username (username will be the ICCID of the sim on chip integrated on each device). We have a collection with all our sims (thousands) and my initial idea is to use this as the users collection.

**Comment by jpmens** [comment]
This is currently not possible.
