### ISSUE TITLE
Mosquitto starts rejecting connections with the reason: "not authorised" a day or two after restart (PostgreSQL)

### ISSUE THREAD

**Issue by PriyankPa** [jpmens/mosquitto-auth-plug#238]
It so happens that every other day, Mosquitto starts rejecting connections with the reason: "not authorised"
The username and password are correct because everything runs properly after restarting mosquitto.

From my general experience, I think this has got something to do with not being able to connect to the database due to stale connection references. I am not sure if there is a mechanism to validate health of database connections and create a new one if necessary. 

I am using Postgres running on the same machine as the back end. The database is up and I can query the tables required by mosquitto. 

Here's what mosquitto_pub returns:

```
mosquitto_pub -h localhost -p 1883 -q 1 -u someuser -P s3cret -t "aws/status" -m "Test message"
Connection Refused: not authorised.
Error: The connection was refused.
```

The log file entry:
/var/log/mosquitto/mosquitto.log

```
1492930284: New connection from 127.0.0.1 on port 1883.
1492930284: Sending CONNACK to 127.0.0.1 (0, 5)
1492930284: Socket error on client <unknown>, disconnecting.
```

Logging config in /etc/mosquitto/mosquitto.conf:

```
log_dest file /var/log/mosquitto/mosquitto.log
log_type all
log_type error
log_type warning
log_type notice
log_type information
#log_type subscribe
#log_type unsubscribe
log_type websockets
```
I don't program in C (except for embedded) so I don't know if this is correct but it seems a connection instance is created only at startup (in the init function) and never after that. So if the connection breaks, ACL won't work till mosquitto is restated.

[be-postgres.c](https://github.com/jpmens/mosquitto-auth-plug/blob/master/be-postgres.c)

**Comment by PriyankPa** [comment]
I have verified that the database connection is not reestablished after it is broken (in case of Postgres backend at least).

Steps to recreate:
1. (Re) Start the mosquitto service
2. Verify whether user authentication works using any client - It does.
3. Restart the database server (in order to break the connection mosquitto is holding)
4. . Verify whether user authentication works using any client - It doesn't

**Comment by jpmens** [comment]
Please test now that #255 has been applied

**Comment by PriyankPa** [comment]
I went through the files. I think the changes made won't resolve this issue.

In case of MySQL back end be-mysql.c , there is a piece of code to check connection health before issuing a query.

As part of this check, it also reestablishes connection if it is broken.

```
	if (mysql_ping(conf->mysql)) {
		fprintf(stderr, "%s\n", mysql_error(conf->mysql));
		if (!auto_connect(conf)) {
			return (NULL);
		}
	}
```

There is no such code for PostgreSQL in  `be-postgres.c `. So I don't think it would fix the problem.
 `be-postgres.c ` requires some connection check & restore functionality..

**Comment by csuarezgfx** [comment]
I just upgraded my entire system to Ubuntu 16.04 and re-compiled and installed the latest of everything. I am now getting this error when I try to use the auth-plugin. If I run mosquitto with the mosquitto.conf.example file, every client on the network is able to connect. If I enable the auth plug I start getting the error.

This is what my settings look like:
**auth_opt_host 127.0.0.1
auth_opt_port 3306
auth_opt_dbname m2m_members
auth_opt_user carlos
auth_opt_pass supersecret
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = '%s' AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw >= '%d')
auth_opt_anonusername AnonymouS
auth_opt_backends mysql**


This is the error:
**New connection from 127.0.0.1 on port 1883.
mosquitto_auth_unpwd_check(S1)
** checking backend mysql
getuser(S1) AUTHENTICATED=0 by none
Sending CONNACK to 127.0.0.1 (0, 5)
Socket error on client <unknown>, disconnecting.**

Using this client:
**mosquitto_sub -t "sensor/#" -u "S1" -P "secretpassword"** 

**_Has a solution been found?_**

**Comment by csuarezgfx** [comment]
These are my revelant ufw status readings:
**1883                       ALLOW       Anywhere                  
1885                       ALLOW       Anywhere                  
8883                       ALLOW       Anywhere                  
3306                       ALLOW       Anywhere                  
1883 (v6)                  ALLOW       Anywhere (v6)             
1885 (v6)                  ALLOW       Anywhere (v6**

**Comment by tilinna** [comment]
This still happens in Debian Stretch with the latest mosquitto-auth-plugin package -- also, I'd consider this as a bug and not merely an enhancement.

**Comment by jpmens** [comment]
It's a bug if you can demonstrate that the handling as it is currently is faulty. The original poster assumes it's due to _stale db connections_ which sounds reasonable. As the code doesn't contain handling for that, I labelled it enhancement.

Can you demonstrate that this occurs even though you're accessing Mosquitto constantly over a long period of time and the connection handles don't have a chance to go awol?

**Comment by tilinna** [comment]
Sorry, I just realized that the stable Debian Stretch package is really old. We'll retest by building from the master and get back to you with an updated info.

**Comment by tilinna** [comment]
Confirming that Debian stretch's mosquitto-auth-plugin (0.0.7-2.1) doesn't recover from losing the connection to the PostgreSQL. However, the recent d15aeb80e80669b5dbb0ff8ae0158fc976ff1c57 commit from the master appears to work fine.
So please disregard my comments related to this bug (stable db connections) -- our case was actually a temporary database connection loss which the old plugin didn't recover from.

@PriyankPa : are you sure you are running the latest version too?

**Comment by PriyankPa** [comment]
This issue was opened on Apr 23, 2017. I have not tested after that.

**Comment by jpmens** [comment]
Closing for lack of response.
