### ISSUE TITLE
[auth-plug.o] Error 127

### ISSUE THREAD

**Issue by AndroidDesigner** [jpmens/mosquitto-auth-plug#241]
Hi.
my operating system is windows 10.
I already installed the mosquitto in windows and it works perfectly.
but now I want to use this plugin for it.
I used bash on windows to run ubuntu commands to configure this plugin.
I installed required helper and developer packages : 
sudo apt-get install libc-ares-dev libcurl4-openssl-dev libmysqlclient-dev

also I created a config.mk file and set path of mosquitto and open-ssl folders.
now I want to run "make" command in "mosquitto-auth-pug" folder. but give me following error : 
 
//--------------------------
the following is bash screen shot : 
//--------------------------

JACK@MY-PC:/mnt/c/mosquitto/mosquitto-auth-plug$ make
Selected backends:          MySQL
Using mosquitto source dir: c:\mosquitto
OpenSSL install dir:        c:\OpenSSL-Win32

If you changed the backend selection, you might need to 'make clean' first

CFLAGS:  -Ic:\mosquitto/src/ -Ic:\mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  -I/usr/include/mysql  -I/src -DDEBUG=1 -Ic:\OpenSSL-Win32/include
LDFLAGS:   -Lc:\mosquitto/lib/
LDADD:    -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -Lc:\OpenSSL-Win32/lib -lcrypto -lmosquitto

cc -Ic:\mosquitto/src/ -Ic:\mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -Ic:\OpenSSL-Win32/include   -c -o auth-plug.o auth-plug.c
/bin/sh: 1: cc: not found
<builtin>: recipe for target 'auth-plug.o' failed
make: *** [auth-plug.o] Error 127

**Comment by jpmens** [comment]
It is highly unlikely that this will work on Windows at all.

**Comment by AndroidDesigner** [comment]
why?
while I have a mosquitto in windows 10 and it is running perfectly.
I think with bash on windows helping, we can run this library in windows also...

**Comment by jpmens** [comment]
If you think you can do it, do it. I don't think you can.

**Comment by AndroidDesigner** [comment]
can we use from Vmware software to create a virtual linux in windows so that we use from the linux to work with mosquitto?
