### ISSUE TITLE
Unable to load auth plugin "/etc/mosquitto/auth-plug.so"

### ISSUE THREAD

**Issue by AndroidDesigner** [jpmens/mosquitto-auth-plug#243]

**Comment by jpmens** [comment]
Furthermore, deleting your post is absolutely stupid. Consider yourself warned: I am going to complain about you if you continue doing this in this repository.

See also https://github.com/eclipse/mosquitto/issues/443#issuecomment-300445708

**Comment by AndroidDesigner** [comment]
you didnt help me at all!I created several topic about various issues,but you didnt direct me at all.
what do you mean from help?!!
