### ISSUE TITLE
using repository for this package

### ISSUE THREAD

**Issue by AndroidDesigner** [jpmens/mosquitto-auth-plug#245]
hi.
I have some problems when I installed mosquitto and this plugin by git clone.
such as : 
1. sometimes changing in mosquitto.conf does not work and we must reboot ubuntu to work it.
2. sometimes mosquitto service does not start after reboot!

Also when I use from ubuntu repository to install mosquitto, everything is good with mosquitto only not this plugin!
But my problem is that : 
when I use from repo to install mosquitto, auth-plug.so give me the following error:
can not find "mosquitto.h"
is there anyway that we can install this authentication package by repository?

**Comment by jpmens** [comment]
We are aware of this issue, and consider this a very relevant input. Since it requires some architectural changes,  we put it into our backlog as component separated issues, which will be highly prioritised as soon as possible.

**Comment by AndroidDesigner** [comment]
thank you very much.
I saw that there is a mosquitto-auth-plug package in ubuntu repository.
after install it by : "sudo apt-get install mosquitto-auth-plug", only one auth-plug.so file is created and I could not find any config.mk file. so I could not work with it.

BUT MY PROBLEM IS THAT : 
what is best method to install mosquitto that can work with this plugin?
when I used from ubuntu repository to install mosquitto, when I added auth-plug.so to the mosquitto.conf file, it said that can not found "mosquitto.h". so I could not work with this method also.

so I used from "git clone https://github.com/eclipse/mosquitto" to clone and next install mosquitto. but I dont know why with this method I have several mosquitto and mosquitto_passwd file!!
so sometimes my MQTT broker work correctly but sometime does not work!
I confused at all!!!

**Comment by jpmens** [comment]
You are confusing a binary installation from packages and an installation from source (which requires `config.mk`). We do not provide a repository for this plugin, so it's up to you to find a combination of Mosquitto and auth-plugin which works for you -- I cannot help you with that.

If you want to install from source, please study the README.md; should you have questions pertaining to that, or should you find errors in the README, I will gladly address those.

**Comment by jpmens** [comment]
I will no longer help you: https://github.com/jpmens/mosquitto-auth-plug/issues/243

**Comment by AndroidDesigner** [comment]
when did you help me at all?

**Comment by sreeisalso** [comment]
@AndroidDesigner have some respect towards others and first and foremost learn about basics of Linux and open source community before pointing at open source project creators

**Comment by AndroidDesigner** [comment]
@sreeisalso I didnt know that cleaning is a bad behaviour. Also my problems were due to my misake about ubuntu not this plugin. so I wanted dont confuse other people.
moreover @jpmens used "stupid" word for me! I think this is not a good word.
No problem at all!
I dont use from this plugin at all...
have a nice day
