### ISSUE TITLE
mosquitto service problem

### ISSUE THREAD

**Issue by BigGitWorld** [jpmens/mosquitto-auth-plug#249]
Hi!
I have installed a mosquitto (by wget method) & mosquitto-auth-plugin (by git clone) in ubuntu 16.04.
everything is ok in the installation.
now I want to edit mosquitto.conf file and then use :
usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
to apply my changes.
but seems my changes does not apply!
I did a search for "mosquitto.service" in ubuntu, but I could not find any file with this name.
why?
so I think this is my issue.
I attempted to create a "sudo nano /etc/systemd/system/mosquitto.service" file, like this :
[Unit]
Description=Insite MQTT Broker

[Service]
ExecStart=/usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
Restart=always

[Install]
WantedBy=multi-user.target

and after it I used :
sudo systemctl start mosquitto.service
systemctl status mosquitto.service
but these commands didnt help me again. because status command give me "activating" or "dead" message and I can not restart my mosquitto service to apply my changes to the mosquitto.conf.
also : 
port 1883 is listening on tcp and tcp6.
how can I solve this problem?

best regard

**Comment by jpmens** [comment]
This question is off-topic here; we are not a Mosquitto support group.
