### ISSUE TITLE
do we need enable allow_anonymous also?

### ISSUE THREAD

**Issue by BigGitWorld** [jpmens/mosquitto-auth-plug#250]
hi!
I have installed this plugin and got this message : 
    mosquitto@ubuntu:~$ /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    1494615863: |-- *** auth-plug: startup
    1494615863: |-- ** Configured order: mysql
    1494615863: |-- }}}} MYSQL
    1494615863: Error: Address already in use
then I filled my mysql database with some rows.
Now I created a publish command as below for testing:
      mosquitto_pub -t /topic -m message

But I dont know why this works!while I didnt provide username and password. namely:
       mosquitto_pub -t /topic -m message -u username -P password

why my mysql backend did not work? 
do I have to enable "allow_anonymous false" in mosquitto.conf file also?

best regard

**Comment by sreeisalso** [comment]
You have to set the allow_anonymous to falls to prevent unauthorised publishing and subscription

**Comment by BigGitWorld** [comment]
thank you for your reply
