### ISSUE TITLE
strange problem with mysql backend

### ISSUE THREAD

**Issue by BigGitWorld** [jpmens/mosquitto-auth-plug#251]
Hi!
I have installed the mosquitto and this plugin.
without the plugin everything work fine.
but I dont know why when mysql backend added to the mosquitto.conf,  publish and sucscribe does not work. although connection is good and client have to provide username and password to connect to the broker.
I should say that acls table is commented and only users table is enabled in the mysql. namely:

auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_backends mysql
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname mydb
auth_opt_user username
auth_opt_pass password
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'

what is the problem?

**Comment by jpmens** [comment]
Show me an example user and password from your database table

**Comment by BigGitWorld** [comment]
thank you for your reply. assume my mosquitto.conf is as the below : 

allow_anonymous false
auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_backends mysql
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname webdata
auth_opt_user username
auth_opt_pass password
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'

now the broker(log), publisher, subscriber and phpmyadmin are as below.
you can see that although connection is done, but publish and subscriber does not perform. so that subscriber does not receive "hi" message.
![phpmyadmin](https://cloud.githubusercontent.com/assets/28644637/26023563/0f7a62ec-37d4-11e7-894e-8268a2377515.png)
broker log:
![broker log](https://cloud.githubusercontent.com/assets/28644637/26023564/218e6be0-37d4-11e7-8d48-9942d067fc32.png)
publisher:
![publisher](https://cloud.githubusercontent.com/assets/28644637/26023566/2bdb02d4-37d4-11e7-8d66-fec323b25bdf.png)
subscriber:
![subscriber](https://cloud.githubusercontent.com/assets/28644637/26023569/3d69114e-37d4-11e7-94ca-f9be175bb5a6.png)

**Comment by jpmens** [comment]
It seems the user is authenticated (password is ok), but you're not authorized (ACL table doesn't allow the publish). Hence the log is showing you `AUTHORIZED=0` in mosquitto's log

**Comment by BigGitWorld** [comment]
I did not enable ACL table in mosquitto.conf file. So how it can effect on my publish and subscribe?

**Comment by jpmens** [comment]
I just checked the code: without ACL checks you cannot subscribe/publish, in other words, that's mandatory unless you ensure all are superusers (you can possibly get away with configuring a superuser which'll match any user (`*`).

**Comment by BigGitWorld** [comment]
shame on me!:)
I'm sorry that I did not consider it.
thank you @jpmens
