### ISSUE TITLE
write only in rw field 

### ISSUE THREAD

**Issue by lexidev** [jpmens/mosquitto-auth-plug#252]
Hello.
I installed mosquitto-auth-plug with PostgreSQL.
In documentation I found only two options for 'rw' field 
   _... In the following example, the table has a column rw containing 1 for readonly topics, and 2 for read-write topics: ..._
But mongo's version contain 3 options:  [topic: string]: "r"|"w"|"rw".
How can I use 'w' write only option in my projects?

Best regards,
Alex.

**Comment by lexidev** [comment]
And how to convert 
    SELECT topic FROM acls WHERE username = '%s' AND (rw & %d)
to Postgres ?

**Comment by jpmens** [comment]
You'll have to find some formula which will do this for you.
