### ISSUE TITLE
Question: allow_anonymous to false ?

### ISSUE THREAD

**Issue by natcl** [jpmens/mosquitto-auth-plug#258]
Hello, I have set `allow_anonymous = false` in my `mosquitto.conf` file. With the auth plugin enabled, it seems to ignore this and anonymous clients seem able to login.  I understand I can map an anonymous user to a user in the database and control which topics he can read/write via ACLs but would there be a way to prevent anonymous users from connecting at all ?

Thanks !

**Comment by jpmens** [comment]
"Seems to ignore" this and anonymous clients "seem able to login".

Is it ignored or not?
Are clients able to login or not?

Please present succinct examples

**Comment by natcl** [comment]
with `allow_anonymous = false` the clients are able to login (and are mapped to the anon user set via `auth_opt_anonusername`

**Comment by natcl** [comment]
Please disregard, there was an issue with my config file not picked the good one in Docker.
Sorry about that.
