### ISSUE TITLE
ACL denying access to client with dangerous client id

### ISSUE THREAD

**Issue by doko83** [jpmens/mosquitto-auth-plug#263]
Since a couple of days i'm stuck on this "ACL denying access to client with dangerous client id".
Dun why cause everithing always worked perfectly - no upgrade/change made

SHELL 1: BROKER
cubo@cubo:~$ sudo mosquitto -c /etc/mosquitto/mosquitto.conf
1496326143: mosquitto version 1.4.12 (build date 2017-06-01 14:10:11+0200) starting
1496326143: Config loaded from /etc/mosquitto/mosquitto.conf.
1496326143: |-- *** auth-plug: startup
1496326143: |-- ** Configured order: mysql

1496326143: |-- }}}} MYSQL
1496326143: Opening websockets listen socket on port 8080.
1496326143: Opening ipv4 listen socket on port 1883.
1496326143: Opening ipv6 listen socket on port 1883.

SHELL 2: SUBSCRIBE
mosquitto_sub -t 'test/temperatura' -u root -P xxxxxxxxx

SHELL 1: BROKER
1496326259: New connection from 127.0.0.1 on port 1883.
1496326259: |-- mosquitto_auth_unpwd_check(root)
1496326259: |-- ** checking backend mysql
1496326259: |-- getuser(root) AUTHENTICATED=1 by mysql
1496326259: New client connected from 127.0.0.1 as mosqpub/6400-cubo (c1, k60, u'root').
1496326259: ACL denying access to client with dangerous client id "mosqpub/6400-cubo"
1496326259: Client mosqpub/6400-cubo disconnected.
1496326271: New connection from 127.0.0.1 on port 1883.
1496326271: |-- mosquitto_auth_unpwd_check(root)
1496326271: |-- ** checking backend mysql
1496326271: |-- getuser(root) AUTHENTICATED=1 by mysql
1496326271: New client connected from 127.0.0.1 as mosqsub/6412-cubo (c1, k60, u'root').

SHELL 3: PUBLISH
 mosquitto_pub -t 'test/temperatura' -m 22 -u root -P xxxxxxxxx

SHELL 1: BROKER
1496326366: New connection from 127.0.0.1 on port 1883.
1496326366: |-- mosquitto_auth_unpwd_check(root)
1496326366: |-- ** checking backend mysql
1496326366: |-- getuser(root) AUTHENTICATED=1 by mysql
1496326366: New client connected from 127.0.0.1 as mosqpub/6480-cubo (c1, k60, u'root').
1496326366: ACL denying access to client with dangerous client id "mosqpub/6480-cubo"
1496326366: Client mosqpub/6480-cubo disconnected.

**Comment by jpmens** [comment]
> no upgrade/change made

You have upgraded to Mosquitto 1.4.12.

**Comment by jpmens** [comment]
There's a bug in Mosquitto which prevents its own clients from connecting to Mosquitto with automatic clientid generation. Downgrade or use specific clientIDs without slashes in them.

And please don't say 'no change made' when it's clear you have:

```
1496326143: mosquitto version 1.4.12 (build date 2017-06-01 14:10:11+0200) starting
```

**Comment by akshar001** [comment]
Hello @doko83 would you tell me how you solved this problem?

**Comment by doko83** [comment]
I made a script that runs after boot (ubuntu 16.04) that killall mosquitto
and restart like sudo mosquitto -c /path/to/mosquitto.conf

Like this everything is working correctly on my system

Il 6 ago 2017 11:43 AM, "akshar001" <notifications@github.com> ha scritto:

**Comment by akshar001** [comment]
So what i should do is to kill all mosquitto processes then start again and then restart the mosquitto?

Thanks for suggesting me

**Comment by doko83** [comment]
This is what i tried and what is working for me, i putted the script on
rc.local. no idea why like this is working, but it is xD

Il 6 ago 2017 2:30 PM, "akshar001" <notifications@github.com> ha scritto:

**Comment by akshar001** [comment]
i have tried that also killig all processes then starting mosquitto but isnt working for me

**Comment by akshar001** [comment]
sudo mosquitto -c /etc/mosquitto/mosquitto.conf
1502022992: |-- *** auth-plug: startup
1502022992: |-- ** Configured order: mysql

1502022992: |-- }}}} MYSQL
1502023001: |-- mosquitto_auth_unpwd_check(su1)
1502023001: |-- ** checking backend mysql
1502023001: |-- getuser(su1) AUTHENTICATED=1 by mysql
1502023001: Sending CONNACK to mosqpub/2240-zpanel1.ve (0, 0)
1502023001: |-- ACL denying access to client with dangerous client id "mosqpub/2240-zpanel1.ve"
1502023001: Denied PUBLISH from mosqpub/2240-zpanel1.ve (d0, q0, r0, m0, 'mega/secret', ... (11 bytes))
1502023001: Received DISCONNECT from mosqpub/2240-zpanel1.ve
1502023011: |-- mosquitto_auth_unpwd_check(akshar)
1502023011: |-- ** checking backend mysql
1502023011: |-- getuser(akshar) AUTHENTICATED=0 by none
1502023011: Sending CONNACK to ::1 (0, 5)
1502023016: |-- mosquitto_auth_unpwd_check(akshar)
1502023016: |-- ** checking backend mysql
1502023016: |-- getuser(akshar) AUTHENTICATED=0 by none
1502023016: Sending CONNACK to ::1 (0, 5)
1502023017: |-- mosquitto_auth_unpwd_check(akshar)
1502023017: |-- ** checking backend mysql
1502023017: |-- getuser(akshar) AUTHENTICATED=0 by none
1502023017: Sending CONNACK to ::1 (0, 5)
1502023018: |-- mosquitto_auth_unpwd_check(akshar)
1502023018: |-- ** checking backend mysql
1502023018: |-- getuser(akshar) AUTHENTICATED=0 by none
1502023018: Sending CONNACK to ::1 (0, 5)
1502023107: |-- mosquitto_auth_unpwd_check(akshar)
1502023107: |-- ** checking backend mysql
1502023107: |-- getuser(akshar) AUTHENTICATED=0 by none
1502023107: Sending CONNACK to ::1 (0, 5)
1502023116: |-- mosquitto_auth_unpwd_check(su1)
1502023116: |-- ** checking backend mysql
1502023116: |-- getuser(su1) AUTHENTICATED=1 by mysql
1502023116: Sending CONNACK to mosqpub/2250-zpanel1.ve (0, 0)
1502023116: |-- ACL denying access to client with dangerous client id "mosqpub/2250-zpanel1.ve"
1502023116: Denied PUBLISH from mosqpub/2250-zpanel1.ve (d0, q0, r0, m0, 'mega/secret', ... (11 bytes))
1502023116: Received DISCONNECT from mosqpub/2250-zpanel1.ve
1502023213: |-- mosquitto_auth_unpwd_check(su1)
1502023213: |-- ** checking backend mysql
1502023213: |-- getuser(su1) AUTHENTICATED=1 by mysql
1502023213: Sending CONNACK to mosqpub/2263-zpanel1.ve (0, 0)
1502023213: |-- ACL denying access to client with dangerous c

**Comment by doko83** [comment]
Mmm try rollback to mossquitto 1.4.11?

Il 6 ago 2017 2:38 PM, "akshar001" <notifications@github.com> ha scritto:

**Comment by akshar001** [comment]
i am using mosquittto 1.4.10

**Comment by akshar001** [comment]
as it turned out i have tried using it with assigning specific client id as jpmens have said
right now its working best

**Comment by doko83** [comment]
This is the most correct way to fix this bug

Il 7 ago 2017 8:00 AM, "akshar001" <notifications@github.com> ha scritto:

**Comment by csuarezgfx** [comment]
akshar001, can you post the sequence of terminal commands that you enter and a copy of your config file settings?
