### ISSUE TITLE
is %d really only be replaced once in mysql query?

### ISSUE THREAD

**Issue by eisbehr-** [jpmens/mosquitto-auth-plug#265]
Hello,

I have an mysql query where it would more performant to have `%d` replaced two times. In the documentation it is mentioned that `a single '%d' is replaced`. I think you use something like `sprintf` to do this. Did that mean using `%d` multiple times in a query would not work in any way?

My ACL query actually looks like this:
```MYSQL
SELECT IFNULL(p.topic, s.topic)
FROM users u
LEFT OUTER JOIN acls_publisher p ON u.type = 'publisher'
LEFT OUTER JOIN acls_subscriber s ON u.type = 'subscriber'
WHERE u.username = '%s' AND IFNULL(p.rw, s.rw) >= %d
```

But it would be better to have it set in the `joins`:
```MYSQL
SELECT IFNULL(p.topic, s.topic)
FROM users u
LEFT OUTER JOIN acls_publisher p ON u.type = 'publisher' AND p.rw >= %d
LEFT OUTER JOIN acls_subscriber s ON u.type = 'subscriber' AND s.rw >= %d
WHERE u.username = '%s'
```

**Comment by wavezhang** [comment]
you can see from code [here](https://github.com/jpmens/mosquitto-auth-plug/blob/master/be-mysql.c#L317)

it will not work in your case, but you can build your own plugin to make it work

**Comment by eisbehr-** [comment]
Ahh, I see. Thank you.

Maybe it could be an idea to use a replace instad of `sprintf` here. Just replace `%s` with the username and `%d` with the `read-write` value. Then everyone would be a bit more flexible with it's queries, but still has the same functionality.

But it's just an idea. I have to stay with my query then. I would not like to build my own version and just stay with the default ...

**Comment by eisbehr-** [comment]
Over a year, no comment nor a single reaction and then closed. Thanks @jpmens !

**Comment by eisbehr-** [comment]
He just responded to my question, that it's really only replaced once (a thing i couldn't believe so far). And i made the suggestion to change that behavior, what would possible be very easy and not harm any backwards compatibility. But that can only be reviewed by you, as the owner, i think.

Sad that you don't see a reason to comment on improvements users have. Even if it's just an idea.

**Comment by jpmens** [comment]
I've processed 24 issues and 3 PR today.

Send me your bank details, and I'll give you a full refund.

**Comment by jpmens** [comment]
I'm sorry; that was uncalled for. 

> Maybe it could be an idea to use a replace instad of sprintf here. Just replace %s with the username and %d with the read-write value. 

If you're up to submitting a pull-request which implements this, we'll take it.
