### ISSUE TITLE
improvement: have client id available in userquery

### ISSUE THREAD

**Issue by eisbehr-** [jpmens/mosquitto-auth-plug#266]
It would be really nice, if the `client id` would be available in the `userquery` too. It would be helpfull to restrict clients to only use a given client id. For example to force clients to use it's username as `client id`.

```MYSQL
SELECT pw FROM users WHERE username = '%s' AND clientid = '%s' LIMIT 1
```

**Comment by jpmens** [comment]
@eisbehr- giving yourself a thumbs-up -- I must remember to do that more often. ;-)

**Comment by eisbehr-** [comment]
Yeha, you should do! Pretty nice feeling. But I got you, have my thumb up for you too! ;)

**Comment by jpmens** [comment]
Thank you for the suggestion. This has now been implemented for the `mysql` backend and can easily be extended for the others on demand, as the `be_xxxx_getuser()` function gets the MQTT _clientid_ passed to it.

**Comment by eisbehr-** [comment]
Thank you very much! 👍
