### ISSUE TITLE
Is it required openssl source directory?

### ISSUE THREAD

**Issue by prasadnadendla** [jpmens/mosquitto-auth-plug#267]
I'm getting this error message
I'm using centos 7 and i gave the path /etc/pki/ssl
openssl/evp.h: No such file or directory

**Comment by prasadnadendla** [comment]
Hey guys,

I installed dev library it worked . thank you. But getting this one now
/usr/bin/ld: cannot find -lmosquitto

**Comment by jpmens** [comment]
You need the Mosquitto development libraries.

**Comment by prasadnadendla** [comment]
Hey, Thank you very much. The issue is resolved :)
