### ISSUE TITLE
Mosquitto-auth-plug fails to authenticate MqTT Connection if TLS PSK is configured.

### ISSUE THREAD

**Issue by HarishHothi** [jpmens/mosquitto-auth-plug#271]
Hi ,
   I am using mosquitto version 1.4.12 with mosquitto-auth-plug (latest cloned form git master branch)to do authentication and authorization. I want to have three listener,
   1. MqTT without security (port 1833)
   2. MqTT with TLS-PSK (port 8883)
   3. MqTT with X509 Certificates (port 8884)

 I am using mosquitto-auth-plug with BE_PSK flag set(I set in my config.mk file (CFLAGS += -DBE_PSK=1 $(BACKENDS) $(BE_CFLAGS) -I$(MOSQ)/src -DDEBUG=1 $(OSSLINC)) ). below is my mosquitto configuration file.

###### "mosquitto configuration file"
auth_plugin /home/{USER_NAME}/Documents/mosquitto/src/mosquitto-22June/auth-plug.so
bind_address 10.1.1.167
port 1883
protocol mqtt

auth_opt_backends mysql
auth_opt_host 10.37.3.24
auth_opt_port 3306
auth_opt_dbname mosquitto
auth_opt_user {db-username}
auth_opt_pass {db-password}
auth_opt_userquery SELECT pw FROM USER WHERE username = '%s'
auth_opt_aclquery SELECT topic FROM ACLS WHERE (username = '%s') AND (rw >= %d)
auth_opt_acl_cacheseconds 60

######## "X509 CONNECTOR "
listener 8884
cafile /home/{USER_NAME}/Documents/mosquitto/src/mosquitto-22June/certs/ca.crt
certfile /home/{USER_NAME}/Documents/mosquitto/src/mosquitto-22June/certs/server.crt
keyfile /home/{USER_NAME}/Documents/mosquitto/src/mosquitto-22June/certs/server.key
require_certificate false

######## "PSK CONNECTOR"
listener 8883
auth_opt_psk_database mysql
psk_hint hint1
use_identity_as_username true

With this configuration mosquitto successfully authenticate connection on 8883. but when I try to connect MqTT client without security on port 18883 (with plain username and password) mosquitto fails and terminate with segmentation fault.

Please find the below log from mosquitto
############## MOSQUITTO LOG ###########

1498467121: mosquitto version 1.4.12 (build date 2017-06-26 03:17:35-0400) starting
1498467121: Config loaded from /home/{USER_NAME}/Documents/mosquitto/mymosquitto.conf.
1498467121: |-- *** auth-plug: startup
1498467121: |-- ** Configured order: mysql

1498467121: |-- }}}} MYSQL
1498467121: Opening ipv4 listen socket on port 8884.
1498467121: Opening ipv6 listen socket on port 8884.
1498467121: Opening ipv4 listen socket on port 8883.
1498467121: Opening ipv6 listen socket on port 8883.
1498467121: Opening ipv4 listen socket on port 1883.
1498467133: New connection from 10.1.1.167 on port 8883.
1498467133: |-- psk_key_get(hint1, ClientIdentity) from [mysql] finds PSK: 1
1498467133: New client connected from 10.1.1.167 as psk_client (c1, k60, u'ClientIdentity').
1498467133: Sending CONNACK to psk_client (0, 0)
1498467133: Received SUBSCRIBE from psk_client
1498467133: 	test_psk (QoS 0)
1498467133: psk_client 0 test_psk
1498467133: Sending SUBACK to psk_client
1498467140: Socket error on client psk_client, disconnecting.
**1498467143: New connection from 10.37.14.24 on port 1883.
1498467143: |-- mosquitto_auth_unpwd_check(testMqtt)
1498467143: |-- ** checking backend psk
Segmentation fault**

If I will compile mosquitto-auth-plug without BE_PSK flag, it can successfully authenticate mqtt connection on both port 1883 (without security) and 8884 (with x509).
And am I doing anything wrong?
Thank you in advance.

**Comment by jpmens** [comment]
Please verify with newer Mosquitto version, and feel free to reopen if issue persists.
