### ISSUE TITLE
Segmentation fault (core dumped) When pubslishing with the auth-plugin

### ISSUE THREAD

**Issue by kebsont** [jpmens/mosquitto-auth-plug#272]
Hi, 
I deployed my broker in my server, but when i try to publish, the broker crashes and If i subscribe, all is good.
mosquitto.conf
`#auth_plugin
auth_plugin /home/webadmin/company-project/mosquitto-auth-plug/mosquitto-1.3.5/a$
auth_opt_backends mysql
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname MyDBName
auth_opt_user root
auth_opt_pass MyPass
auth_opt_userquery SELECT password FROM core_mqtt_user WHERE email = '%s'
#auth_opt_superquery SELECT COUNT(*) FROM core_mqtt_user WHERE email = '%s' AND role=1
#auth_opt_aclquery SELECT topic FROM core_mqtt_acl WHERE (email='%s')
auth_opt_anonusername AnonymouS
auth_opt_mysql_opt_reconnect true
auth_opt_mysql_auto_connect true
`
In the side of my client, it says me : 
`778A3C58/config', ... (351 bytes))
 9:29:23 210971 (debug): MQTT : Client mosq/@ZO[70<dmrGhZko6XK received CONNACK
 9:29:23 211004 (info ): Succesfully connected to MQTT broker
 9:29:23 269477 (debug): MQTT : Client mosq/@ZO[70<dmrGhZko6XK received SUBACK
`
And in the broker side,
`webadmin@company-dev:~/company-project/mosquitto-auth-plug/mosquitto-1.3.5$ ./src/mosquitto -c mosquitto.conf 
1498721328: mosquitto version 1.3.5 (build date 2017-06-28 16:15:26+0000) starting
1498721328: Config loaded from mosquitto.conf.
1498721328: |-- *** auth-plug: startup
1498721328: |-- ** Configured order: mysql

1498721328: |-- }}}} MYSQL
1498721328: Opening ipv4 listen socket on port 8883.
1498721328: Opening ipv6 listen socket on port 8883.
1498721328: Opening ipv4 listen socket on port 1883.
1498721328: Opening ipv6 listen socket on port 1883.
1498721380: New connection from XX.XX.63.203 on port 8883.
1498721380: |-- mosquitto_auth_unpwd_check(user@company.net)
1498721380: |-- ** checking backend mysql
1498721380: |-- getuser(user@company.net) AUTHENTICATED=1 by mysql
1498721380: New client connected from XX.XX.63.203 as mosq/@ZO[70<dmrGhZko6XK (c1, k60, uuser@company.net).
Segmentation fault (core dumped)
webadmin@company-dev:~/company-project/mosquitto-auth-plug/mosquitto-1.3.5$`

**Comment by jasiek** [comment]
I'd look at the corefile with gdb to see where it blew up.

**Comment by kebsont** [comment]
And what do you find?

**Comment by jasiek** [comment]
Hopefully you'll be able to identify the line of code where it blows up.

**Comment by kebsont** [comment]
Actually it works just because i recommenced to zero. I did a make clean, make install, make, and compiled the plugin.

**Comment by jpmens** [comment]
This report was hopelessly useless.

**Comment by kebsont** [comment]
I don't receive any help from this issue, that's why i do that.

**Comment by jpmens** [comment]
You did receive help: two hours ago, @jasiek picked up this issue and started asking useful questions. Then you say you fixed it yourself, by redoing everything from scratch. Had you done that to start with you would have saved other people work. Most importantly you wouldn't have upset me.

And if you are complaining that it took six days for somebody to comment on your issue, then you have no idea at all how Open Source works: we haven't seen any money or help from you: you get what you pay for. Continuing in this tone will guarantee that you'll find zero help here in the future.

Have a good day.

**Comment by kebsont** [comment]
Ok thank u, i understand what you says. And sorry

**Comment by kebsont** [comment]
Ok thank u, i understand what you says. And sorry
Hv a gd day

**Comment by shahabmusic** [comment]
I get this error when my client tries to connect to server repeatedly with only 3seconds gap in between connection retries.
I don't know what GDB is and I have no idea about core files. I will do more research and publish my results once I had more info on this.
