### ISSUE TITLE
Disconnect client on Connection Refused: not authorised

### ISSUE THREAD

**Issue by ishrikanth** [jpmens/mosquitto-auth-plug#273]
Hi  @vinnyt, @jasiek, @jpmens, All

I have changed my source code
be-http.c
from 500 to 400 so that client gets disconnected.
`else if (re == CURLE_OK && respCode >= 400) {
			ok = BACKEND_ERROR;
}`
But still client is not getting disconnected. Even with server unreachable also its not terminating the client
Please let me know what could be the problem.

Client Log
Connection Refused: not authorised.
Connection Refused: not authorised.
Connection Refused: not authorised.
Connection Refused: not authorised.
Connection Refused: not authorised.
Connection Refused: not authorised.

**Comment by jpmens** [comment]
It is up to the client to disconnect.

**Comment by ishrikanth** [comment]
Normally when you use mosquitto_sub client, it does not disconnect and it keeps making the HTTP request or database query in a regular interval depending on auth provider which will increase the latency and affect the performance. Is there any configuration available to force disconnect on auth failure or connection refused?

**Comment by jpmens** [comment]
No, that's the way these utilities work.

**Comment by nikhilvs** [comment]
What's the purpose of authentication plugin, if broker doesn't disconnect on auth failure ?
Whole idea is to make sure, broker's resource is utilised for proper client's.

Please correct me if cam wrong!!

**Comment by jpmens** [comment]
Take a vanilla Mosquitto without authentication plugin and do your tests. 
Then come back here.

**Comment by ishrikanth** [comment]
@jpmens 

You mean to say its the limitation from the mosquitto side or the auth plugin side. If its auth plugin side. Is there a way where we can modify the source code?
