### ISSUE TITLE
Creating working hash in c#

### ISSUE THREAD

**Issue by mtalent** [jpmens/mosquitto-auth-plug#274]
I have been working for days trying to re-create the hash needed for the plug in using c#.  I need my users to be able to change/create their password with a mobile app written in c#.  I'll include what I have but it doesn't work.  

    private int SaltByteLength = 12
    private int DerivedKeyLength = 24

    public string CreatePasswordHash(string password)
    {

        var salt = GenerateRandomSalt();    
        var iterationCount = GetIterationCount();
        var hashValue = GenerateHashValue(password, salt, iterationCount);
        string result = "PBKDF2$sha256$" + iterationCount + "$" + Convert.ToBase64String(salt) + "$" + 
        Convert.ToBase64String(hashValue);
        return result;

    }

    private int GetIterationCount()
    {
        return 901;
    }

    private static byte[] GenerateRandomSalt()
    {
        var csprng = new RNGCryptoServiceProvider();
        var salt = new byte[SaltByteLength];
        csprng.GetBytes(salt);
        return salt;
        //return GetLetter();
    }

    private static byte[] GenerateHashValue(string password, byte[] salt, int iterationCount)
    {
         byte[] hashValue;
         var valueToHash = string.IsNullOrEmpty(password) ? string.Empty : password;
         using (var pbkdf2 = new Rfc2898DeriveBytes(valueToHash, salt, iterationCount))
         {
             hashValue = pbkdf2.GetBytes(DerivedKeyLength);
         }
        return hashValue;

    }

please help if you can ..... Also the plug in is great I have been working on this project for a while and I knew I was going to need a way to use a database for authentication and wasn't sure how hard it was going to be.  I really appreciate all the work you did to make this possible.

**Comment by jpmens** [comment]
I cannot help you with that, unfortunately. You'll have to find a standard PBKDF2 function for C#.

**Comment by mtalent** [comment]
After a few days of trying everything on the planet to get a C# sha256 pbkdf2 hashing algorithm that would work with the mosquitto-auth-plug I figured it out.  Code below will work if you make auth-plug.so with the -RAWSALT flag.   



    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Security.Cryptography;

    namespace Password
    {
        class Program
        {
            static void Main(string[] args)
            {
                while (true) // Loop indefinitely
                {
                    Console.Write("Enter Password (Exit to end): "); // Prompt
                    string line = Console.ReadLine(); // Get string from user
                    if (line == "exit") // Check string
                    {
                        break;
                    }
                    string password = CreatePasswordHash(line);

                    Console.Write("Hash = "); // Report output
                    Console.Write(password);
                    Console.WriteLine();
                
                }

            }


            private static string CreatePasswordHash(string password)
            {
    
                int iterationCount = 901;
                var salt = GenerateRandomSalt();
                var hashValue = GenerateHashValue(password, salt, iterationCount);
                string result = "PBKDF2$sha256$" + iterationCount + "$" + Convert.ToBase64String(salt) + "$" 
                + Convert.ToBase64String(hashValue);
                Array.Clear(salt, 0, salt.Length);
                Array.Clear(hashValue, 0, hashValue.Length);
                return result;

        }

        private static byte[] GenerateRandomSalt()
        {
            int SaltByteLength = 12;
            var csprng = new RNGCryptoServiceProvider();
            var salt = new byte[SaltByteLength];
            csprng.GetBytes(salt);
            return salt;
        }

        private static byte[] GenerateHashValue(string password, byte[] salt, int iterationCount)
        {


            int DerivedKeyLength = 24;
            var passwordBytes = System.Text.Encoding.UTF8.GetBytes(password);
            var hashedPassword = new byte[DerivedKeyLength];
            hashedPassword = PBKDF2Sha256GetBytes(DerivedKeyLength, passwordBytes, salt, iterationCount);
            return hashedPassword;

        }


        public static byte[] PBKDF2Sha256GetBytes(int dklen, byte[] password, byte[] salt, int iterationCount)
        {
            using (var hmac = new System.Security.Cryptography.HMACSHA256(password))
            {
                int hashLength = hmac.HashSize / 8;
                if ((hmac.HashSize & 7) != 0)
                    hashLength++;
                int keyLength = dklen / hashLength;
                if ((long)dklen > (0xFFFFFFFFL * hashLength) || dklen < 0)
                    throw new ArgumentOutOfRangeException("dklen");
                if (dklen % hashLength != 0)
                    keyLength++;
                byte[] extendedkey = new byte[salt.Length + 4];
                Buffer.BlockCopy(salt, 0, extendedkey, 0, salt.Length);
                using (var ms = new System.IO.MemoryStream())
                {
                    for (int i = 0; i < keyLength; i++)
                    {
                        extendedkey[salt.Length] = (byte)(((i + 1) >> 24) & 0xFF);
                        extendedkey[salt.Length + 1] = (byte)(((i + 1) >> 16) & 0xFF);
                        extendedkey[salt.Length + 2] = (byte)(((i + 1) >> 8) & 0xFF);
                        extendedkey[salt.Length + 3] = (byte)(((i + 1)) & 0xFF);
                        byte[] u = hmac.ComputeHash(extendedkey);
                        Array.Clear(extendedkey, salt.Length, 4);
                        byte[] f = u;
                        for (int j = 1; j < iterationCount; j++)
                        {
                            u = hmac.ComputeHash(u);
                            for (int k = 0; k < f.Length; k++)
                            {
                                f[k] ^= u[k];
                            }
                        }
                        ms.Write(f, 0, f.Length);
                        Array.Clear(u, 0, u.Length);
                        Array.Clear(f, 0, f.Length);
                    }
                    byte[] dk = new byte[dklen];
                    ms.Position = 0;
                    ms.Read(dk, 0, dklen);
                    ms.Position = 0;
                    for (long i = 0; i < ms.Length; i++)
                    {
                        ms.WriteByte(0);
                    }
                    Array.Clear(extendedkey, 0, extendedkey.Length);
                    return dk;
                }
            }




        }

	}
}

**Comment by jpmens** [comment]
Congratulations. If you turn this into a pull-request for something in `contrib/`, I'll take it -- maybe others can profit from your work.
