### ISSUE TITLE
File backend without reload ?

### ISSUE THREAD

**Issue by natcl** [jpmens/mosquitto-auth-plug#275]
Is it possible to update passwords/acl using the File backend without having to restart mosquitto ?

**Comment by jpmens** [comment]
That is currently not implemented, but it *would* be possible to add code to do so.

If somebody wants to implement this in `be-files.c`, I'd take a pull request.

**Comment by natcl** [comment]
The strategy would be to read the files at each ACL request ?

**Comment by jpmens** [comment]
That would be pretty suboptimal on a busy broker ...

No, the strategy ought to be to check stat(2) of file, see if mtime has changed, and if so, close/open the file.

**Comment by natcl** [comment]
Thanks, my C skills are pretty minimal but I'll pass along to my collegues !

**Comment by natcl** [comment]
Question: if I send a sighup to mosquitto will the files be reloaded ? That could also be a solution...

**Comment by jpmens** [comment]
If you look at mosquitto.conf manual page, it says about plugins: "Not currently reloaded on reload signal.", so no.

**Comment by jpmens** [comment]
Closing; feel free to reopen when you have code for us. :-)
