### ISSUE TITLE
sqLite authentication failure: Can't bind: bind or column index out of range, getuser() AUTHETICATED=0 by none

### ISSUE THREAD

**Issue by VauxAlexander** [jpmens/mosquitto-auth-plug#276]
I am currently implementing authentication using sqLite backend. I have created username: alexander and hashed password `PBKDF2$sha256$901$SuPQNHe56L/DAnTQ$mHgOmr+cyuF3GTK5vFHHWoXgBrydzwRX` using `./np`. The original password is "alexanderpwd".

MQTT broker was setup successfully: 
```
1499359619: Config loaded from /home/alexander/Workplace/mosquitto/pluginTest/mosquitto.conf.
1499359619: |-- *** auth-plug: startup
1499359619: |-- ** Configured order: sqlite

1499359619: Opening ipv4 listen socket on port 8883.
1499359619: Opening ipv6 listen socket on port 8883.
```

(Note: I dont think the file location of mosquitto.conf is a problem. I have successfully subscribe and publish using mosquitto-passwd).

However, when I tried to subscribe a topic, the error came in on broker: 
```
1499360764: New connection from 127.0.0.1 on port 8883.
1499360764: |-- mosquitto_auth_unpwd_check(alexander)
1499360764: |-- ** checking backend sqlite
1499360764: |-- Can't bind: bind or column index out of range
1499360764: |-- getuser(alexander) AUTHENTICATED=0 by none
```

My client looks like this:
```
mosquitto_sub -h 127.0.0.1 -p 8883 -t "gateway" --cafile ./ca.crt -u alexander -P alexanderpwd
Connection Refused: not authorised.
```

To clarify a little bit, my mosquitto.conf looks like this:

```
auth_plugin /home/alexander/Workplace/mosquitto/pluginTest/auth-plug.so
auth_opt_backends sqlite
auth_opt_dbpath /home/alexander/Workplace/mosquitto/pluginTest/test.db
auth_opt_sqliteuserquery SELECT pw FROM users WHERE username = '%s'
port 8883
allow_anonymous false
cafile /home/alexander/Workplace/mosquitto/pluginTest/ca.crt
certfile /home/alexander/Workplace/mosquitto/pluginTest/srv.crt
keyfile /home/alexander/Workplace/mosquitto/pluginTest/srv.key
```

I noticed someone had problem with `'%s'` since they used curly single quotation mark. But I typed out the single quotation mark and this should not be a problem.
The case is a little complex here since I tried to establish SSH connection. However, SSH is proven to work correctly. 

Please help me out! Any ideas is welcomed. =)

**Comment by VauxAlexander** [comment]
This is my test.db:
sqlite> .headers on
sqlite> SELECT * FROM users
   ...> ;
username|pw
alexander|PBKDF2$sha256$901$SuPQNHe56L/DAnTQ$mHgOmr+cyuF3GTK5vFHHWoXgBrydzwRX

**Comment by jpmens** [comment]
First of all, please learn to format github comments, particularly code using lines of three backticks as I've now done for you; it's incredibly helpful (to me at least) in reading code. :)

You need to remove the `%s` and replace by a single `?` which is the bind parameter. So:

```
SELECT pw FROM users WHERE username = ?
```

should work.

**Comment by VauxAlexander** [comment]
Thank you so much for your help.=) I definetely agree with you that proper formatting will improve readibility. I have done some changes myself. 
With changing to `?`, I can now subscribe to the broker. The matter should be resolved!
