### ISSUE TITLE
Using certificates for authentication

### ISSUE THREAD

**Issue by vedavidhbudimuri** [jpmens/mosquitto-auth-plug#277]
Does mosquitto-auth-plug support authentication by certificates instead of username and password?

Im actually trying to authenticate users using certificates and fetch the user details using the username the is given while generating the certificates.

**Comment by jpmens** [comment]
No, but depending on your client you may be able to use TLS-PSK which is supported by libmosquitto.

**Comment by vedavidhbudimuri** [comment]
Enabling both certificate related settings and mosquitto-auth-plug settings seem to work fine for the use case I mentioned. 
Thanks for the reply.

**Comment by Timester** [comment]
@vedavidhbudimuri How does it work in your case? I have a use case where I want to use client certificates for authentication and this plugin for applying ACLs from a database. Is this what you have done? I know that mosquitto will use the CN field from the client cert as a username, I was wondering if I set an empty password in the database (or an empty string hashed using the PBKDF2 format) for the user maybe I can circumvent the authentication part of the plugin.

**Comment by jpmens** [comment]
@Timester that _might_ not be necessary ... it's quite possible (untested) that Mosquitto will not invoke the `unpwd_check()` function to verify username/password when authenticating with a cert, but will then check the ACLs with the plugin function. It's worth testing.

**Comment by Timester** [comment]
@jpmens Thanks, I'll check it!

**Comment by Timester** [comment]
@jpmens You were right, works just fine. It looks like username / password based authentication is totally skipped if I use client certificates instead. Thanks!
