### ISSUE TITLE
Can not make the plugin file in centos 7

### ISSUE THREAD

**Issue by akshar001** [jpmens/mosquitto-auth-plug#284]
Selected backends:          MySQL
Using mosquitto source dir: /etc/mosquitto
OpenSSL install dir:        /usr/include/openssl

If you changed the backend selection, you might need to 'make clean' first

/bin/sh: mysql_config: command not found
CFLAGS:   -I/etc/mosquitto/src/ -I/etc/mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL   -I/src -DDEBUG=1 -I/usr/include/openssl/include
LDFLAGS:   -L/etc/mosquitto/lib/
/bin/sh: mysql_config: command not found
LDADD:     -L/usr/include/openssl/lib -lcrypto -lmosquitto

cc  -I/etc/mosquitto/src/ -I/etc/mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include/openssl/include   -c -o auth-plug.o auth-plug.c
/bin/sh: mysql_config: command not found
auth-plug.c:34:23: fatal error: mosquitto.h: No such file or directory
 #include <mosquitto.h>
                       ^
compilation terminated.
make: *** [auth-plug.o] Error 1

This is the error which i am getting...
Thank you

**Comment by akshar001** [comment]
Hello jpmens 
What you are doing is great. I Might be beginner in all this things but i need to implement this plugin very badly. I actually had installed mosquitto before and then i was trying to implement the plugin but as i came to know that it needs repo files i have used them so that error is gone. Now i had installed mysql before. But i am getting mysql.h not found. This isn't an issue. But i needed help so i have tried asking here. May be it is wasting your time but if you can help me set up your plugin it would be great thanks

**Comment by jpmens** [comment]
To build the plugin you need development packages for the components you are installing, e.g. mysel-dev or whatever it's called in your distribution.

**Comment by akshar001** [comment]
Thanks.
Sorry if am disturbing but for mysql where should i assign the path of the package after downloading it..

**Comment by akshar001** [comment]
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o auth-plug.o auth-plug.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o base64.o base64.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o pbkdf2-check.o pbkdf2-check.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o log.o log.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o envs.o envs.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o hash.o hash.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o be-psk.o be-psk.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o backends.o backends.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -c -o cache.o cache.c
cc  -I/root/mqtt/mosquitto-1.4.14/src/ -I/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror   -I/src -DDEBUG=1 -I/root/mqtt/openssl-1.0.2l/include   -L/root/mqtt/mosquitto-1.4.14/lib/ -fPIC -shared -o auth-plug.so auth-plug.o base64.o pbkdf2-check.o log.o envs.o hash.o be-psk.o backends.o cache.o   -L/root/mqtt/openssl-1.0.2l/lib -lcrypto -lmosquitto
/usr/bin/ld: cannot find -lmosquitto

i just tried saying mysql no and am getting this error

**Comment by jpmens** [comment]
You need libmosquitto-dev

**Comment by akshar001** [comment]
Thank you ver much

**Comment by akshar001** [comment]
I cant install  libmosquitto-dev
have tried but i have already installed mosquitto package from yum so files are getting conflicted!
Sorry

**Comment by akshar001** [comment]
Hello
Thanks for your info as it turned out there is one error is showing 
/bin/sh: mysql_config: command not found
CFLAGS:   -I../org.eclipse.mosquitto//src/ -I../org.eclipse.mosquitto//lib/ -fPIC -Wall -Werror  -DBE_MYSQL   -I/src -DDEBUG=1 -I/usr/include
LDFLAGS:   -L../org.eclipse.mosquitto//lib/
/bin/sh: mysql_config: command not found
LDADD:     -L/usr/lib -lcrypto -lmosquitto

cc  -I../org.eclipse.mosquitto//src/ -I../org.eclipse.mosquitto//lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
/bin/sh: mysql_config: command not found
In file included from auth-plug.c:54:0:
be-mysql.h:32:19: fatal error: mysql.h: No such file or directory
 #include <mysql.h>
                   ^
compilation terminated.

i have tried installing both mysql client and server library if there is anything else that can help me to install.?

**Comment by akshar001** [comment]
as it turned out i tried yum install mysql++-devel.x86_64 and it go well
Thanks
