### ISSUE TITLE
Fallback mechanism if back-end goes down.

### ISSUE THREAD

**Issue by sachingupta141** [jpmens/mosquitto-auth-plug#289]
Hi,

I am using mosquitto version 1.4.12 with mosquitto-auth-plug to do authentication and authorization.
I am using Redis as back-end. Authentication and authorization is working fine.

But I am wondering, if there is any fallback mechanism available, if back-end goes down.
Currently, whenever it goes down, it starts to deny authentication requests

**Comment by jpmens** [comment]
No, we don't have fallback mechanisms.
