### ISSUE TITLE
How to use redis as a backend for mosquitto ACL

### ISSUE THREAD

**Issue by AdnateIOT** [jpmens/mosquitto-auth-plug#295]
I am working on Mosquitto and plan to use Redis as the back end to  handle both username/password pair authentication and ACL. I am using  JPmens' authentication plugin to do this.
 mosquitto conf:
 **auth_opt_backends redis
 auth_plugin /etc/mosquitto/auth-plug.so
 auth_opt_redis_host 127.0.0.1 
 auth_opt_redis_port 6379 
 auth_opt_redis_userquery GET %s 
 auth_opt_redis_aclquery GET %s-%s** 
 Following name/password pairs are working fine for the authentication  
**SET user1 PBKDF2$sha256$901$Qh18ysY4wstXoHhk$g8d2aDzbz3rYztvJiO3dsV698jzECxSg** 
 Following settings won't work for the ACL: 
 **SET user1-test 2**  
Following are the logs of mosquitto :  
1507037072: Denied PUBLISH from mosqpub/3838-ip-172-31- (d0, q0, r0, m0, 'user1-test', ... (4 bytes)) 1507037072: Received DISCONNECT from mosqpub/3838-ip-172-31-  So, whenever I try to pub/sub mosquitto authenticate the user but didn't allow for publishing and disconnect the user.  
Testing with:  
**mosquitto_pub -p 1884 -t "test" -m "demo" -u user1 -P xyz**   
for sub: 
 **mosquitto_sub -p 1884 -t "test" -u user1 -P xyz**

**Comment by btry** [comment]
Hi

Is this your question ?

https://stackoverflow.com/questions/46557609/how-to-use-redis-as-a-backend-for-mosquitto-acl/46570011#46570011

It seems interesting to document here too the explanation of the issue.
