### ISSUE TITLE
Mosquitto broker stop working when user is deleted from MySql DB

### ISSUE THREAD

**Issue by stzoran1** [jpmens/mosquitto-auth-plug#302]
I have installed mosquitto_auth_plugin and during testing I noticed that Mosquitto broker became unresponsive 2-5 seconds after I delete user from DB. All users loose connections and I have to restart mosquitto service manually in order to continue.
I am using Centos 7, mosquitto 1.4.14, latest version of your plugin and MariaDb 10.2.9.
Do you know how to solve this problem? Is this a possible bug or there are some steps I have to follow when deleting users from DB?

Thank you in advance.

**Comment by jpmens** [comment]
Please show me exactly how to reproduce this using Mosquitto 1.5.4 (current version) and the current auth-plugin.
