### ISSUE TITLE
Old version of config.mk prevents hash checking from working properly

### ISSUE THREAD

**Issue by sfowlr** [jpmens/mosquitto-auth-plug#303]
Commit 6c72a55 added support for Django hashing algorithm, but the way it was implemented in the makefile requires the following line to be added to the config.mk:
`SUPPORT_DJANGO_HASHERS ?= no`
Since config.mk isn't version controlled, this change in the template easily goes unnoticed. 

If 'no' isn't explicitly stated, the build succeeds but will never properly authenticate any users. 
Can a default 'no' be added in the makefile, so more people don't have to pull their hair out wondering why their plugin no longer works after fetching the latest source and rebuilding?

**Comment by jpmens** [comment]
You're right. Can you create a pull-request for this?

**Comment by jpmens** [comment]
Closed via https://github.com/jpmens/mosquitto-auth-plug/pull/307
