### ISSUE TITLE
Add possibility of returning topics with wildcards with HTTP just like with MYSQL

### ISSUE THREAD

**Issue by Gussoh** [jpmens/mosquitto-auth-plug#306]
Hi,

Currently I'm trying to avoid using the HTTP backend since it creates a lot of queries for each publish and subscribe. The MYSQL backend seems much more efficient since I can just return a topic wildcard such as sensor/x/#. It would be great if there was a way to do the same thing with the HTTP backend.

Thanks for a great plugin!

**Comment by rgaufman** [comment]
Did you ever find a solution to this?

**Comment by Gussoh** [comment]
No. Not yet.

**Comment by jpmens** [comment]
If somebody provides code for this, we will accept it.
