### ISSUE TITLE
Possible memory leak in get_string_envs

### ISSUE THREAD

**Issue by oh5fsz** [jpmens/mosquitto-auth-plug#310]
In be-http.c line 66 the following for-loop is run:
```
	for( i = 0; i < num; i++ ){
		escaped_key = curl_easy_escape(curl, params_key[i], 0);
		escaped_val = curl_easy_escape(curl, env_value[i], 0);

		//_log(LOG_DEBUG, "key=%s", params_key[i]);
		//_log(LOG_DEBUG, "escaped_key=%s", escaped_key);
		//_log(LOG_DEBUG, "escaped_val=%s", escaped_envvalue);

		data = (char *)malloc(strlen(escaped_key) + strlen(escaped_val) + 1);
		if ( data == NULL ) {
			_fatal("ENOMEM");
			return (-1);
		}
		sprintf(data, "%s=%s&", escaped_key, escaped_val);
		if ( i == 0 ) {
			sprintf(querystring, "%s", data);
		} else {
			strcat(querystring, data);
		}
	}
```

In the end of the function, there's only a single call to `free(data)`. If the for loop runs multiple times (num > 1), the malloc is ran multiple times but only the last block of memory will be freed.

**Comment by jpmens** [comment]
@oh5fsz thank you for the report. I've pushed a patch which should address this.

To be honest, large parts of this file should be rewritten from scratch. I accepted it at the time but I should have completely cleaned this up. If anybody's up for it, I'll gladly accept a PR.

**Comment by kipe** [comment]
Hmm, actually... Doesn't the same issue also affect `escaped_key` and `escaped_val`?

Judging by the example at https://curl.haxx.se/libcurl/c/curl_easy_escape.html there's also a special function `curl_free` for freeing those...
