### ISSUE TITLE
SSL secured connection to database(mysql) 

### ISSUE THREAD

**Issue by bag0enth** [jpmens/mosquitto-auth-plug#312]
Hi jpmens, 

great project, thank you very much for sharing it! 

I have a question concering the connection between the auth-plugin and the database (in my case mysql) containing the acl and usertable. Isn't the connection SSL secured? I am asking because there is no possibility to enable/disable ssl or to specify a certificate file. 

Best regards,
Bastian

**Comment by jpmens** [comment]
Looking at the code in be-mysql.c I don't see anything which does TLS.  If you need that it would be an enhancement (and probably a welcome one).

**Comment by bag0enth** [comment]
Added SSL support to "be_mysql.c"
[be-mysql.zip](https://github.com/jpmens/mosquitto-auth-plug/files/1556069/be-mysql.zip)

Settings in mosquitto.conf:
auth_opt_ssl_enabled true --> If this line is not there, SSL is disabled
auth_opt_ssl_key /path/to/file
auth_opt_ssl_cert /path/to/file
auth_opt_ssl_ca /path/to/file
auth_opt_ssl_capath /path/to/file
auth_opt_ssl_cipher /path/to/file

**Comment by jpmens** [comment]
It's quite unusual to provide a patch this way. If you're not able to create a proper pull request I'll take it probably, but do you want to reconsider? It's not difficult to do :-)

**Comment by bag0enth** [comment]
Sorry I am new to GitHub, hope I have done it correct now :)

**Comment by jpmens** [comment]
Excellent, thank you. I have merged https://github.com/jpmens/mosquitto-auth-plug/pull/313 just now (travelling at 200 km/h in a train: the wonderful world in which we live today; of sorts).

Thank you for your contribution.

**Comment by bag0enth** [comment]
Klingt ganz nach einem ICE :)

**Comment by jpmens** [comment]
ICE 90.
