### ISSUE TITLE
Build Failed when using "old" config.mk (without BACKEND_MEMCACHED option)

### ISSUE THREAD

**Issue by otavioarrudasantos** [jpmens/mosquitto-auth-plug#317]
I was using an "old" config.mk file obtained when the MEMCACHED backend wasn't available.
So today I cloned the repo and during the build process (with this config.mk file) it gave me this error message:
> make[1]: Leaving directory '/home/mqtt/mosquitto-auth-plug/contrib/tinycdb-0.78'
> Selected backends:          Memcached HTTP
> Using mosquitto source dir: /home/mqtt/mosquitto-1.4.14
> OpenSSL install dir:        /usr
> 
> If you changed the backend selection, you might need to 'make clean' first
> 
> CFLAGS:   -I/home/mqtt/mosquitto-1.4.14/src/ -I/home/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror  -DBE_MEMCACHED -DBE_HTTP  -I/usr/local/include/libmemcached -I/src -DDEBUG=1 -I/usr/include
> LDFLAGS:   -L/usr/local/lib -L/home/mqtt/mosquitto-1.4.14/lib/
> LDADD:    -lmemcached -lcurl -L/usr/lib -lcrypto -lmosquitto
> 
> cc  -I/home/mqtt/mosquitto-1.4.14/src/ -I/home/mqtt/mosquitto-1.4.14/lib/ -fPIC -Wall -Werror  -DBE_MEMCACHED -DBE_HTTP  -I/usr/local/include/libmemcached -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
> auth-plug.c: In function 'mosquitto_auth_plugin_init':
> auth-plug.c:347:20: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]                                                                                    
>     (*bep)->getuser =  be_memcached_getuser;                                                                                                                                                 
>                     ^                                                                                                                                                                        
> cc1: all warnings being treated as errors                                                                                                                                                    
> make: *** [auth-plug.o] Error 1                                                                                                                                                              
> <builtin>: recipe for target 'auth-plug.o' failed

So, after trying to find out why this happened, I came here em noticed that the new Backend with Memcached is available.

After adding this line to the config.mk, the build succedded:

> BACKEND_MEMCACHED ?= no

There is a bug in the build process when all available backends aren't defined in the config.mk file?
Even I have defined HTTP as the backend, in the build process the MEMCACHED was selected.

Here is the zip file containing the new and old config.mk files for checkings. [new_and_old_config.mk.zip](https://github.com/jpmens/mosquitto-auth-plug/files/1576536/new_and_old_config.mk.zip)

--
Thank you for the excellent job.

**Comment by CloCkWeRX** [comment]
Fixed in febe59127d5e047227066173a1f84466dcee2ba7
