### ISSUE TITLE
Error: Unable to load auth plugin "/usr/lib/auth-plug.so"

### ISSUE THREAD

**Issue by gallog** [jpmens/mosquitto-auth-plug#33]
Hi,
I've a problem running your library on a x86 machine:

./mosquitto -c mosquitto.conf1412605004: mosquitto version 1.3.4 (build date 2014-10-06 16:14:36+0200) starting
1412605004: Config loaded from mosquitto.conf.
1412605004: Error: Unable to load auth plugin "/usr/lib/auth-plug.so".

I've succesfully compiled the library without modify your makefile (I've only changed the MOSQUITTO_SRC) and moved to /usr/lib/auth.plugin.so.

I'm using mosquitto 1.3.4 compiled by myself and here is my mosquitto.conf:

autosave_interval 1800
connection_messages true
log_timestamp true
listener 1883
auth_plugin /usr/lib/auth-plug.so
auth_opt_backends mysql
auth_opt_host 127.0.0.1
auth_opt_port 3306
auth_opt_dbname mqtt
auth_opt_user mqttauth
auth_opt_pass mqttauthpassword
auth_opt_userquery SELECT password FROM USERS WHERE id_user = %s
auth_opt_superquery SELECT IFNULL(COUNT(_), 0) FROM USERS WHERE id_user = %s AND superuser = 1
auth_opt_superusers S_

**Comment by hkverma310** [comment]
Access denied for user 'info24'@'localhost' (using password: NO)
i am getting the above error

**Comment by jpmens** [comment]
Why are you commenting on a closed issue with something that has nothing to do with the original issue?! The plugin isn't allowed to connect to mysql. are you sure `root` is your db password?

**Comment by hkverma310** [comment]
yeah my db password is root

**Comment by mahesh21** [comment]
I have changed WITH_SRV:=no and recompiled both mosquitto and mqtt-auth-plugin. I am getting the below error.
 
./mosquitto -c ../local.conf 
1457697662: mosquitto version 1.4.8 (build date 2016-03-11 03:59:19-0800) starting
1457697662: Config loaded from ../local.conf.
1457697662: |-- *** auth-plug: startup
|-- No backends configured.
|-- *** ABORT.
