### ISSUE TITLE
build error for BACKEND_MEMCACHED=yes

### ISSUE THREAD

**Issue by alteholz** [jpmens/mosquitto-auth-plug#335]
Issue #317 was closed after just defining "BACKEND_MEMCACHED ?= no" in config.mk.

But in case you really want to use BACKEND_MEMCACHED, the issue will reappear. be_memcached_getuser() returns a char*, whereas f_getuser in backends.h expects an int here. 

All other backends except MEMCACHED and PSK do return the correct type.

  Thorsten

**Comment by jpmens** [comment]
Tracking in #336
