### ISSUE TITLE
authentication plugins for mosquitto?

### ISSUE THREAD

**Issue by pokal4u** [jpmens/mosquitto-auth-plug#337]
Hi,
Please suggest me which authentication plugin  for mosquitto is secure and less load on server?
Plugins:
Mysql, Redis, Mongodb and Files
Thanks

**Comment by karan6190** [comment]
Hey,
You can go for MongoDB.
Redis - Data is stored on RAM, backed up to the HDD/SSD of the server, RAM is a lot faster than HDDs or SSDs, but is also more expensive when it comes to large amounts of data. Servers with 20GB Ram would cost a lot more than a server with a 20GB SSD.

Mongo - Data stored on HDD/SSD, can hold as much data as you have storage space but is slightly slower than Redis

If you have a large forum then Mongo would likely be the best solution if you're just starting out, then Redis is better supported here, as more of us use it. You can technically use both.
If we talk about performance- for small no of user say 10k or 20k, both the DB will provide you with the same performance, but if talk about large data set of the user then mongo is a bit slower than Redis.
For Redis, you will have to set another DB for Authentication and Authorization.
