### ISSUE TITLE
Fixes due after Mosquitto 1.5 is fully integrated

### ISSUE THREAD

**Issue by jpmens** [jpmens/mosquitto-auth-plug#344]
Via #343:

- The hash which provide association with client to username is never purged and will grow forever.
- Client is added to the hash even if it will be rejected, which may be useless.
- clientid is no longer available to ACL check
- PSK authenticated client are probably not working

**Comment by kainosnoema** [comment]
These issues are preventing us from upgrading to mosquitto 1.5. Are you accepting PRs to wrap some of these up (first three especially)?

**Comment by jpmens** [comment]
In how far are the first two preventing your upgrade?

Other than that, I would surely accept PRs which address and fix these issues.

**Comment by jpmens** [comment]
Closing for lack of response.
