### ISSUE TITLE
Save user credentials in MongoDb in nested object

### ISSUE THREAD

**Issue by karlTGA** [jpmens/mosquitto-auth-plug#347]
Is there a way to store the credentials of every mqtt user in a nested object in the mongo document?
I want to store the information like this: 
```json
"mqtt" : {
		"password" : "*******",
		"superuser" : true,
		"topics" : {
			"public/#" : "r"
		},
		"username" : "username_mqtt"
}
```
I tried entrys in the mosquitto.conf like this:
`auth_opt_mongo_user_username_prop mqtt.username`

But that does not seem to work.

**Comment by jpmens** [comment]
That doesn't appear to be possible.
