### ISSUE TITLE
Incorrect plugin version  

### ISSUE THREAD

**Issue by cocoabox** [jpmens/mosquitto-auth-plug#353]
Hi, 
I am running Raspbian release 9 on a raspberry pi board.

I have installed all required dependencies (including libwebsockets),  checked out mosquitto (```d8dc336c2```) and mosquitto-auth-plug (```d15aeb80e8```), built mosquitto with ```cmake``` followed by ```make all``` and installed successfully.

I have then modified ```config.mk``` in the auth plugin source to enable HTTP, ``` make clean && make all```. 
here is my ```mosquitto-auth-plug/config.mk```:
```# Select your backends from this list
BACKEND_CDB ?= no
BACKEND_MYSQL ?= no
BACKEND_SQLITE ?= no
BACKEND_REDIS ?= no
BACKEND_POSTGRES ?= no
BACKEND_LDAP ?= no
BACKEND_HTTP ?= yes
BACKEND_JWT ?= no
BACKEND_MONGO ?= no
BACKEND_FILES ?= no
BACKEND_MEMCACHED ?= no

# Specify the path to the Mosquitto sources here
MOSQUITTO_SRC = /src/mqtt/mosquitto

# Specify the path the OpenSSL here
OPENSSLDIR = /usr

# Add support for django hashers algorithm name
SUPPORT_DJANGO_HASHERS ?= no

# Specify optional/additional linker/compiler flags here
# On macOS, add
#	CFG_LDFLAGS = -undefined dynamic_lookup
# as described in https://github.com/eclipse/mosquitto/issues/244
#
# CFG_LDFLAGS = -undefined dynamic_lookup  -L/usr/local/Cellar/openssl/1.0.2l/lib
# CFG_CFLAGS = -I/usr/local/Cellar/openssl/1.0.2l/include -I/usr/local/Cellar/mosquitto/1.4.12/include
CFG_LDFLAGS =
CFG_CFLAGS =
```
I put copied the generated ```auth-plug.so``` in my mosquitto source (build) dir.

I have referenced ```auth-plug.so``` in my ```/etc/mosquitto/conf.d/wss.conf``` as follows:
```
listener 8881
protocol websockets

# has to be a cert-chain file
cafile   /etc/mosquitto/certs/ca-cert-chain.pem
keyfile  /etc/mosquitto/certs/server-key-nopass.pem
certfile /etc/mosquitto/certs/server-cert.pem

allow_anonymous false

auth_plugin /src/mqtt/mosquitto/auth-plug.so
auth_opt_backends http
auth_opt_http_ip 127.0.0.1
auth_opt_http_port 8088
auth_opt_http_getuser_uri /__getuser__
auth_opt_http_superuser_uri /__superuser__
#auth_opt_http_aclcheck_uri /__aclcheck__
```

However, when I restarted mosquitto, mosquitto complained ```Error: Incorrect auth plugin version (got 3, expected 2)```. Is there anything else that has to be done in the build process? Many thanks,

**Comment by leoncool** [comment]
anyone please? I am also facing this issue.

**Comment by cocoabox** [comment]
This is what I ended up doing:
First: (most important) install libwebsocket 2.0
1. remove libwebsocket3 : `sudo apt-get remove libwebsockets3`
2. download libwebsocket 2.0.2 from : https://github.com/warmcat/libwebsockets/
```
curl -L https://github.com/warmcat/libwebsockets/archive/v2.0.2.tar.gz | tar xvzf -
cd libwebsockets-2.0.2/
```

3. since this won't build, modify the CMakeList.txt and create make file
```
mv CMakeLists.txt CMakeLists.txt.bak
sed -e 's/\-Wall/-Wno-error/g' < CMakeLists.txt.bak > CMakeLists.txt
mkdir build
cd build
cmake .. -DOPENSSL_ROOT_DIR=/usr/bin/openssl
```
4. make and install
```
make && sudo make install && sudo ldconfig
```
5. make sure 2.0.2 is installed
```pkg-config libwebsockets --modversion```

Then install mosquitto (commit `bda989371312780cc544ee246b107d3b42afa669`) with the following changes in config.mk
```
-WITH_WEBSOCKETS:=no
+WITH_WEBSOCKETS:=yes
```
and
```
-WITH_DOCS:=yes
+WITH_DOCS:=no
```
Then make and install.

Finally, install mosquitto auth plug (commit `d15aeb80e80669b5dbb0ff8ae0158fc976ff1c57`)

I hope this helps

**Comment by vishuPPatel** [comment]
I face same issue.anybody know how to fix-it???

**Comment by niravtrivedi21** [comment]
I face same problem so please let me know how to fix it ..
Thanks ..
