### ISSUE TITLE
mosquitto1.5 subscribe uses MOSQ_ACL_SUBSCRIBE

### ISSUE THREAD

**Issue by dmwhw** [jpmens/mosquitto-auth-plug#356]
the new version  of mosquitto add new flag MOSQ_ACL_SUBSCRIBE. now i find that the auth-plug has no implement about MOSQ_ACL_SUBSCRIBE,which leads to MOSQ_ERR_ACL_DENIED via mosquitto_auth_acl_check()

```
/*
 * Function: mosquitto_auth_acl_check
 *
 * Called by the broker when topic access must be checked. access will be one
 * of:
 *  **_MOSQ_ACL_SUBSCRIBE_** when a client is asking to subscribe to a topic string.
 *                     This differs from MOSQ_ACL_READ in that it allows you to
 *                     deny access to topic strings rather than by pattern. For
 *                     example, you may use MOSQ_ACL_SUBSCRIBE to deny
 *                     subscriptions to '#', but allow all topics in
 *                     MOSQ_ACL_READ. This allows clients to subscribe to any
 *                     topic they want, but not discover what topics are in use
 *                     on the server.
 *  MOSQ_ACL_READ      when a message is about to be sent to a client (i.e. whether
 *                     it can read that topic or not).
 *  MOSQ_ACL_WRITE     when a message has been received from a client (i.e. whether
 *                     it can write to that topic or not).
 *
 * Return:
 *	MOSQ_ERR_SUCCESS if access was granted.
 *	MOSQ_ERR_ACL_DENIED if access was not granted.
 *	MOSQ_ERR_UNKNOWN for an application specific error.
 *	MOSQ_ERR_PLUGIN_DEFER if your plugin does not wish to handle this check.
 */
int mosquitto_auth_acl_check(void *user_data, int access, const struct mosquitto *client, const struct mosquitto_acl_msg *msg);
```

**Comment by gcc-tan** [comment]
I found the same problem. I completely followed the documents to configure, but the access was denied. I added logs in some places in auth-plug, mainly printing access flags and acl query SQL statements(in the be-mysql.c, be_mysql_aclcheck function).


log :

1540070941: |-- acc is 4
1540070941: |-- SQL: SELECT topic FROM acls WHERE (username = 'jjolie') AND (rw >= 4)

And **MOSQ_ACL_SUBSCRIBE is 0x04**

**Comment by dmwhw** [comment]
> I found the same problem. I completely followed the documents to configure, but the access was denied. I added logs in some places in auth-plug, mainly printing access flags and acl query SQL statements(in the be-mysql.c, be_mysql_aclcheck function).
> 
> log :
> 
> 1540070941: |-- acc is 4
> 1540070941: |-- SQL: SELECT topic FROM acls WHERE (username = 'jjolie') AND (rw >= 4)
> 
> And **MOSQ_ACL_SUBSCRIBE is 0x04**

Do not use mosquitto 1.5. I found mosquitto-1.5  integrated with this plugin may lead to program crash.

**Comment by mikumaycry** [comment]
These marco can be found in mosquitto_plugin.h in mosquitto 1.5.3
```
#define MOSQ_ACL_NONE 0x00
#define MOSQ_ACL_READ 0x01
#define MOSQ_ACL_WRITE 0x02
#define MOSQ_ACL_SUBSCRIBE 0x04
```
The rw flag in database should also change from 0~3 to [0,1,2,4]

**Comment by curzon01** [comment]
The ACL should be treated as a bitmask, also for mosquitto &lt; 1.5 because older mosquitto too uses a distinguish between 'read' and 'write' and a combination of them - 'readwrite'. 

The bits are:
```
READ: 0x01
WRITE: 0x02
```
I can set an ACL for 'read' (1), for 'write' (2) and for 'readwrite' (3) using older mosquitto too. For example a user having 'write' access do not have 'read' permission so %d=2 is not the same as  %d=3.

To consider that my SQL statement for `auth_opt_aclquery` is:
`auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw & %d)`

A possible description for %d in ACL query should be:
> ...and a single '%d' is replaced with the integer value having bit 0 set (=1) for 'read', bit 1 set (=2) for 'write', and bit 0 and 1 set (=3) for 'readwrite':
```
0: no access (NULL)
1: read access (r)
2: write access (w)
3: read and write access (rw)
```

As since mosquitto 1.5 has implemented an additonal bit 3 (=4) we now have (in theory) for all combinations values form 0-7:
```
0: no access (NULL)
1: read access (r)
2: write access (w)
3: read and write access (rw)
4: subscribe access (s)
5: read & subscribe access (rs)
6: write & subscribe access (ws)
7: read, write and subscribe access (rws)
```
To be backward compatible with user definition in mosquitto &lt; 1.5 you simply need to add value 4 in user acl list.


But this is not the whole story:
The enhancement within mosquitto-auth-plug is if bit 2 is set (SUBSCRIBE = value 4) in acl _without_ having bit 0 set (READ = value 1) the topic is not allowed containing '+' or '#'.

**Comment by curzon01** [comment]
The issue can be solved by changing the SQL queries.

The queries below consider the new flag MOSQ_ACL_SUBSCRIBE in mosquitto &gt;= 1.5 and is backward compatible to mosquitto 1.4.

### MySQL

For MySQL the aclquery should be (tested)
```sql
SELECT topic FROM acls WHERE (username = '%s') AND (rw & %d) AND ( NOT (topic REGEXP '[+#]') OR (rw & 1) )
```
Mosquitto (partly) configuration for the `mysql` back-end:
```
...
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw & %d) AND ( NOT (topic REGEXP '[+#]') OR (rw & 1) )
...
```

### PostgreSQL

For PostgreSQL the aclquery should be (untested)
```sql
SELECT topic FROM acls WHERE (username = $1) AND (rw & $2) AND ((topic NOT SIMILAR TO '%(+|#)%') OR (rw & 1) )
```
Mosquitto (partly) configuration for the `postgres` back-end:
```
...
auth_opt_aclquery SELECT topic FROM acls WHERE (username = $1) AND (rw & $2) AND ((topic NOT SIMILAR TO '%(+|#)%') OR (rw & 1) )
...
```
