### ISSUE TITLE
Error in match version

### ISSUE THREAD

**Issue by iranappo** [jpmens/mosquitto-auth-plug#358]
Hi
I have below error
1531577739: Error: Incorrect auth plugin version (got 3, expected 2)
My mosquitto version is 1.4

**Comment by vishuPPatel** [comment]
I face same issue..!!1

**Comment by jpmens** [comment]
You are running the plugin against an older Mosquitto version; ensure both match, e.g. current auth plugin with Mosquitto 1.5.x
