### ISSUE TITLE
Make Error: fatal error: mosquitto_plugin.h: No such file or directory

### ISSUE THREAD

**Issue by mntolia** [jpmens/mosquitto-auth-plug#362]
Hi,
I am trying to install mosquitto auth plugin but I am getting this error:
Selected backends:          MySQL
Using mosquitto source dir: 
OpenSSL install dir:        /usr

If you changed the backend selection, you might need to 'make clean' first

```
/bin/sh: 1: mysql_config: not found
CFLAGS:   -I/src/ -I/lib/ -fPIC -Wall -Werror  -DBE_MYSQL   -I/src -DDEBUG=1 -I/usr/include
LDFLAGS:   -L/lib/
/bin/sh: 1: mysql_config: not found
LDADD:     -L/usr/lib -lcrypto -lmosquitto

cc  -I/src/ -I/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
/bin/sh: 1: mysql_config: not found
auth-plug.c:35:30: fatal error: mosquitto_plugin.h: No such file or directory
 #include <mosquitto_plugin.h>
                              ^
compilation terminated.
<builtin>: recipe for target 'auth-plug.o' failed
make: *** [auth-plug.o] Error 1
```

I tried on Rasbian & Ubuntu 17. I got the exact same error.
I have installed mosquitto, libmosquitto-dev & openSSL.
I am using mosquitto version 1.4.8
I tried searching for the file manually but I got no result.

What am I doing wrong?

BTW Thank you for this plugin!

**Comment by devorrah** [comment]
did you find a solution? I'm getting similar errors when trying to compile the plugin.
