### ISSUE TITLE
When adding auth-* lines into mosquitto.conf I get "Socket error on client <any client>, disconnecting.

### ISSUE THREAD

**Issue by euquiq** [jpmens/mosquitto-auth-plug#364]
HI there ... I am baffled by this:

I already had mosquitto running on my Centos 7.5 server and now I decided to both update my mosquitto version (as I was using earlier 1.4.x) and try out this plugin, since I could really use mysql as backend for authenticating users in an ongoing project of mine.

So, I downloaded the source code for mosquitto 1.5.1 and compiled it.

I tried it with my old mosquitto.conf and  passwd file, and it worked fine.

 Now, I Downloaded auth-plug source, set mysql as backend, pointed the MOSQUITTO_SRC into the source code I used earlier to compile my new mosquitto 1.5.1, compiled it and copied the resulting auth-plug.so into /etc/mosquitto/.

Of course, I added the needed config lines into my mosquitto.conf
I also commented out the path into the passwd file, since I would not need it any more ...

PROBLEM:  Each client connection is closed immediately after being ok'd by the auth-plug.so.

```
[root@virtualmin01 mosquitto-1.5.1]# /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
1537132016: mosquitto version 1.5.1 starting
1537132016: Config loaded from /etc/mosquitto/mosquitto.conf.
1537132016: |-- *** auth-plug: startup
1537132016: |-- ** Configured order: mysql

1537132016: |-- }}}} MYSQL
1537132016: |-- SSL is disabled
1537132016: Opening ipv4 listen socket on port 1883.
1537132016: Opening ipv6 listen socket on port 1883.
1537132016: Opening ipv4 listen socket on port 8883.
1537132016: Opening ipv6 listen socket on port 8883.
1537132019: |-- mosquitto_auth_unpwd_check(<a valid userid here>)
1537132019: |-- ** checking backend mysql
1537132019: |-- getuser(<a valid userid here>) AUTHENTICATED=1 by mysql
1537132019: New client connected from <My ipv4 address> as A-ZY223TDJZ4 (c1, k60, u'<a valid userid here>').
1537132019: No will message specified.
1537132019: Sending CONNACK to A-ZY223TDJZ4 (0, 0)
1537132019: Received SUBSCRIBE from A-ZY223TDJZ4
1537132019: 	<my valid topic here> (QoS 0)
1537132019: |-- mosquitto_auth_acl_check(..., client id not available, <a valid userid here>, AV/013227000039614, MOSQ_ACL_WRITE)
1537132019: |-- aclcheck(<a valid userid here>, <my valid topic here>, 4) AUTHORIZED=0 by none
1537132019: |--  Cached  [90F880DD9783EC6C1B1DDA463C80F76A07B704FD] for (client id not available,<a valid userid here>,4)
1537132019: Sending SUBACK to A-ZY223TDJZ4
1537132019: Socket error on client A-ZY223TDJZ4, disconnecting.
```

Please notice how the plugin validates the user, and the user proceeds to subscribe to a topic, so  there are actually some  ConACK, sub ACK, Pub ACK, etc packets going up and down, inside the first second, only to be closed with the socket error.

I uncommented the passwd file into the mosquitto.conf in order to try authenticating the users thorugh that "hardwired method" and I get the same thing: Clients get authenticated, etc. but RIGHT then there is the Socket error on each client, thus disconnecting them.

Then I proceed to COMMENT (with # at the beginning) each auth_  * related line inside mosquitto.conf  and although I loose the ability to get my users authenticated by this plugin, the users I got "hardcoded" on my old passwd file start working again.

So, AFAIK, there is something inside auth-plug.so which is causing the "SOCKET ERROR".

Any idea or help is well appreciated. Sorry if solution is obvious, I am learning!

Enrique

**Comment by euquiq** [comment]
As a Follow up to this, as far as I could read, this current version of AUTH-PLUGIN won't work with mosquitto 1.5.x ... it works only up to older 1.4.15 version.

**Comment by jpmens** [comment]
Thank you for your clear report, and I'm sorry you're experiencing problems.

I see @kainosnoema reported similar issues in #344 and I was hoping to receive the PRs he spoke of; I wonder if we should wait a bit for those?

**Comment by euquiq** [comment]
@jpmens no, please, thank you for your work! This plugin is a life saver for my ongoing project. Your work is really appreciated.

I got another question about the plugin: I am trying to use ACLs on my MySQL, with the 

```SELECT topic FROM acls WHERE (username = '%s') AND (rw >= %d)````

I need some topics to be READ ONLY and others to be WRITE ONLY. 

As I understand it, you only contemplate READ, and READ/WRITE ... but left out WRITE (only).

Could you please consider adding this possibility ? Also, is there any way to repay you for your work ? Paypal Donation ?

Regards,

Enrique

**Comment by jpmens** [comment]
Please try with Mosquitto 1.5.4; this _sounds_ to me like what we saw in https://github.com/jpmens/mosquitto-auth-plug/issues/374

Feel free to re-open if this is not the case.
