### ISSUE TITLE
Client disconnects when acl auth is 4XX

### ISSUE THREAD

**Issue by ibrahimkoujar** [jpmens/mosquitto-auth-plug#374]
Hello 
I am using mosquitto jwt auth and I faced this problem, when user try to connect to the broker its work normally but when he try subscribe to unauthorized topic the package disconnecting the user socket from broker, its happened only with subscribe.

Thanks...

**Comment by iegomez** [comment]
It was a bug at mosquitto, see https://github.com/eclipse/mosquitto/issues/1016.

**Comment by jpmens** [comment]
@iegomez thank you for the report. Closing.
