### ISSUE TITLE
ACL issue (acc=4)

### ISSUE THREAD

**Issue by matnbaz** [jpmens/mosquitto-auth-plug#376]
Hello,
I use Mosquitto 1.5.3 with Auth plugin (HTTP backend);
The ACL check sends the value of "acc = 4" in the url arguments; however, the documentation states that this value should be 1 (sub) or 2 (pub);
With a value of 4 for acc, ACL check return 403 response.

**Comment by knutanderss** [comment]
+1

**Comment by knutanderss** [comment]
We got around by changing the acl check from (rw >= $2) to (rw >= $2 OR $2 = 4 AND rw >= 1)

**Comment by jpmens** [comment]
Mosquitto 1.5.4 with current git compile of auth plugin uses the constants provided by Mosquitto when performing ACL checks over HTTP: these correspond to what is documented: 1 on subscribe and 2 on publish.

**Comment by jpmens** [comment]
If the issue persists for you please submit a minimal, reproducible example.
