### ISSUE TITLE
New version to release?

### ISSUE THREAD

**Issue by Bacto** [jpmens/mosquitto-auth-plug#378]
Hi,

First I would like to thank you for your work on this very useful plugin 👍 

The last release has more than a year and 81 commits were done since.
Is it possible to create a new release and in the future to regulary get new releases so we can follow an update process?

Thanks :)
Adrien

**Comment by jpmens** [comment]
You are right, and thanks for the nicely phrased reminder. We still have a number of outstanding issues which have been reported, but as far as I'm concerned this is the best version yet, so I've just [released 0.1.3](https://github.com/jpmens/mosquitto-auth-plug/releases/tag/0.1.3).

**Comment by Bacto** [comment]
Thank you @jpmens for your reactivity!
