### ISSUE TITLE
ACL issue with JWT backend

### ISSUE THREAD

**Issue by bstie** [jpmens/mosquitto-auth-plug#380]
With mosquitto 1.5.4 and a build of mosquitto-auth-plug from the current main branch (master@9fe7b4) I am facing the same issue as in #376.
But it seems to depend on the MQTT-Version that is used to connect by the client.

I am using the JWT-Backend and activated also the files backend (for superusers that should be able to connect, even if my REST-Api should not work correctly)

## When using MQTT 3.1.1 on the client side (using MQTTfx client)

When I try to subcribe the Topic "test/topic", this is what my REST Api receives:

```bash
Started POST "//v1/mqtt_users/acl" for 159.69.40.219 at 2018-11-27 15:10:59 +0100
Processing by Api::V1::MqttUsersController#acl as JSON
 Parameters: {"topic"=>"test/topic", "acc"=>"4", "clientid"=>"client id not available"}
```

When I try to publish the Topic "test/topic", this is what my REST Api receives:

```bash
Started POST "//v1/mqtt_users/acl" for 159.69.40.219 at 2018-11-27 15:22:21 +0100
Processing by Api::V1::MqttUsersController#acl as JSON
 Parameters: {"topic"=>"test/topic", "acc"=>"2", "clientid"=>"client id not available"}
```

## When using MQTT 3.1 on the client side (using MQTTfx client)

When I try to subcribe the Topic "test/topic", my REST Api does not receive a request.
When displaying the mosquitto.log I can see, that mosquitto/mosquitto-auth-plug accepts the subscription without asking the external API (mosquittos cache is deactivated).
```bash
1543329974: Received SUBSCRIBE from 49be1e4dff4c4b3c8c32612f492556ac
1543329974: 	test/topic (QoS 0)
1543329974: 49be1e4dff4c4b3c8c32612f492556ac 0 test/topic
1543329974: Sending SUBACK to 49be1e4dff4c4b3c8c32612f492556ac
```

When I try to publish the Topic "test/topic", this is what my REST Api receives:

```bash
Started POST "//v1/mqtt_users/acl" for 159.69.40.219 at 2018-11-27 15:19:44 +0100
Processing by Api::V1::MqttUsersController#acl as JSON
 Parameters: {"topic"=>"test/topic", "acc"=>"2", "clientid"=>"client id not available"}
```

So the `acc` value seems to depend on the MQTT-Version.

**Comment by jpmens** [comment]
This is related to #356

**Comment by bstie** [comment]
Thank you for the hint that this is related to #356, I didn't notice that. 

So for now I could change my API to accept `acc`-values `1` and `4` for read/subscribe acl requests. I will use MQTT 3.1.1 anyways, so this should work.

I will check again if the MQTT 3.1 subscribe acl request really was not cached.

The auth-plugin related part of my mosquitto config looks like this:

```bash
auth_plugin /etc/mosquitto/plugins/auth-plug_with-jwt_1.4.15.so
auth_opt_backends files,jwt

# files backend
auth_opt_password_file /etc/mosquitto/passwords.pw
auth_opt_acl_file /etc/mosquitto/access_control_list.acl

# jwt backend
auth_opt_http_ip <ip removed...>
auth_opt_http_hostname <hostname removed...>
auth_opt_http_with_tls true
auth_opt_http_port 443
auth_opt_http_getuser_uri /v1/mqtt_users/auth
auth_opt_http_superuser_uri /v1/mqtt_users/superuser
auth_opt_http_aclcheck_uri /v1/mqtt_users/acl
auth_opt_cacheseconds 0
```

I noticed that the `auth_opt_cacheseconds` option is deprecated, so I should use `auth_opt_acl_cacheseconds` instead, right?
Is it possible that this is the reason, why mosquitto did not ask my API when I was using MQTT 3.1 on the client side?
(so maybe the cache was not disabled due to my wrong config)
