### ISSUE TITLE
Inconsistencies between HTTP and JWT code & configuration

### ISSUE THREAD

**Issue by rmilenko** [jpmens/mosquitto-auth-plug#381]
Based on most recend git clone, here's what I have noticed:

be_http.c (code staring at line 135)
---
```
// enable the https
if (strcmp(conf->with_tls, "true") == 0){
    sprintf(url, "https://%s:%d%s", conf->hostname, conf->port, uri);
else{
    sprintf(url, "http://%s:%d%s", conf->hostname, conf->port, uri);
}
```
----

be_jwt.c (code starting at line 125)
---
```
snprintf(url, sizeof(url), "%s://%s:%d/%s",
    strcmp(conf->with_tls, "true") == 0 ? "https" : "http",
    conf->hostname ? conf->hostname : conf->ip,
    conf->port,
    uri);
```
---

Now, notice that be_jwt.c there's additional slash "/" between %d and %s (port and uri).
This slash doesn't exist in be_http.c code, which leads to different format of uri in mosquitto.conf.

Therefore, if using HTTP backend URI must begin with slash "/", but MUST NOT begin with slash if using JWT backend.

**Comment by jpmens** [comment]
Thank you @rmilenko; I've fixed that in `be-http.c`

**Comment by rmilenko** [comment]
You're welcome,
but does this mean that URIs in old mosquitto.conf files must be modified to REMOVE leading slash?

Also, configuration example for HTTP backend still have URIs starting with slash "/".

**Comment by jpmens** [comment]
I've been caught not paying attention it seems. I've reverted back to the original documented behaviour. `uri` begin with a slash in both backends now. 

Thank you for paying attention.
