### ISSUE TITLE
problem with sizeof 

### ISSUE THREAD

**Issue by alljoynsville** [jpmens/mosquitto-auth-plug#387]
be-http.c: In function 'http_post':
be-http.c:136:22: error: argument to 'sizeof' in 'snprintf' call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess]
  snprintf(url, sizeof(url), "%s://%s:%d%s",
                      ^
cc1: all warnings being treated as errors
make: *** [<builtin>: be-http.o] Error 1

**Comment by jpmens** [comment]
Fixed, thank you.
