### ISSUE TITLE
Websocket error: connection was lost (verbose output)

### ISSUE THREAD

**Issue by devorrah** [jpmens/mosquitto-auth-plug#389]
_Websockets isn't working for me. I get an interesting message on mosquitto startup (in bold)_

1544585559: mosquitto version 1.5.5 starting
1544585559: Config loaded from /etc/mosquitto//mosquitto.conf.
1544585559: |-- *** auth-plug: startup
1544585559: |-- ** Configured order: mysql

1544585559: |-- }}}} MYSQL
1544585559: |-- SSL is disabled
**1544585559: Opening websockets listen socket on port 1888.
1544585559: Initial logging level 255
1544585559: Libwebsockets version: 1.7.1 unknown-build-hash
1544585559: IPV6 not compiled in
1544585559: libev support compiled in but disabled**
1544585559:  LWS_DEF_HEADER_LEN    : 1024
1544585559:  LWS_MAX_PROTOCOLS     : 5
1544585559:  LWS_MAX_SMP           : 32
1544585559:  SPEC_LATEST_SUPPORTED : 13
1544585559:  sizeof (*info)        : 216
1544585559:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
1544585559:  default timeout (secs): 20
1544585559:  Threads: 1 each 1024 fds
1544585559:  mem: context:         62808 bytes (58712 ctx + (1 thr x 4096))
1544585559:  mem: http hdr rsvd:   67712 bytes (1 thr x (1024 + 3208) x 16))
1544585559:  mem: pollfd map:       8192
1544585559:  mem: platform fd map:  8192 bytes
1544585559:  LWS_MAX_EXTENSIONS_ACTIVE: 2
1544585559:  mem: per-conn:          808 bytes + protocol rx buf
1544585559:  canonical_hostname = amd-box
1544585559:  Compiled with OpenSSL support
1544585559:  Using non-SSL mode
1544585559:  SSL ECDH curve 'prime256v1'
1544585559:  interface lo vs 127.0.1.1
1544585559:  interface enp1s0 vs 127.0.1.1
1544585559:  interface lo vs 127.0.1.1
1544585559:  interface enp1s0 vs 127.0.1.1
1544585559:  interface lo vs 127.0.1.1
1544585559:  interface enp1s0 vs 127.0.1.1
1544585559:  interface enp1s0 vs 127.0.1.1
1544585559:  interface enp1s0 vs 127.0.1.1
1544585559: insert_wsi_socket_into_fds: 0xa202d0: tsi=0, sock=8, pos-in-fds=1
1544585559:  Listening on port 1888
1544585559: Opening ipv4 listen socket on port 1883.
1544585559: Opening ipv6 listen socket on port 1883.

_I can publish and subscribe without a problem on MQTT port 1883 but when I type this..._
**mosquitto_pub -h 127.0.1.1 -p 1888 -t mega/secret -m "testing is for suckers" -u su1 -P myPassword
Error: The connection was lost.**

_I get this output:_

1544585381: not calling back closed mode=0 state=2
1544585381: lws_free_wsi: 0x13b9c90, remaining wsi 1
1544585382: accepted new conn  port 43564 on fd=12
1544585382: Accepted 0x13b9c90 to tsi 0
1544585382: lws_adopt_socket: new wsi 0x13b9c90
1544585382: insert_wsi_socket_into_fds: 0x13b9c90: tsi=0, sock=12, pos-in-fds=2
1544585382: lws_header_table_attach: wsi 0x13b9c90: ah (nil) (tsi 0)
1544585382: lws_header_table_attach: wsi 0x13b9c90: ah 0x13a0170: count 1 (on exit)
1544585382: lws_server_socket_service: 0x13b9c90: rxpos:0 rxlen:0
1544585382: lws_server_socket_service: wsi 0x13b9c90, ah->rxlen = 50
1544585382: lws_read: incoming len 50
1544585382: issuing 50 bytes to parser
1544585382: WSI_TOKEN_NAME_PART '' (mode=0)
1544585382: Unknown method - dropping
1544585382: lws_parse failed
1544585382: lws_header_table_detach: wsi 0x13b9c90: ah 0x13a0170 (tsi=0, count = 1)
1544585382: closing connection at lws_read bail:
1544585382: lws_close_free_wsi: shutting down connection: 0x13b9c90
1544585382: lws_server_socket_service: wsi 0x13b9c90 read 0
1544585382: lws_server_socket_service: read 0 len
1544585382: lws_close_free_wsi: real just_kill_connection: 0x13b9c90
1544585382: remove_wsi_socket_from_fds: wsi=0x13b9c90, sock=12, fds pos=2, end guy pos=3, endfd=0

_for the life of me I can't figure this out. Is the libwebsockets version too old?_
_Do I have to compile Libewebsockets myself?_

**Comment by devorrah** [comment]
_ok so I uninstalled EVERYTHING and started from scratch. Everything compiled fine and now I am trying to configure websockets. Please let me know what I am doing wrong._

_my mosquitto.conf contains:_

**Extra listeners section**
#listener port-number [ip address/host name]
**listener 1888/127.0.0.1
protocol websockets**


_Then in terminal:_
mosquitto_pub -p 1888 -t mega/secret -m "testing websockets" -u devy -P myPassword
**Error: A network protocol error occurred when communicating with the broker.**


_Mosquitto broker outputs:_
**1544655860:  forbidding on uri sanitation**

BTW, this works using MQTT protocol

**Comment by jpmens** [comment]
If it works using MQTT then this is not an authentication plugin problem.

**Comment by devorrah** [comment]
I C. Thank you JPMens

**Comment by devorrah** [comment]
It appears the mosuitto_pub utility does not support websockets. I'll test my installations using the PAHO javascript library.
https://github.com/eclipse/mosquitto/issues/391
