### ISSUE TITLE
segfault with http when client publish without user

### ISSUE THREAD

**Issue by pat1** [jpmens/mosquitto-auth-plug#43]
mosquitto_pub -t /test -m ciao
produce segfault:

Using host libthread_db library "/lib64/libthread_db.so.1".
1416706120: mosquitto version 1.3.5 (build date 2014-10-08 22:06:55+0000) starting
1416706120: Config loaded from /etc/mosquitto/mosquitto.conf.
1416706120: |-- **\* auth-plug: startup
1416706120: |-- *\* Configured order: http

1416706120: |-- getuser_uri=/auth
1416706120: |-- superuser_uri=/superuser
1416706120: |-- aclcheck_uri=/acl
1416706120: Opening ipv4 listen socket on port 1883.
1416706120: Opening ipv6 listen socket on port 1883.
1416706127: New connection from 192.168.1.172 on port 1883.
1416706127: New client connected from 192.168.1.172 as mosqpub/3837-asus-pat1 (c1, k60).
1416706127: Sending CONNACK to mosqpub/3837-asus-pat1 (0)
1416706127: |-- mosquitto_auth_acl_check(..., mosqpub/3837-asus-pat1, NULL, /test, MOSQ_ACL_WRITE)

Program received signal SIGSEGV, Segmentation fault.
0x00000036157398cf in __strlen_sse42 () from /lib64/libc.so.6
(gdb) where
#0  0x00000036157398cf in __strlen_sse42 () from /lib64/libc.so.6
#1  0x00007ffff7baa780 in hexify (clientid=0x652460 "mosqpub/3837-asus-pat1", username=0x0, topic=0x650b60 "/test", access=2,

```
hex=0x7fffffffd2c0 "`\ve") at cache.c:64
```
#2  0x00007ffff7babfd8 in cache_q (clientid=0x652460 "mosqpub/3837-asus-pat1", username=0x0, topic=0x650b60 "/test", access=2,

```
userdata=0x64dd20) at cache.c:144
```
#3  0x00007ffff7ba84df in mosquitto_auth_acl_check (userdata=0x64dd20, clientid=0x652460 "mosqpub/3837-asus-pat1",

```
username=0x0, topic=0x650b60 "/test", access=2) at auth-plug.c:440
```
#4  0x000000000040fbcb in ?? ()
#5  0x000000000040f255 in ?? ()
#6  0x000000000040b212 in ?? ()
#7  0x000000000040401b in ?? ()
#8  0x0000003615621b45 in __libc_start_main () from /lib64/libc.so.6
#9  0x0000000000404139 in ?? ()

**Comment by whidbey** [comment]
what?means when publish a message,you need to check the user again and again?
why dont' just auth functions,and when publish message no need auth any more?
