### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by erhuabushuo** [jpmens/mosquitto-auth-plug#53]
undefined symbol: ares_library_init	(./auth-plug.so)
undefined symbol: ares_library_cleanup	(./auth-plug.so)

**Comment by jpmens** [comment]
This is turning into a FAQ ...

You appear to have Mosquitto compiled with SRV record support. Either disable that and rebuild, or intall lib ares for the DNS  resolving capabilities.

**Comment by w3hacker** [comment]
yum install c-ares-devel  -y
