### ISSUE TITLE
Yet another unable to load auth-plugin.

### ISSUE THREAD

**Issue by AggelosGroumas** [jpmens/mosquitto-auth-plug#55]
Hi, i followed #33 but no luck. Any help appreciated.

1422608200: mosquitto version 1.3.5 (build date 2015-01-29 19:51:52+0200) starting
1422608200: Config loaded from mosquitto.conf.
LOADERROR /usr/lib/x86_64-linux-gnu/auth-plug.so: **undefined symbol: deflate**
1422608200: Error: Unable to load auth plugin "/usr/lib/x86_64-linux-gnu/auth-plug.so".

--------------------------------------------------------------------------------------------
System Info:
- OS: Ubuntu 14.04.1 LTS
- Linux 3.13.0-44-generic x86_64 GNU/Linux
- package: zlib1g-dev / Status: install ok installed

--------------------------------------------------------------------------------------------
**ldd /usr/local/sbin/mosquitto**
	linux-vdso.so.1 =>  (0x00007fff840ef000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6a3c388000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6a3c082000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6a3be79000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f6a3bc1b000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f6a3b841000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a3b47a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6a3c5a8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6a3b25c000)

**ldd auth-plug.so**
	linux-vdso.so.1 =>  (0x00007fff83fba000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f526b99c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f526b5d6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f526b3d1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f526c29c000)

--------------------------------------------------------------------------------------------
**cat config.mk**
BACKEND_CDB ?= no
BACKEND_MYSQL ?= yes
BACKEND_SQLITE ?= no
BACKEND_REDIS ?= no
BACKEND_POSTGRES ?= no
BACKEND_LDAP ?= no
BACKEND_HTTP ?= no

MOSQUITTO_SRC = /home/gkraggel/Downloads/mosquitto/mosquitto-1.3.5

OPENSSLDIR = /usr/include/openssl

--------------------------------------------------------------------------------------------
**locate zlib.h**
/usr/include/zlib.h
/usr/src/linux-headers-3.13.0-32/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/crypto/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/jffs2/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/squashfs/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/ubifs/fs/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-40/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-40-generic/include/config/crypto/zlib.h
/usr/src/linux-headers-3.13.0-40-generic/include/config/jffs2/zlib.h
/usr/src/linux-headers-3.13.0-40-generic/include/config/squashfs/zlib.h
/usr/src/linux-headers-3.13.0-40-generic/include/config/ubifs/fs/zlib.h
/usr/src/linux-headers-3.13.0-40-generic/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-43/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-43-generic/include/config/crypto/zlib.h
/usr/src/linux-headers-3.13.0-43-generic/include/config/jffs2/zlib.h
/usr/src/linux-headers-3.13.0-43-generic/include/config/squashfs/zlib.h
/usr/src/linux-headers-3.13.0-43-generic/include/config/ubifs/fs/zlib.h
/usr/src/linux-headers-3.13.0-43-generic/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-44/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-44-generic/include/config/crypto/zlib.h
/usr/src/linux-headers-3.13.0-44-generic/include/config/jffs2/zlib.h
/usr/src/linux-headers-3.13.0-44-generic/include/config/squashfs/zlib.h
/usr/src/linux-headers-3.13.0-44-generic/include/config/ubifs/fs/zlib.h
/usr/src/linux-headers-3.13.0-44-generic/include/linux/zlib.h

**Comment by jpmens** [comment]
`undefined symbol: deflate` sounds like linking with `-lz` is missing

**Comment by jpmens** [comment]
or is it `-lzlib`?

**Comment by AggelosGroumas** [comment]
Thanks for your response. I was putting the -lz flag in the wrong place so i had the illusion i was linking. 
For future readers:  Modify LDADD variable adding "-lz" at the end.

Now i get however:
1422613437: Config loaded from mosquitto.conf.
1422613437: |-- *** auth-plug: startup
|-- No backends configured.
|-- *** ABORT.

**Comment by jpmens** [comment]
> |-- No backends configured.
> |-- *** ABORT.

Looks pretty self-explanatory to me.

**Comment by AggelosGroumas** [comment]
Yes i know, the thing is i had a mysql backend configured
I used the .sql script located in the examples folder.

conf file is: 
pid_file ./mosquitto.pid

persistence true
persistence_file mosquitto.db
persistence_location /tmp/
connection_messages true
log_timestamp true
log_dest stderr

log_type debug

listener 1883

auth_plugin /usr/lib/x86_64-linux-gnu/auth-plug.so
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname test
auth_opt_user root
auth_opt_pass root
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = '%s' AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw >= %d)

**Comment by jpmens** [comment]
You have not told the plugin which backend to use!

`auth_opt_backends`

**Comment by AggelosGroumas** [comment]
Indeed that slipped through. 
Thank you very much for your time!
