### ISSUE TITLE
ACL check only on publish

### ISSUE THREAD

**Issue by cairesvs** [jpmens/mosquitto-auth-plug#66]
Using the configuration from examples/mosquitto-mysql.conf when I publish to the topic I got denied but I  still can subscribe without any problem.

**Comment by jpmens** [comment]
I admit the examples/ aren't kept up to date. Please consult the README.md in the top-level for the documentation as the queries have changed slightly.

**Comment by cairesvs** [comment]
I check the README.md as well but I still got the same results, I don't if this will help but my current configuration is this:

protocol mqtt
allow_anonymous false
auth_plugin /path/to/auth-plug.so
auth_opt_backends mysql
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname mosquitto
auth_opt_user root
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = '%s' AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw >= %d)
auth_opt_anonusername AnonymouS

The mosquitto_auth_acl_check is only call on publish.

**Comment by cairesvs** [comment]
@jpmens I just found out that on the version 1.4 of mosquitto there is a bug that ignores acl check on subscribe because the wildcards problems.

**Comment by simonmorley** [comment]
@cairesvs Did you ever find a work-around for this?
