### ISSUE TITLE
Redis ACL question

### ISSUE THREAD

**Issue by SeanChen59** [jpmens/mosquitto-auth-plug#68]
Hi, JPmens:

I am working on mosquito authentication and ACL. Redis is chosen as back-end. The authentication by username and password pair is working well. But I have difficulties to use it on the ACL.  What's the correct ACL data structure in Redis? It will be great helpful for the people who are interested in this topic if you can add more detail,  samples or links on your plugin main page.

I have posted same question with more info at:
http://stackoverflow.com/questions/29474742/how-to-use-redis-as-back-end-for-mosquitto-acl-jpmens-plugin-is-used

Thank you very much.

Regards,
Sean Chen

**Comment by jpmens** [comment]
I believe you've found out how to do this.
