### ISSUE TITLE
Cached ACLs?

### ISSUE THREAD

**Issue by edgar89** [jpmens/mosquitto-auth-plug#69]
Hi, thanks for your hard work!
I have a question for you. We will have a production environment with some thousands client that will publish selected messages. Our client wants to be able to allow/deny access to single devices while mosquitto is running.
However it seems that this hot swap does not work well. 
Restarting the mosquitto service fixes the issues.

Can you help me resolve this?

Giuseppe

**Comment by karlp** [comment]
You can HUP the mosquitto process, or you can use a plugin that handles
it dynamically for you.

edgar89 <notifications@github.com> wrote:
> Hi, thanks for your hard work!
> I have a question for you. We will have a production environment with
> some thousands client that will publish selected messages. Our client
> wants to be able to allow/deny access to single devices while mosquitto
> is running.
> However it seems that this hot swap does not work well. 
> Restarting the mosquitto service fixes the issues.
> 
> Can you help me resolve this?
> 
> Giuseppe
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jpmens/mosquitto-auth-plug/issues/69

-- 
Sent using Mailpile, Free Software from www.mailpile.is

**Comment by jpmens** [comment]
Well, part of the reason, I suppose for you to be using this plugin is to allow precisely that -- dynamic updates to the backend ACLs which will then be effective.

**Comment by edgar89** [comment]
Hi jpmens, sorry for bothering you, it was my bad. I completely missed the auth_opt_cacheSeconds param you specified in the official documentation.

Putting this param to 5sec fixed the issue.
Thanks again

Giuseppe

**Comment by jpmens** [comment]
Glad you got it working.
