### ISSUE TITLE
Configuration loading fails with multiple spaces between key and value in mosquitto.conf

### ISSUE THREAD

**Issue by acataluddi** [jpmens/mosquitto-auth-plug#70]
Dear Jan-Piet,
I found that the plug-in is not able to correctly parse configuration when there are multiple spaces between the key and value.

For example, consider a configuration block like the following:

```conf
auth_plugin               /usr/local/lib/mosquitto/auth-plug.so
auth_opt_backends         redis
auth_opt_redis_host       127.0.0.1
auth_opt_redis_port       6379
```
I produced a little patch that fix this issue, I'll open a pull request.

Regards
Adriano C.

**Comment by jpmens** [comment]
Adriano, this is, unfortunately not something under the plugin's control I think; it's a general issue of Mosquitto's configuration file format. While your patch may solve the issue for the few plugin configuration values, I believe you'll find that the rest of Mosquitto will suffer with a "neat" config file. I think you'd be better off providing a patch to the Mosquitto project.

**Comment by acataluddi** [comment]
Thank you Jan-Piet,
I have a working patch for the `mosquitto-auth-plug` that works for every backend. I will try to patch also Mosquitto. What if, for now, we at least solve it locally on the plug-in?

**Comment by karlp** [comment]
Are you using mosquitto 1.4.0?  this should have only affected 1.4.0, 1.4.1 fixed this, and it didn't exist in earlier versions to my understanding.

**Comment by acataluddi** [comment]
Hello Karl,
I compiled the auth-plug against Mosquitto `1.4.2` and experienced this issue. Is it possibile it was'nt properly fixed?

Thank you
Adriano

**Comment by karlp** [comment]
If it is, I think this should be filed and taken up with mosquitto itself, not worked around in _this_ plugin (The issue would undoubtedly affect others)

**Comment by acataluddi** [comment]
Hello Karl,
I agree and I'll focus fixing it also in Mosquitto: for now the patch solves the issue at lest in this plug-in (that is what I was needing for urgentely) :).

Thank you
Adriano

**Comment by jpmens** [comment]
Unless you can prove that this is a fault of the plugin, I will not take this patch. I believe, corroborated by the above discussion, that it's a problem in Mosquitto's config parser. I _seem_ to recall that that was addressed by Roger, but I cannot check now nor do I recall in which version.

Your workaround, for now, will be to snip leading white space in your configuration file.

**Comment by acataluddi** [comment]
Ok Jan-Piet,
I'll update this discussion when I'll have ready the patch for the Mosquitto's config parser. 

For what is my understanding, me too I'm convinced that the bug is related to Mosquitto because the plug-in receives the parsed data structure not trimmed in the function `mosquitto_auth_plugin_init` inside the struct `mosquitto_auth_opt *auth_opts`.

So, if you want, we can close this pull request.

Thank you for cooperation
Adriano

**Comment by ralight** [comment]
auth_opt_ options were special cased in mosquitto and I missed it for 1.4.1. It'll be fixed in 1.4.2.

**Comment by acataluddi** [comment]
Thank you Roger.
Adriano.

**Comment by jpmens** [comment]
Closing. Thanks @ralight
