### ISSUE TITLE
HTTP auth - params string not null terminated

### ISSUE THREAD

**Issue by adriancretu** [jpmens/mosquitto-auth-plug#74]
When trying to use simple HTTP user+pass authentication, the plugin will send garbage string in the URL right before the "username=..." parameters start, making the auth endpoint unable to read the username. Looking in the code I see that the custom parameters string is allocated but never null-terminated when no custom params are defined in config...
As a workaround, all the three custom exported parameter options have to be defined inside mosquitto.conf, so that the code will add some sane strings from potential environment values:

auth_opt_http_getuser_params domain=DOMAIN,port=PORT
auth_opt_http_superuser_params domain=DOMAIN,port=PORT
auth_opt_http_aclcheck_params domain=DOMAIN,port=PORT

**Comment by jpmens** [comment]
Thanks for your report. I'm looking at this by I can't see what you mean (possibly due to lack of coffee).
Can you point out a line number where you suspect the missing null-termination?

**Comment by adriancretu** [comment]
Sure: https://github.com/jpmens/mosquitto-auth-plug/blob/master/be-http.c#L147
The problem occurs when there are no custom configurations for env params. Garbage bytes are inserted in the request string.
