### ISSUE TITLE
Unable to load auth plugin "undefined symbol: mosquitto_topic_matches_sub"

### ISSUE THREAD

**Issue by ndorigatti** [jpmens/mosquitto-auth-plug#75]
Hello, 
I'm trying to use this library on an ubuntu 14.04 i686 (it's a virtual machine).

I installed the mosquitto 1.4.1 library from ppa repo (following mosquitto guides) and installed python packages (as stated in this repo readme) and 
libmosquitto-dev

Then i downloaded sources for mosquitto 1.4.1, cloned this repo inside src directory so:
mosquitto-1.4.1
-/src
--/mosquitto-auth-plug
---/Makefile,README etc..

Then if i run make in "mosquitto-auth-plug" i got errors, so i changed makefile (according to a friend that successfully uses mosquitto 1.4.1 and this pluging on a mac), first line now is:
CFLAGS = -std=gnu99 -fPIC -I../lib `python-config --includes` -I /home/testuser/mosquitto/mosquitto-1.4.1/src  -Wall -Wextra -O2

where /home/testuser/mosquitto/mosquitto-1.4.1/src is the directory of the sources (and i have to admit I'm not sure about this line because "-I../lib" is wrong, since there is no lib folder in the src folder!
Anyway, the library compiles without warnings (I already put the printf("LOADERROR" line in the securty.c file, but no error arise).

Then if i link in the config file the plugin and try to start mosquitto:
1430984744: mosquitto version 1.4.1 (build date 2015-04-03 07:41:31+0000) starting
1430984744: Config loaded from /etc/mosquitto/zito.conf.
1430984744: Error: Unable to load auth plugin "/var/lib/mosquitto/auth_plugin_pyauth.so".
1430984744: Load error: /var/lib/mosquitto/auth_plugin_pyauth.so: undefined symbol: mosquitto_topic_matches_sub

(config file is almost empty, and /var/lib/mosquitto/auth_plugin_pyauth.so" is there)

It's been a whole day I'm trying to make it work, but now I given up and need some help, can you help me?

Thanks

**Comment by jpmens** [comment]
What is `auth_plugin_pyauth.so` ?

**Comment by ndorigatti** [comment]
the result of the "make" command as per "compiling" guideline

**Comment by jpmens** [comment]
Are you actually reporting this to the right project? ;-)
This is `mosquitto-auth-plug`, and there is no such thing as `auth_plugin_pyauth` here.

**Comment by ndorigatti** [comment]
I'm so sorry, you are right... -.-
I am following too much tabs... sorry
