### ISSUE TITLE
mosquitto 1.4.2 crash

### ISSUE THREAD

**Issue by kenshiro75** [jpmens/mosquitto-auth-plug#76]
hi,

i've compiled the auth-plug and got the auth-plug.so file correctly : i modified the mosquitto.conf file adding the correct path for  auth-plug.so and mysql backend . 
i login as root but when i start mosquitto's service it crashes.
on the contrary if i comment the added auth-plug options in the config file mosquitto starts correctly.

some ideas ?

os: Ubuntu 14.04.1 LTS
mosquitto : 1.4.2
mysql : 5.5.38

**Comment by jpmens** [comment]
Show me a) your configuration and b) some logs

**Comment by kenshiro75** [comment]
mosquitto.conf :


# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_type all
log_dest file /var/log/mosquitto/mqtt.log

include_dir /etc/mosquitto/conf.d

listener 1883

listener 1884 127.0.0.1
protocol websockets

allow_anonymous false

auth_plugin /home/zzzzz/mosquitto-auth-plug/auth-plug.so
auth_opt_backends mysql
auth_opt_host localhost
auth_opt_port 3306
auth_opt_dbname xxxxxx
auth_opt_user root
auth_opt_pass yyyyyyy
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = '%s' AND super $
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw >= %d)
auth_opt_anonusername AnonymouS
auth_opt_superusers S*

log file :
well it's empty... this is because as i said mosquitto crashes as soon as i use this config file and does not write anything ...

thank you very much  :)

**Comment by jpmens** [comment]
Then  start it from the console: mosquitto -c config-file -v
We need to see what it's doing.

**Comment by kenshiro75** [comment]
i've launched your command but mosquitto didn't start and no log :(

**Comment by jpmens** [comment]
Nothing on the console?!? That's quite unlikely.

OK. Show me this please: `ldd /path/to/your/mosquitto' and `ldd /path/to/your/plugin.so'

**Comment by kenshiro75** [comment]
root@webserver:/home/xxxx# ldd /usr/sbin/mosquitto
        linux-vdso.so.1 =>  (0x00007fffe9dfe000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2dfda84000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2dfd77e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2dfd575000)
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f2dfd36b000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2dfd10d000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f2dfcd31000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f2dfcb2c000)
        libwebsockets.so.3 => /usr/lib/x86_64-linux-gnu/libwebsockets.so.3 (0x00007f2dfc91b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2dfc555000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2dfdc91000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2dfc337000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f2dfc11d000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2dfbf03000)

		

root@webserver:/home/xxxx# ldd /home/xxxx/mosquitto-auth-plug/auth-plug.so
        linux-vdso.so.1 =>  (0x00007fff66bfe000)
        libmysqlclient.so.18 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007fa43068e000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fa4302b3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa42feed000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa42fcd4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa42fad0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa42f8b1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa42f5ab000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa430de2000)

maybe ?

**Comment by jpmens** [comment]
Please add a

```
log_dest stderr
```

and try launching again to see something on console.

(Oh, and please when posting logs, configs, etc, would you wrap them between lines containing three backticks  ? That makes it much easier to read on github :)

**Comment by kenshiro75** [comment]
```
root@webserver:/home/xxxx/mosquitto-auth-plug# /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf -v
1432819103: mosquitto version 1.4.2 (build date 2015-05-12 20:14:11+0000) starting
1432819103: Config loaded from /etc/mosquitto/mosquitto.conf.
1432819103: Error: Unable to load auth plugin "/home/xxxx/mosquitto-auth-plug/auth-plug.so".
1432819103: Load error: /home/xxxx/mosquitto-auth-plug/auth-plug.so: undefined symbol: ares_library_init
```
ok this error is the same as the issue https://github.com/jpmens/mosquitto-auth-plug/issues/33#
so i've already added to config.mk a new line with

```
WITH_SRV:=no
```
then 
```
make clean
make
```
(also rebuilt mosquitto source) 
but i get always the same error...

**Comment by jpmens** [comment]
That looks better :)

If you're getting the same error, one (or both) of the binaries are still being linked with the ares library. You say you 'added a line' to config.mk -- make sure it's not in there twice.

**Comment by kenshiro75** [comment]
ok now i can start mosquitto!

just to be clear : the WITH_SRV:=no option is in the config.mk of MOSQUITTO' source dir!
maybe i'm a dumb but it was not clear at all!

thank you very much!

**Comment by jpmens** [comment]
Glad you got it working. (Yes, it's in Mosquitto's config.mk -- sorry if that got you confused.)
