### ISSUE TITLE
Can't authenticate on mysql

### ISSUE THREAD

**Issue by kenshiro75** [jpmens/mosquitto-auth-plug#77]
hi,

after having successfully started mosquitto, now i get 

```
1432826211: New connection from ::1 on port 1883.
1432826211: |-- mosquitto_auth_unpwd_check(xxxx)
1432826211: |-- ** checking backend mysql
1432826211: |-- getuser(xxxx) AUTHENTICATED=0 by none
```

i used ./np to create the hash of testpassword :
PBKDF2$sha256$901$0mse2Mr2YeE8Y8t7$RLMyCjyX0o8al7u+ZaxRST1l6ssDlizo
but nothing... 

my config and related are in https://github.com/jpmens/mosquitto-auth-plug/issues/76

any idea ?

**Comment by jpmens** [comment]
And you are sure that your query

```
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
```

is correct? and you are attempting to connect with a user which exists, and with a *cleartext* password which matches what you gave `./np` ?

**Comment by kenshiro75** [comment]
ok the problem was the VARCHAR 'pw' database field : it was 45 chars too short for the PBKDF2 hash password.
now i've extended it to 255 chars and the authentication is going on :) 

however i need to solve another problem too : mqttwarn plugin !!

yes i use your mqttwarn plugin to save mqtt's messages into mysql but when i solved the problem with the users' authentication i got a problem with mqttwarn.

when i publish a message now the mqtt broker logs like this :
```
...
1432903541: Sending SUBACK to CFSyqrCrCwumhWagxNEGZ
1432903543: |-- mosquitto_auth_acl_check(..., CFSyqrCrCwumhWagxNEGZ, userXXX, /test, MOSQ_ACL_WRITE)
1432903543: |-- aclcheck(userXXX, /test, 2) SUPERUSER=Y by mysql
1432903543: |--  Cached  [714A04BF556386462CC1C8BDCD22621C173B4965] for (CFSyqrCrCwumhWagxNEGZ,userXXX,2)
1432903543: Received PUBLISH from CFSyqrCrCwumhWagxNEGZ (d0, q0, r0, m0, '/test', ... (114 bytes))
1432903543: |-- mosquitto_auth_acl_check(..., mqttwarn, anonymous, /test, MOSQ_ACL_READ)
1432903543: |-- user anonymous was authenticated in back-end 0 (mysql)
1432903543: |-- aclcheck(anonymous, /test, 1) AUTHORIZED=0 by mysql
1432903543: |--  Cached  [D1E60DD788C9F14D9BEB019603C242420FB647E8] for (mqttwarn,anonymous,1)
1432903543: |-- mosquitto_auth_acl_check(..., CFSyqrCrCwumhWagxNEGZ, userXXX, /test, MOSQ_ACL_READ)
1432903543: |-- aclcheck(userXXX, /test, 1) SUPERUSER=Y by mysql
1432903543: |--  Cached  [3B7AEFA09C922FC4B906F353DF846B9A031C9BF3] for (CFSyqrCrCwumhWagxNEGZ,userXXX,1)
1432903543: Sending PUBLISH to CFSyqrCrCwumhWagxNEGZ (d0, q0, r0, m0, '/test', ... (114 bytes))
...
```
as you see i can correctly connect to the broker and publish messages but when mqttwarn try to connect to the broker to save the message it uses the 'anonymous'  user ...

my mqttwarn config file is :
```
[defaults]
hostname     = 'localhost'  ; default
port         = 1883
clientid     = 'mqttwarn'
username     = userXXX
password     = userPWD
lwt          = 'clients/mqttwarn'
skipretained = False
cleansession = False

...
[config:mysql]
host  =  'localhost'
port  =  3306
user  =  'mysqlUSER'
pass  =  'mysqlPWD'
dbname  =  'mqtt'
targets = {
          # tablename  #fallbackcolumn
 'm2'   : [ 'payloads_log',   'full'            ]
  }

...
```

with the same config file and no auth-plugin i've no problem to log messages into mysql...

any idea ?

**Comment by jpmens** [comment]
The plugin documentation describes how to handle anonymous users. 
Also, if you can authenticate from a client, mqttwarn will be able to do so as well -- there's no difference.
