### ISSUE TITLE
Memory error when connecting to mongo backend

### ISSUE THREAD

**Issue by cookejames** [jpmens/mosquitto-auth-plug#78]
I'm getting the following error when authenticating against a mongo db. I've tracked the error down to line #437 of auth-plug.c `free(phash);` however my knowledge of C isn't good enough to figure out how to fix it. Any suggestions would be appreciated.

```
mongo: [mongodb://172.17.0.1:27017]
2015/06/13 22:36:18.0304: [  870]:    DEBUG:      cluster: Client initialized in direct mode.
1434234983: |-- mosquitto_auth_unpwd_check(james)
1434234983: |-- ** checking backend mongo
1434234983: |-- getuser(james) AUTHENTICATED=1 by mongo
*** Error in `mosquitto': free(): invalid next size (fast): 0x0000000000add770 ***
Aborted (core dumped)
```

auth.conf
```
auth_plugin /root/mosquitto-auth-plug/auth-plug.so
auth_opt_backends mongo
auth_opt_mongo_host 172.17.0.1
auth_opt_mongo_port 27017
```

**Comment by jpmens** [comment]
I don't *think* that can be caused there, but you could do me a favor: comment out the line which says 

```
// free(phash);
```

(line 437) by prepending a double slash as shown. Stop Mosquitto, run `make` and try again.

**Comment by cookejames** [comment]
Commenting it out lets me publish a message however I then get a different error the next time I publish (I think an overflow but I'm not at a computer now)

**Comment by jpmens** [comment]
I trust this has been fixed with today's merges. Feel free to re-issue if you still encounter the problem.
