### ISSUE TITLE
ACL checking fails when using two backends

### ISSUE THREAD

**Issue by Sermus** [jpmens/mosquitto-auth-plug#82]
Please consider the following scenario:
1) The plugin is configured to use to backends - be1 and be2 (no matter what they are)
2) User1 authenticates with be1 (please note that ud->authentication_be is set to the number corresponding to be1 in mosquitto_auth_unpwd_check)
3) User2 authenticates with be2 (please note that ud->authentication_be is set to the number corresponding to be2 in mosquitto_auth_unpwd_check, since ud is global data the previous value of authentication_be is overwritten)
4) User1 tries to post to a topic. The plugin checks ACL assuming that the user us authenticated with the be stored in ud->authentication_be:
The code snippet is:
	nord = ud->authentication_be;
	if (nord < 0 || nord >= NBACKENDS) {
		nord = ud->fallback_be;
	}
	backend_name = (nord >= 0 && nord < NBACKENDS) ?  ud->be_list[nord]->name : "<nil>";

But authenticated_be contains nord associated with User2 because it was overwritten during authentication of User2.

As a result the plugin checks ACL for User1 with be2 and fails because be2 has nothing to do with User1.

**Comment by jpmens** [comment]
Thank you for your report. I haven't studied the code yet, but I think your evaluation is correct. I will address this, but it will take some weeks. (If you are able to and have time to do so, any help is greatly appreciated. :-)
