### ISSUE TITLE
can't receive any message when authenticated by MySQL

### ISSUE THREAD

**Issue by damoyelang1992** [jpmens/mosquitto-auth-plug#84]
I am a newer to mosquitto-auth-plugin,It may be a stupid question.But i can't solve it.
when i configured the mosquitto with the auth-plugin.the log like this 

root@iZ239bulecwZ:~/IoTServer/mosquitto-auth-plug# mosquitto -c /etc/mosquitto/mosquitto.conf
1435979274: mosquitto version 1.4.2 (build date 2015-07-04 09:25:06+0800) starting
1435979274: Config loaded from /etc/mosquitto/mosquitto.conf.
1435979274: |-- *** auth-plug: startup
1435979274: |-- ** Configured order: mysql
1435979274: |-- }}}} MYSQL
1435979274: Opening websockets listen socket on port 9001.
1435979274: Opening ipv4 listen socket on port 1883.
1435979274: Opening ipv6 listen socket on port 1883.
1435979288: New connection from 183.208.143.41 on port 1883.
1435979288: |-- mosquitto_auth_unpwd_check(ps1)
1435979288: |-- ** checking backend mysql
1435979288: |-- getuser(ps1) AUTHENTICATED=1 by mysql
1435979288: New client connected from 183.208.143.41 as mosq_sub_8054_qinfei-L (c1, k60, u'ps1').
1435979299: New connection from 183.208.143.41 on port 1883.
1435979299: |-- mosquitto_auth_unpwd_check(ps1)
1435979299: |-- ** checking backend mysql
1435979299: |-- getuser(ps1) AUTHENTICATED=1 by mysql
1435979299: New client connected from 183.208.143.41 as mosq_pub_8056_qinfei-L (c1, k60, u'ps1').
1435979299: |-- mosquitto_auth_acl_check(..., mosq_pub_8056_qinfei-L, ps1, x, MOSQ_ACL_WRITE)
1435979299: |-- user ps1 was authenticated in back-end 0 (mysql)
1435979299: |-- aclcheck(ps1, x, 2) AUTHORIZED=0 by mysql
1435979299: |--  Cached  [B61BAE88F2954494E08FC02FCBF2DDCFC1F76C92] for (mosq_pub_8056_qinfei-L,ps1,2)
1435979299: Client mosq_pub_8056_qinfei-L disconnected.
when i subscribe the topic like this:

qinfei@qinfei-Lenovo-B470:~$ mosquitto_pub  -h iot.open-smart.cn -t 'x' -m hello -u ps1 -P 123456

But i publish the topic use the same topic & username & password .I can't receive any message.

qinfei@qinfei-Lenovo-B470:~$ mosquitto_sub -h iot.open-smart.cn -t 'x' -u ps1 -P 123456

can you hekp me?

**Comment by jpmens** [comment]
Your publish appears to have worked, but you subscribe after the pub. The message is not retained so you don't see it. 

Sub in one window, then pub from another.

**Comment by damoyelang1992** [comment]
I am sorry ,But it is two window

**Comment by damoyelang1992** [comment]
it worked well before  the auth plugin installed .thank you

**Comment by damoyelang1992** [comment]
The broker is working  you can have a try use the user information and broker domain in my log

**Comment by damoyelang1992** [comment]
I fixed it use your example thank you.
