### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by mewejo** [jpmens/mosquitto-auth-plug#87]
Hi,

Great plugin, working really well. Thank you.

Would it be possible for an option to be added for HTTP Basic Auth for the HTTP module? To authenticate at the moment the only possible options are in the URL itself and via the accessing IP address.

Other than creating a local proxy server to forward calls on elsewhere, there isn't much else I can do.

Do you have any other suggestions, or any plans to implement HTTP Basic Auth?

Thank you,

Josh

**Comment by jpmens** [comment]
That should be possible and is probably rather simple because libCurl supports Basic Auth. I personally have neither plans (nor time) to do that. Care to give it a whack? :-)

**Comment by mewejo** [comment]
I'm not a C guru, so I'll have to ask my colleague to take a look. :) Thanks!
