### ISSUE TITLE
Logging via Mosquitto's lib

### ISSUE THREAD

**Issue by jpmens** [jpmens/mosquitto-auth-plug#9]

**Comment by FernandoGarcia** [comment]
Hi @jpmens !

Any news about this issue?

Best regards.

**Comment by jpmens** [comment]
I tried recently again and crashed the broker (on macOS); I haven't dug in further, but if you can, I'd appreciate it.

**Comment by FernandoGarcia** [comment]
Thanks for quick answer.
Unfortunately I can't help.

**Comment by FernandoGarcia** [comment]
Hi @jpmens !
Is possible use logrotate with this this plugin?
Actually I'm using with Mosquitto with log_dest as /var/log/mosquitto/mosquitto.log but the plugin is saving at /var/log/mosquitto.log, so I have two log files in different places.
The setup for Mosquitto is here: https://github.com/eclipse/mosquitto/issues/385
Best regards.

**Comment by FernandoGarcia** [comment]
Hi!
This issue should be closed after this PR? 
https://github.com/jpmens/mosquitto-auth-plug/pull/299
Best regards.

**Comment by jpmens** [comment]
Working here.
