### ISSUE TITLE
Possible Windows version?

### ISSUE THREAD

**Issue by bluewalk** [jpmens/mosquitto-auth-plug#91]
Would there be a possibility to compile this plugin for Windows versions of mosquitto as well?

**Comment by jpmens** [comment]
I suppose it could be done -- I can't think of anything which would be a major blocker (other than the typical things: dependencies, libraries, and the huge PITA of building on Win32 as I recall it).

You are welcome to give it a try, and I'll assist as much I can. However: I will not do it. :-)

**Comment by bluewalk** [comment]
I have given it a shot and messed around for about two hours with different cross compilers and such but no joy. Think it's easier and faster to start running mosquitto on a linux machine ;-)

**Comment by jpmens** [comment]
"I told you so" ;-)
Indeed. If you have to use Windows, consider a small virtual machine (even Virtualbox) in which to run that. I think you'll be happier all around.

**Comment by whidbey** [comment]
do you mean we have to build it on linux ,and run a windows host,linux client vm?
