### ISSUE TITLE
Getting a not authorized message - but I AM authorized

### ISSUE THREAD

**Issue by csuarezgfx** [jpmens/mosquitto-auth-plug#94]
Can you help me figure this out? Thanks:) These are my config settings:

auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_backends mysql,redis
auth_opt_redis_host 127.0.0.1
auth_opt_redis_port 6379
auth_opt_host 127.0.0.1
auth_opt_port 3306
auth_opt_dbname m2m_members
auth_opt_user daniel
auth_opt_pass secret
auth_opt_userquery SELECT pw FROM users WHERE username = ‘%s’
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = ‘%s’ AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = ‘%s’) AND (rw >= %d)
auth_opt_anonusername AnonymouS

I start mosquitto:

~$ mosquitto -v -c /etc/mosquitto/mosquitto.conf
1444190045: mosquitto version 1.4.4 (build date 2015-10-06 22:41:21-0400) starting
1444190045: Config loaded from /etc/mosquitto/mosquitto.conf.
1444190045: |-- *** auth-plug: startup
1444190045: |-- ** Configured order: mysql,redis

1444190045: |-- }}}} MYSQL
1444190045: |-- }}}} Redis
1444190045: Opening ipv4 listen socket on port 1883.
1444190045: Opening ipv6 listen socket on port 1883.

My mySql db contains the users 'daniel' and 'jjolie' and they both have the same password, 'secret'

The topics and usernames are the ones you provided in the example folder and I added 'daniel'. All users have the same password.

Then I try to sub to an unlisted topic in the database from another terminal:  

mosquitto_sub -t "hello/world" -u daniel -P secret
 And I get : Connection Refused: not authorised.

The broker prints out:

1444190427: New connection from 127.0.0.1 on port 1883.
1444190427: |-- mosquitto_auth_unpwd_check(daniel)
1444190427: |-- ** checking backend mysql
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '��daniel’' at line 1
1444190427: |-- ** checking backend redis
1444190427: |-- getuser(daniel) AUTHENTICATED=0 by none
1444190427: Sending CONNACK to 127.0.0.1 (0, 5)
1444190427: Socket error on client <unknown>, disconnecting.

Then I try to PUB to a listed topic from the topic owner in the database from another terminal:  

mosquitto_pub -t "loc/jjolie" -m "testmessage" -u jjolie -P secret
Connection Refused: not authorised.

Same mosquitto response to second user.

Can you help me figure out what is going wrong?

**Comment by jpmens** [comment]
What worries me is the UTF-8 in the mysql error "You have an error ... near". Would you please tripple-verify that you are using normal single quotes in your configuration?

**Comment by csuarezgfx** [comment]
I will do that right now, thank you for the quick response.

**Comment by csuarezgfx** [comment]
my config looked like this and it used the curly single quotes:
auth_opt_userquery SELECT pw FROM users WHERE username = ‘%s’
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = ‘%s’ AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = ‘%s’) AND (rw >= %d)

I changed it to the single quotes on my keyboard:
auth_opt_userquery SELECT pw FROM users WHERE username = '%s'
auth_opt_superquery SELECT COUNT(*) FROM users WHERE username = '%s' AND super = 1
auth_opt_aclquery SELECT topic FROM acls WHERE (username = '%s') AND (rw >= '%d')

And now everything works as expected. Thank you very much for your help and the plugin.

**Comment by jpmens** [comment]
Glad you got it working.
