### ISSUE TITLE
Help to Compile

### ISSUE THREAD

**Issue by vitordangelo** [jpmens/mosquitto-auth-plug#95]
I tray to compile but i had some errors:

Selected backends:          MySQL
Using mosquitto source dir: /etc/mosquitto
OpenSSL install dir:        /usr/bin/openssl

If you changed the backend selection, you might need to 'make clean' first

cc -I/etc/mosquitto/src/ -I/etc/mosquitto/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/bin/openssl/include   -c -o auth-plug.o auth-plug.c
/bin/sh: 1: mysql_config: not found
cc1: error: /usr/bin/openssl/include: Not a directory
make: *** [auth-plug.o] Error 1

Iam using Linux Mint
MySQL is instaled by Xampp

Someone can helpme?

**Comment by jpmens** [comment]
Have you installed the required MySQL client library and its headers? You'll probably find a packaged called `mysqlclients-dev` or something like it.

**Comment by ikarbiztech** [comment]
Check the  OpenSSL directory. You have the path to the executable of the openssl not to the libraries.

Try using something like:
  OPENSSLDIR = /usr/include/openssl 

You will need to install the openssl-devel libraries.

**Comment by 7wonders** [comment]
i know this is an old issue but for anyone else having problems here is an ubuntu on aws ec2 example:

```
sudo add-apt-repository ppa:mosquitto-dev/mosquitto-ppa
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install mosquitto libmosquitto-dev unzip make libssl-dev libmysqlclient-dev
wget https://github.com/jpmens/mosquitto-auth-plug/archive/master.zip
wget http://mosquitto.org/files/source/mosquitto-1.4.8.tar.gz
unzip master.zip
tar -zxvf mosquitto-1.4.8.tar.gz
cd mosquitto-auth-plug-master/
cp config.mk.in config.mk
nano config.mk
MOSQUITTO_SRC = /home/ubuntu/mosquitto-1.4.8
make clean
make
```
