### ISSUE TITLE
ACLs and automatic sub/pub

### ISSUE THREAD

**Issue by vitorrents** [jpmens/mosquitto-auth-plug#96]
Best regards.

I've noticed that when using the plugin. users are automatically subscribed to the topics added to the ACLs. Completely ignoring the order subscribe ("test / topic", 2) on the client. even you subscribe to the topics in ACLs, when the order was omitted: subscribe  ("test / topic", 2).

In my project, a client "can" subscribe to various topics. But one topic at a time. depending on the context.

How I can do, to decide through the command: subscribe ("test / topic", 2). At what topic I want to subscribe?

**Comment by jpmens** [comment]
No "automatic subscribe" occurs in the plugin.  A client subscribes using the subscribe() function. If the subscription is authorized, the client gets messages published to it.

**Comment by vitorrents** [comment]
I am sorry, it was my mistake:

I'm new, i was doing tests and was not properly unsubscribe. I ended up subscribe to all my test topics.
