### ISSUE TITLE
Mongo ACL check filled in

### ISSUE THREAD

**Issue by Spekko** [jpmens/mosquitto-auth-plug#98]
Hi, 
thought there would be a way to contact you through some messaging in github but I find none.

I have filled in the ACL check in be-mongo.c and seems to be working for me so far. Later in the day or tomorrow I will get on the superuser part.

see: https://github.com/Spekko/mosquitto-auth-plug

Regards, and thank you so much for the plugin :)

**Comment by jpmens** [comment]
Closing because #99
